In [1]:
import pandas as pd

In [2]:
pd.options.display.max_rows = 1000

In [22]:
df_may = pd.read_excel('/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/Raw-Data/Reformatted/2018/2018May.xlsx')

In [18]:
df = pd.read_excel('/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/Raw-Data/Reformatted/2018/2018Oct.xlsx')

In [4]:
df_utility = pd.read_csv('/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/ToDatabase/TotalUtilities_v02.csv')

/anaconda3/envs/cds/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (3,6,8,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df.head()

,Premise,Premise Address,City,State,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date
0,10001,300 ACORN ST,ALBANY,GA,216323,NaN,NaN,CDEP,NaN,NaN,NaN,200.00,2018-12-06
1,10001,300 ACORN ST,ALBANY,GA,216323,NaN,NaN,NaN,NaN,NaN,NaN,40.00,2018-12-11
2,10001,300 ACORN ST,ALBANY,GA,216323,NaN,NaN,CUTO,NaN,NaN,NaN,30.00,2018-12-16
3,10002,212 ACORN ST,ALBANY,GA,10002,DELC,100.0,216,650.0,32.0,KWH,132.48,2018-10-09
4,10002,212 ACORN ST,ALBANY,GA,10002,NaN,150.0,NaN,NaN,NaN,NaN,22.49,2018-10-09

In [6]:
sorted_oct = df.sort_values('Premise Address')

In [7]:
df_utility.head()

,ChargeID,ChargeID.1,ChargeID.1.1,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
0,0,0,0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012,1,9,27944
1,1,1,1,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012,1,9,27944
2,2,2,2,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012,1,9,27944
3,3,3,3,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012,1,9,27944
4,4,4,4,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012,1,9,27944

In [8]:
sorted_utility = df_utility.sort_values(['Premise Address', 'Year', 'Month'])

In [9]:
sorted_utility.head(1000)

          ChargeID  ChargeID.1  ChargeID.1.1  Premise  \
4303731    4303731     4303731       4303731    82900
4490188    4490188     4490188       4490188    82900
4677761    4677761     4677761       4677761    82900
4867239    4867239     4867239       4867239    82900
5056518    5056518     5056518       5056518    82900
5246172    5246172     5246172       5246172    82900
5434527    5434527     5434527       5434527    82900
5619773    5619773     5619773       5619773    82900
5802928    5802928     5802928       5802928    82900
5988918    5988918     5988918       5988918    82900
6176327    6176327     6176327       6176327    82900
6362885    6362885     6362885       6362885    82900
6548045    6548045     6548045       6548045    82900
6733875    6733875     6733875       6733875    82900
6926821    6926821     6926821       6926821    82900
7113720    7113720     7113720       7113720    82900
7301962    7301962     7301962       7301962    82900
7487672    7487672     7487672       7487672    82900
7671846    7671846     7671846       7671846    82900
7855943    7855943     7855943       7855943    82900
8043159    8043159     8043159       8043159    82900
8229947    8229947     8229947       8229947    82900
8414826    8414826     8414826       8414826    82900
8600247    8600247     8600247       8600247  82900.0
8785494    8785494     8785494       8785494    82900
8968331    8968331     8968331       8968331    82900
9148713    9148713     9148713       9148713    82900
9331742    9331742     9331742       9331742    82900
9512796    9512796     9512796       9512796    82900
9693671    9693671     9693671       9693671    82900
9874554    9874554     9874554       9874554    82900
10042934  10042934    10042934      10042934    82900
10217706  10217706    10217706      10217706    82900
10401585  10401585    10401585      10401585    82900
10582745  10582745    10582745      10582745    82900
10765651  10765651    10765651      10765651  82900.0
10948195  10948195    10948195      10948195    82900
11127997  11127997    11127997      11127997    82900
11313372  11313372    11313372      11313372    82900
11495943  11495943    11495943      11495943    82900
11677950  11677950    11677950      11677950    82900
11859591  11859591    11859591      11859591    82900
12040295  12040295    12040295      12040295    82900
12224805  12224805    12224805      12224805    82900
12406455  12406455    12406455      12406455    82900
12588950  12588950    12588950      12588950    82900
12770651  12770651    12770651      12770651    82900
12951764  12951764    12951764      12951764  82900.0
13134120  13134120    13134120      13134120    82900
13316772  13316772    13316772      13316772    82900
13500475  13500475    13500475      13500475    82900
13682527  13682527    13682527      13682527    82900
14192143  14192143    14192143      14192143    82900
14192144  14192144    14192144      14192144    82900
14192145  14192145    14192145      14192145    82900
14376548  14376548    14376548      14376548    82900
14454860  14454860    14454860      14454860    82900
14741434  14741434    14741434      14741434    82900
4490430    4490430     4490430       4490430    83191
4678008    4678008     4678008       4678008    83191
4867485    4867485     4867485       4867485    83191
5056776    5056776     5056776       5056776    83191
5246420    5246420     5246420       5246420    83191
5434765    5434765     5434765       5434765    83191
5619989    5619989     5619989       5619989    83191
5803145    5803145     5803145       5803145    83191
5989134    5989134     5989134       5989134    83191
6176559    6176559     6176559       6176559    83191
6363093    6363093     6363093       6363093    83191
6548251    6548251     6548251       6548251    83191
6734111    6734111     6734111       6734111    83191
6927045    6927045     6927045       6927045    83191
7113962    7113962     7113962       7113962    83191
7302165    7302165     7302165       7302165    83191
7487874    7487874     7487874       7487874    83191
7672048    7672048     7672048       7672048    83191
7856164    7856164     7856164       7856164    83191
8043374    8043374     8043374       8043374    83191
8230174    8230174     8230174       8230174    83191
8415033    8415033     8415033       8415033    83191
8600456    8600456     8600456       8600456  83191.0
8785723    8785723     8785723       8785723    83191
8968540    8968540     8968540       8968540    83191
9148919    9148919     9148919       9148919    83191
9331947    9331947     9331947       9331947    83191
9512989    9512989     9512989       9512989    83191
9693870    9693870     9693870       9693870    83191
9874753    9874753     9874753       9874753    83191
10043133  10043133    10043133      10043133    83191
10217897  10217897    10217897      10217897    83191
10401778  10401778    10401778      10401778    83191
10582949  10582949    10582949      10582949    83191
10765851  10765851    10765851      10765851  83191.0
10948399  10948399    10948399      10948399    83191
11128187  11128187    11128187      11128187    83191
11313570  11313570    11313570      11313570    83191
11496144  11496144    11496144      11496144    83191
11678131  11678131    11678131      11678131    83191
11859784  11859784    11859784      11859784    83191
12040485  12040485    12040485      12040485    83191
12225011  12225011    12225011      12225011    83191
12406653  12406653    12406653      12406653    83191
12589135  12589135    12589135      12589135    83191
12770835  12770835    12770835      12770835    83191
12951946  12951946    12951946      12951946  83191.0
13134301  13134301    13134301      13134301    83191
13316958  13316958    13316958      13316958    83191
13500655  13500655    13500655      13500655    83191
13682709  13682709    13682709      13682709    83191
14192672  14192672    14192672      14192672    83191
14192673  14192673    14192673      14192673    83191
14192674  14192674    14192674      14192674    83191
14376727  14376727    14376727      14376727    83191
14454992  14454992    14454992      14454992    83191
14741597  14741597    14741597      14741597    83191
4303691    4303691     4303691       4303691    82857
4490149    4490149     4490149       4490149    82857
4677722    4677722     4677722       4677722    82857
4867199    4867199     4867199       4867199    82857
5056475    5056475     5056475       5056475    82857
5246130    5246130     5246130       5246130    82857
5434488    5434488     5434488       5434488    82857
5619735    5619735     5619735       5619735    82857
5802888    5802888     5802888       5802888    82857
5988874    5988874     5988874       5988874    82857
6176282    6176282     6176282       6176282    82857
6362839    6362839     6362839       6362839    82857
6547999    6547999     6547999       6547999    82857
6733828    6733828     6733828       6733828    82857
6926769    6926769     6926769       6926769    82857
7113673    7113673     7113673       7113673    82857
7301915    7301915     7301915       7301915    82857
7487620    7487620     7487620       7487620    82857
7671807    7671807     7671807       7671807    82857
7855903    7855903     7855903       7855903    82857
8043116    8043116     8043116       8043116    82857
8229901    8229901     8229901       8229901    82857
8414780    8414780     8414780       8414780    82857
8600199    8600199     8600199       8600199  82857.0
8785439    8785439     8785439       8785439    82857
8968280    8968280     8968280       8968280    82857
9148673    9148673     9148673       9148673    82857
9331699    9331699     9331699       9331699    82857
9512751    9512751     9512751       9512751    82857
9693624    9693624     9693624       9693624    82857
9874505    9874505     9874505       9874505    82857
10042884  10042884    10042884      10042884    82857
10217657  10217657    10217657      10217657    82857
10401535  10401535    10401535      10401535    82857
10582690  10582690    10582690      10582690    82857
10765605  10765605    10765605      10765605  82857.0
10948147  10948147    10948147      10948147    82857
11127950  11127950    11127950      11127950    82857
11313326  11313326    11313326      11313326    82857
11495901  11495901    11495901      11495901    82857
11677906  11677906    11677906      11677906    82857
11859545  11859545    11859545      11859545    82857
12040248  12040248    12040248      12040248    82857
12224751  12224751    12224751      12224751    82857
12406408  12406408    12406408      12406408    82857
12588903  12588903    12588903      12588903    82857
12770604  12770604    12770604      12770604    82857
12951718  12951718    12951718      12951718  82857.0
13134075  13134075    13134075      13134075    82857
13316725  13316725    13316725      13316725    82857
13500427  13500427    13500427      13500427    82857
13682484  13682484    13682484      13682484    82857
14192020  14192020    14192020      14192020    82857
14192021  14192021    14192021      14192021    82857
14192022  14192022    14192022      14192022    82857
14376508  14376508    14376508      14376508    82857
14454828  14454828    14454828      14454828    82857
14741392  14741392    14741392      14741392    82857
4303651    4303651     4303651       4303651    82810
4304140    4304140     4304140       4304140    83358
4490120    4490120     4490120       4490120    82810
4490591    4490591     4490591       4490591    83358
4677692    4677692     4677692       4677692    82810
4678147    4678147     4678147       4678147    83358
4867169    4867169     4867169       4867169    82810
4867630    4867630     4867630       4867630    83358
5056444    5056444     5056444       5056444    82810
5056916    5056916     5056916       5056916    83358
5246097    5246097     5246097       5246097    82810
5246557    5246557     5246557       5246557    83358
5434451    5434451     5434451       5434451    82810
5434894    5434894     5434894       5434894    83358
5619696    5619696     5619696       5619696    82810
5620117    5620117     5620117       5620117    83358
5802852    5802852     5802852       5802852    82810
5803282    5803282     5803282       5803282    83358
5988837    5988837     5988837       5988837    82810
5989275    5989275     5989275       5989275    83358
6176244    6176244     6176244       6176244    82810
6176708    6176708     6176708       6176708    83358
6362801    6362801     6362801       6362801    82810
6363229    6363229     6363229       6363229    83358
6547963    6547963     6547963       6547963    82810
6548380    6548380     6548380       6548380    83358
6733788    6733788     6733788       6733788    82810
6734249    6734249     6734249       6734249    83358
6926729    6926729     6926729       6926729    82810
6927179    6927179     6927179       6927179    83358
7113632    7113632     7113632       7113632    82810
7114098    7114098     7114098       7114098    83358
7301876    7301876     7301876       7301876    82810
7302295    7302295     7302295       7302295    83358
7487572    7487572     7487572       7487572    82810
7488001    7488001     7488001       7488001    83358
7671777    7671777     7671777       7671777    82810
7672161    7672161     7672161       7672161    83358
7855863    7855863     7855863       7855863    82810
7856283    7856283     7856283       7856283    83358
8043087    8043087     8043087       8043087    82810
8043488    8043488     8043488       8043488    83358
8229871    8229871     8229871       8229871    82810
8230290    8230290     8230290       8230290    83358
8414750    8414750     8414750       8414750    82810
8415146    8415146     8415146       8415146    83358
8600170    8600170     8600170       8600170  82810.0
8600573    8600573     8600573       8600573  83358.0
8785411    8785411     8785411       8785411    82810
8785838    8785838     8785838       8785838    83358
8968246    8968246     8968246       8968246    82810
8968659    8968659     8968659       8968659    83358
9148649    9148649     9148649       9148649    82810
9149046    9149046     9149046       9149046    83358
9331670    9331670     9331670       9331670    82810
9332071    9332071     9332071       9332071    83358
9512724    9512724     9512724       9512724    82810
9513095    9513095     9513095       9513095    83358
9693595    9693595     9693595       9693595    82810
9693977    9693977     9693977       9693977    83358
9874476    9874476     9874476       9874476    82810
9874860    9874860     9874860       9874860    83358
10042851  10042851    10042851      10042851    82810
10043236  10043236    10043236      10043236    83358
10217630  10217630    10217630      10217630    82810
10217998  10217998    10217998      10217998    83358
10401503  10401503    10401503      10401503    82810
10401878  10401878    10401878      10401878    83358
10582656  10582656    10582656      10582656    82810
10583055  10583055    10583055      10583055    83358
10765571  10765571    10765571      10765571  82810.0
10765959  10765959    10765959      10765959  83358.0
10948117  10948117    10948117      10948117    82810
10948516  10948516    10948516      10948516    83358
11127921  11127921    11127921      11127921    82810
11128296  11128296    11128296      11128296    83358
11313281  11313281    11313281      11313281    82810
11313671  11313671    11313671      11313671    83358
11495872  11495872    11495872      11495872    82810
11496257  11496257    11496257      11496257    83358
11677874  11677874    11677874      11677874    82810
11678242  11678242    11678242      11678242    83358
11859514  11859514    11859514      11859514    82810
11859882  11859882    11859882      11859882    83358
12040218  12040218    12040218      12040218    82810
12040582  12040582    12040582      12040582    83358
12224727  12224727    12224727      12224727    82810
12225115  12225115    12225115      12225115    83358
12406382  12406382    12406382      12406382    82810
12406755  12406755    12406755      12406755    83358
12588876  12588876    12588876      12588876    82810
12589234  12589234    12589234      12589234    83358
12770576  12770576    12770576      12770576    82810
12770939  12770939    12770939      12770939    83358
12951690  12951690    12951690      12951690  82810.0
12952048  12952048    12952048      12952048  83358.0
13134045  13134045    13134045      13134045    82810
13134407  13134407    13134407      13134407    83358
13316688  13316688    13316688      13316688    82810
13317054  13317054    13317054      13317054    83358
13500398  13500398    13500398      13500398    82810
13500750  13500750    13500750      13500750    83358
13682452  13682452    13682452      13682452    82810
13682807  13682807    13682807      13682807    83358
14191922  14191922    14191922      14191922    82810
14191923  14191923    14191923      14191923    82810
14191924  14191924    14191924      14191924    82810
14192969  14192969    14192969      14192969    83358
14192970  14192970    14192970      14192970    83358
14192971  14192971    14192971      14192971    83358
14376475  14376475    14376475      14376475    82810
14376824  14376824    14376824      14376824    83358
14454801  14454801    14454801      14454801    82810
14455052  14455052    14455052      14455052    83358
14741354  14741354    14741354      14741354    82810
14741692  14741692    14741692      14741692    83358
4303772    4303772     4303772       4303772    82943
4490229    4490229     4490229       4490229    82943
4677806    4677806     4677806       4677806    82943
4867281    4867281     4867281       4867281    82943
5056563    5056563     5056563       5056563    82943
5246216    5246216     5246216       5246216    82943
5434577    5434577     5434577       5434577    82943
5619807    5619807     5619807       5619807    82943
5802964    5802964     5802964       5802964    82943
5988953    5988953     5988953       5988953    82943
6176368    6176368     6176368       6176368    82943
6362912    6362912     6362912       6362912    82943
6548077    6548077     6548077       6548077    82943
6733909    6733909     6733909       6733909    82943
6926854    6926854     6926854       6926854    82943
7113754    7113754     7113754       7113754    82943
7301996    7301996     7301996       7301996    82943
7487705    7487705     7487705       7487705    82943
7671878    7671878     7671878       7671878    82943
7855976    7855976     7855976       7855976    82943
8043194    8043194     8043194       8043194    82943
8229982    8229982     8229982       8229982    82943
8414860    8414860     8414860       8414860    82943
8600281    8600281     8600281       8600281  82943.0
8785527    8785527     8785527       8785527    82943
8968364    8968364     8968364       8968364    82943
9148747    9148747     9148747       9148747    82943
9331775    9331775     9331775       9331775    82943
9512827    9512827     9512827       9512827    82943
9693705    9693705     9693705       9693705    82943
9874588    9874588     9874588       9874588    82943
10042967  10042967    10042967      10042967    82943
10217740  10217740    10217740      10217740    82943
10401617  10401617    10401617      10401617    82943
10582778  10582778    10582778      10582778    82943
10765685  10765685    10765685      10765685  82943.0
10948228  10948228    10948228      10948228    82943
11128029  11128029    11128029      11128029    82943
11313405  11313405    11313405      11313405    82943
11495975  11495975    11495975      11495975    82943
11677982  11677982    11677982      11677982    82943
11859623  11859623    11859623      11859623    82943
12040326  12040326    12040326      12040326    82943
12224837  12224837    12224837      12224837    82943
12406487  12406487    12406487      12406487    82943
12588980  12588980    12588980      12588980    82943
12770682  12770682    12770682      12770682    82943
12951794  12951794    12951794      12951794  82943.0
13134150  13134150    13134150      13134150    82943
13316803  13316803    13316803      13316803    82943
13500505  13500505    13500505      13500505    82943
13682557  13682557    13682557      13682557    82943
14192233  14192233    14192233      14192233    82943
14192234  14192234    14192234      14192234    82943
14192235  14192235    14192235      14192235    82943
14376578  14376578    14376578      14376578    82943
14454882  14454882    14454882      14454882    82943
14741463  14741463    14741463      14741463    82943
4304079    4304079     4304079       4304079    83282
4490518    4490518     4490518       4490518    83282
4678083    4678083     4678083       4678083    83282
4867565    4867565     4867565       4867565    83282
5056846    5056846     5056846       5056846    83282
5246496    5246496     5246496       5246496    83282
5434832    5434832     5434832       5434832    83282
5620058    5620058     5620058       5620058    83282
5803221    5803221     5803221       5803221    83282
5989214    5989214     5989214       5989214    83282
6176646    6176646     6176646       6176646    83282
6363168    6363168     6363168       6363168    83282
6548327    6548327     6548327       6548327    83282
6734191    6734191     6734191       6734191    83282
6927123    6927123     6927123       6927123    83282
7114044    7114044     7114044       7114044    83282
7302248    7302248     7302248       7302248    83282
7487949    7487949     7487949       7487949    83282
7672110    7672110     7672110       7672110    83282
7856230    7856230     7856230       7856230    83282
8043436    8043436     8043436       8043436    83282
8230236    8230236     8230236       8230236    83282

In [10]:
sorted_oct.head(1000)

,Premise,Premise Address,City,State,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date
399923,45825,8TH AVE,NaN,NaN,45825,CWTR,300.0,230,35.000,31.0,TGAL,74.17,2018-10-29
399924,45825,8TH AVE,NaN,NaN,45825,CWTR,300.0,230,38.000,31.0,TGAL,79.75,2018-11-29
399925,45825,8TH AVE,NaN,NaN,45825,CWTR,300.0,230,42.000,31.0,TGAL,87.19,2018-12-28
516444,9246,CASON ST,NaN,NaN,9246,CELC,101.0,210W,183.000,31.0,KWH,45.61,2018-12-06
516443,9246,CASON ST,NaN,NaN,9246,CELC,101.0,210W,146.000,32.0,KWH,40.11,2018-11-07
516442,9246,CASON ST,NaN,NaN,9246,CELC,101.0,210W,113.000,31.0,KWH,37.82,2018-10-09
516441,9245,CASON ST,NaN,NaN,9245,CELC,101.0,210W,32.000,31.0,KWH,23.20,2018-12-06
516440,9245,CASON ST,NaN,NaN,9245,CELC,101.0,210W,60.000,32.0,KWH,27.34,2018-11-07
516439,9245,CASON ST,NaN,NaN,9245,CELC,101.0,210W,110.000,31.0,KWH,37.31,2018-10-09
38437,14655,CLARK AVE,ALBANY,GA,14655,DELC,100.0,212W,1422.000,32.0,KWH,214.48,2018-10-17
38446,14657,CLARK AVE,ALBANY,GA,14657,CELC,101.0,210W,79.000,33.0,KWH,30.16,2018-10-17
38445,14656,CLARK AVE,ALBANY,GA,14656,DELC,100.0,212W,1986.000,33.0,KWH,292.70,2018-12-10
38444,14656,CLARK AVE,ALBANY,GA,14656,DELC,100.0,212W,1043.000,31.0,KWH,161.90,2018-11-09
38443,14656,CLARK AVE,ALBANY,GA,14656,DELC,100.0,212W,112.000,32.0,KWH,32.78,2018-10-17
38442,14655,CLARK AVE,ALBANY,GA,14655,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-12-10
38441,14655,CLARK AVE,ALBANY,GA,14655,DELC,100.0,212W,1988.000,33.0,KWH,292.97,2018-12-10
38447,14657,CLARK AVE,ALBANY,GA,14657,CELC,101.0,210W,65.000,30.0,KWH,28.10,2018-11-09
38439,14655,CLARK AVE,ALBANY,GA,14655,DELC,100.0,212W,1005.000,31.0,KWH,156.63,2018-11-09
38438,14655,CLARK AVE,ALBANY,GA,14655,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-17
38448,14657,CLARK AVE,ALBANY,GA,14657,CELC,101.0,210W,91.000,33.0,KWH,31.95,2018-12-10
38440,14655,CLARK AVE,ALBANY,GA,14655,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-09
120694,22947,CORN,ALBANY,GA,22947,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-10-18
120696,22947,CORN,ALBANY,GA,22947,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-12-13
120695,22947,CORN,ALBANY,GA,22947,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-11-14
516424,9240,DARROW JCT,NaN,NaN,62751,DELC,100.0,212,198.000,31.0,KWH,55.49,2018-10-09
516425,9240,DARROW JCT,NaN,NaN,62751,DELC,100.0,212,164.000,32.0,KWH,51.31,2018-11-07
516426,9240,DARROW JCT,NaN,NaN,62751,DELC,100.0,212,206.000,31.0,KWH,56.22,2018-12-06
77691,18430,DUNES AVE,ALBANY,GA,234417,NaN,150.0,NaN,NaN,NaN,NaN,89.99,2018-10-17
77692,18430,DUNES AVE,ALBANY,GA,234417,NaN,150.0,NaN,NaN,NaN,NaN,89.99,2018-11-12
77695,18430,DUNES AVE,ALBANY,GA,234417,NaN,NaN,CUTO,NaN,NaN,NaN,30.00,2018-12-21
77693,18430,DUNES AVE,ALBANY,GA,234417,NaN,150.0,NaN,NaN,NaN,NaN,89.99,2018-12-11
77694,18430,DUNES AVE,ALBANY,GA,234417,NaN,NaN,LATE,NaN,NaN,NaN,15.00,2018-12-16
138408,24474,EDGERLY AVE,ALBANY,GA,24474,DELC,100.0,212W,190.000,30.0,KWH,43.60,2018-12-14
138407,24474,EDGERLY AVE,ALBANY,GA,24474,DELC,100.0,212W,122.000,30.0,KWH,34.17,2018-11-15
138406,24474,EDGERLY AVE,ALBANY,GA,24474,DELC,100.0,212W,159.000,32.0,KWH,39.29,2018-10-19
95722,2023,EVERGREEN DR,ALBANY,GA,2023,DELC,100.0,212W,290.000,33.0,KWH,63.71,2018-10-03
95724,2023,EVERGREEN DR,ALBANY,GA,2023,DELC,100.0,212W,779.000,34.0,KWH,125.28,2018-12-03
95723,2023,EVERGREEN DR,ALBANY,GA,2023,DELC,100.0,212W,252.000,29.0,KWH,52.19,2018-11-01
171799,27704,FIRESTONE DR,NaN,NaN,27704,DELC,100.0,212W,409.000,32.0,KWH,73.97,2018-12-17
171800,27704,FIRESTONE DR,NaN,NaN,27704,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-17
171801,27704,FIRESTONE DR,NaN,NaN,27704,CWTR,300.0,230,0.000,32.0,TGAL,11.85,2018-12-17
171797,27704,FIRESTONE DR,NaN,NaN,27704,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-16
171793,27704,FIRESTONE DR,NaN,NaN,27704,DELC,100.0,212W,721.000,33.0,KWH,117.25,2018-10-19
171796,27704,FIRESTONE DR,NaN,NaN,27704,DELC,100.0,212W,129.000,30.0,KWH,35.13,2018-11-16
171794,27704,FIRESTONE DR,NaN,NaN,27704,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-19
171795,27704,FIRESTONE DR,NaN,NaN,27704,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-19
171798,27704,FIRESTONE DR,NaN,NaN,27704,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-16
183838,28629,GILLIONVILLE RD,NaN,NaN,28629,DELC,100.0,212,8400.000,33.0,KWH,890.96,2018-10-22
183839,28629,GILLIONVILLE RD,NaN,NaN,28629,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-22
183840,28629,GILLIONVILLE RD,NaN,NaN,28629,DELC,100.0,212,7520.000,30.0,KWH,825.78,2018-11-19
183842,28629,GILLIONVILLE RD,NaN,NaN,28629,DELC,100.0,212,16000.000,32.0,KWH,1407.52,2018-12-18
183841,28629,GILLIONVILLE RD,NaN,NaN,28629,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-19
183843,28629,GILLIONVILLE RD,NaN,NaN,28629,CWTR,300.0,230,0.000,32.0,TGAL,11.85,2018-12-18
8800,11260,GROVE PARK,ALBANY,GA,11260,NaN,150.0,NaN,NaN,NaN,NaN,16.82,2018-12-07
8799,11260,GROVE PARK,ALBANY,GA,11260,NaN,150.0,NaN,NaN,NaN,NaN,16.82,2018-11-08
8798,11260,GROVE PARK,ALBANY,GA,11260,NaN,150.0,NaN,NaN,NaN,NaN,16.82,2018-10-15
329052,39841,INDIAN CREEK DR,NaN,NaN,39841,DELC,100.0,212,8283.000,31.0,KWH,953.25,2018-10-25
329054,39841,INDIAN CREEK DR,NaN,NaN,39841,DELC,100.0,212,10578.000,32.0,KWH,1123.23,2018-12-21
330974,39969,INDIAN CREEK DR,NaN,NaN,39969,DELC,100.0,212,2958.000,35.0,KWH,402.37,2018-10-25
330975,39969,INDIAN CREEK DR,NaN,NaN,39969,DELC,100.0,212,1138.000,28.0,KWH,193.06,2018-11-27
330976,39969,INDIAN CREEK DR,NaN,NaN,39969,DELC,100.0,212,322.000,32.0,KWH,99.24,2018-12-28
329053,39841,INDIAN CREEK DR,NaN,NaN,39841,DELC,100.0,212,3391.000,32.0,KWH,481.98,2018-11-26
279268,35630,LAKEVIEW,NaN,NaN,35630,CWTR,300.0,230,0.000,28.0,TGAL,11.85,2018-11-21
279269,35630,LAKEVIEW,NaN,NaN,35630,DELC,100.0,212W,5560.000,32.0,KWH,788.41,2018-12-20
279267,35630,LAKEVIEW,NaN,NaN,35630,DELC,100.0,212W,2320.000,28.0,KWH,339.02,2018-11-21
279266,35630,LAKEVIEW,NaN,NaN,35630,CWTR,300.0,230,0.000,35.0,TGAL,11.85,2018-10-23
279265,35630,LAKEVIEW,NaN,NaN,35630,DELC,100.0,212W,2160.000,35.0,KWH,316.83,2018-10-23
279270,35630,LAKEVIEW,NaN,NaN,35630,CWTR,300.0,230,0.000,32.0,TGAL,11.85,2018-12-20
77395,18398,MITCHELL AVE,ALBANY,GA,18398,DELC,100.0,212W,214.000,30.0,KWH,46.92,2018-11-12
77393,18398,MITCHELL AVE,ALBANY,GA,18398,DELC,100.0,212W,291.000,34.0,KWH,57.60,2018-10-17
77394,18398,MITCHELL AVE,ALBANY,GA,18398,CWTR,300.0,230,0.000,34.0,TGAL,11.85,2018-10-17
77398,18398,MITCHELL AVE,ALBANY,GA,18398,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-12-11
77397,18398,MITCHELL AVE,ALBANY,GA,18398,DELC,100.0,212W,777.000,33.0,KWH,125.01,2018-12-11
77396,18398,MITCHELL AVE,ALBANY,GA,18398,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-12
86831,19256,MOBILE AVE,ALBANY,GA,19256,DELC,100.0,212,9760.000,32.0,KWH,1150.06,2018-11-12
86832,19256,MOBILE AVE,ALBANY,GA,19256,DELC,100.0,212,12040.000,30.0,KWH,1318.93,2018-12-11
86830,19256,MOBILE AVE,ALBANY,GA,19256,DELC,100.0,212,3520.000,34.0,KWH,514.99,2018-10-17
5621,10670,MOCK RD,ALBANY,GA,10670,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-09
5624,10670,MOCK RD,ALBANY,GA,10670,DELC,100.0,212W,358.000,31.0,KWH,66.89,2018-12-06
5623,10670,MOCK RD,ALBANY,GA,10670,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-07
5622,10670,MOCK RD,ALBANY,GA,10670,DELC,100.0,212W,335.000,29.0,KWH,63.71,2018-11-07
5620,10670,MOCK RD,ALBANY,GA,10670,DELC,100.0,212W,1313.000,33.0,KWH,227.64,2018-10-09
5625,10670,MOCK RD,ALBANY,GA,10670,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-06
98284,20488,MORNINGSIDE DR,ALBANY,GA,20488,DELC,100.0,212W,177.000,34.0,KWH,41.79,2018-10-18
98285,20488,MORNINGSIDE DR,ALBANY,GA,20488,DELC,100.0,212W,355.000,32.0,KWH,66.48,2018-11-13
98286,20488,MORNINGSIDE DR,ALBANY,GA,20488,DELC,100.0,212W,941.000,31.0,KWH,147.76,2018-12-12
23680,1283,NEWTON RD,ALBANY,GA,1283,DELC,100.0,212,13520.000,33.0,KWH,1757.87,2018-12-03
23456,1279,NEWTON RD,ALBANY,GA,24016,GWTR,300.0,433,0.000,31.0,TGAL,11.85,2018-10-03
23676,1283,NEWTON RD,ALBANY,GA,1283,GGAS,200.0,220,4.000,30.0,CCF,12.28,2018-10-03
23677,1283,NEWTON RD,ALBANY,GA,1283,DELC,100.0,212,24320.000,33.0,KWH,2674.99,2018-11-01
23678,1283,NEWTON RD,ALBANY,GA,1283,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-11-01
23679,1283,NEWTON RD,ALBANY,GA,1283,GGAS,200.0,220,0.000,33.0,CCF,7.82,2018-11-01
23675,1283,NEWTON RD,ALBANY,GA,1283,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-10-03
23457,1279,NEWTON RD,ALBANY,GA,24016,CSWR,400.0,452,0.000,31.0,NONE,10.12,2018-10-03
23674,1283,NEWTON RD,ALBANY,GA,1283,DELC,100.0,212,29760.000,30.0,KWH,3077.90,2018-10-03
23459,1279,NEWTON RD,ALBANY,GA,24016,CSWR,400.0,452,0.000,33.0,NONE,10.12,2018-11-01
23460,1279,NEWTON RD,ALBANY,GA,24016,GWTR,300.0,433,0.000,33.0,TGAL,11.85,2018-12-03
23461,1279,NEWTON RD,ALBANY,GA,24016,CSWR,400.0,452,0.000,33.0,NONE,10.12,2018-12-03
23682,1283,NEWTON RD,ALBANY,GA,1283,GGAS,200.0,220,453.000,33.0,CCF,597.39,2018-12-03
23681,1283,NEWTON RD,ALBANY,GA,1283,NaN,150.0,NaN,NaN,NaN,NaN,50.46,2018-12-03
23458,1279,NEWTON RD,ALBANY,GA,24016,GWTR,300.0,433,0.000,33.0,TGAL,11.85,2018-11-01
125616,2335,OAKRIDGE,ALBANY,GA,194985,DELC,100.0,212W,0.000,32.0,KWH,18.45,2018-11-01
125615,2335,OAKRIDGE,ALBANY,GA,194985,DELC,100.0,212W,0.000,30.0,KWH,18.45,2018-10-03
125617,2335,OAKRIDGE,ALBANY,GA,194985,DELC,100.0,212W,1.000,34.0,KWH,18.60,2018-12-03
121381,2300,OAKRIDGE DR,ALBANY,GA,2300,RWTR,300.0,130,0.000,32.0,TGAL,11.85,2018-11-01
117573,2273,OAKRIDGE DR,ALBANY,GA,2273,DELC,100.0,212,13760.000,30.0,KWH,1591.86,2018-10-03
121382,2300,OAKRIDGE DR,ALBANY,GA,2300,RWTR,300.0,130,0.000,34.0,TGAL,11.85,2018-12-03
121380,2300,OAKRIDGE DR,ALBANY,GA,2300,RWTR,300.0,130,0.000,30.0,TGAL,11.85,2018-10-03
121529,2301,OAKRIDGE DR,ALBANY,GA,2301,DELC,100.0,212,14438.000,30.0,KWH,1289.18,2018-10-03
122653,2313,OAKRIDGE DR,ALBANY,GA,2313,DELC,100.0,212,23120.000,31.0,KWH,2411.21,2018-10-03
121531,2301,OAKRIDGE DR,ALBANY,GA,2301,DELC,100.0,212,0.000,34.0,KWH,74.59,2018-12-03
124878,2329,OAKRIDGE DR,ALBANY,GA,194985,DELC,100.0,212W,1.000,30.0,KWH,18.62,2018-10-03
122654,2313,OAKRIDGE DR,ALBANY,GA,2313,DELC,100.0,212,14200.000,32.0,KWH,1750.57,2018-11-01
124879,2329,OAKRIDGE DR,ALBANY,GA,194985,DELC,100.0,212W,0.000,32.0,KWH,18.45,2018-11-01
124880,2329,OAKRIDGE DR,ALBANY,GA,194985,DELC,100.0,212W,0.000,34.0,KWH,18.45,2018-12-03
122655,2313,OAKRIDGE DR,ALBANY,GA,2313,DELC,100.0,212,24880.000,34.0,KWH,2541.57,2018-12-03
117575,2273,OAKRIDGE DR,ALBANY,GA,2273,DELC,100.0,212,13520.000,33.0,KWH,1574.09,2018-12-03
117574,2273,OAKRIDGE DR,ALBANY,GA,2273,DELC,100.0,212,10200.000,33.0,KWH,1313.46,2018-11-01
121530,2301,OAKRIDGE DR,ALBANY,GA,2301,DELC,100.0,212,6556.000,32.0,KWH,741.59,2018-11-01
503081,83138,OKELLY LANE,NaN,NaN,208245,NaN,700.0,NaN,NaN,NaN,NaN,5.23,2018-12-17
503079,83138,OKELLY LANE,NaN,NaN,208245,NaN,700.0,NaN,NaN,NaN,NaN,5.23,2018-10-19
503080,83138,OKELLY LANE,NaN,NaN,208245,NaN,700.0,NaN,NaN,NaN,NaN,5.23,2018-11-16
502820,82977,OLD DAWSON RD,NaN,NaN,48062,NaN,700.0,NaN,NaN,NaN,NaN,9.50,2018-10-24
502821,82977,OLD DAWSON RD,NaN,NaN,48062,NaN,700.0,NaN,NaN,NaN,NaN,9.50,2018-11-26
502822,82977,OLD DAWSON RD,NaN,NaN,48062,NaN,700.0,NaN,NaN,NaN,NaN,9.50,2018-12-21
405395,46171,PALMYRA RD,NaN,NaN,46171,CWTR,300.0,230,0.000,31.0,TGAL,11.85,2018-10-29
407316,46315,PALMYRA RD,NaN,NaN,46315,DELC,100.0,212W,1007.000,30.0,KWH,156.92,2018-12-28
407315,46315,PALMYRA RD,NaN,NaN,46315,DELC,100.0,212W,967.000,31.0,KWH,151.37,2018-11-29
405397,46171,PALMYRA RD,NaN,NaN,46171,CWTR,300.0,230,0.000,31.0,TGAL,11.85,2018-12-28
405396,46171,PALMYRA RD,NaN,NaN,46171,CWTR,300.0,230,0.000,32.0,TGAL,11.85,2018-11-29
407314,46315,PALMYRA RD,NaN,NaN,46315,DELC,100.0,212W,995.000,31.0,KWH,155.25,2018-10-29
5279,10642,PEARCE AVE,ALBANY,GA,10642,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-09
5281,10642,PEARCE AVE,ALBANY,GA,10642,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-07
5280,10642,PEARCE AVE,ALBANY,GA,10642,DELC,100.0,212W,1440.000,29.0,KWH,216.97,2018-11-07
5283,10642,PEARCE AVE,ALBANY,GA,10642,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-06
5282,10642,PEARCE AVE,ALBANY,GA,10642,DELC,100.0,212W,3120.000,34.0,KWH,449.98,2018-12-06
5278,10642,PEARCE AVE,ALBANY,GA,10642,DELC,100.0,212W,1160.000,33.0,KWH,203.12,2018-10-09
129380,23704,PINE AVE,ALBANY,GA,23704,DELC,100.0,210W,84.000,31.0,KWH,30.90,2018-12-14
129378,23704,PINE AVE,ALBANY,GA,23704,DELC,100.0,210W,81.000,32.0,KWH,30.48,2018-10-24
129379,23704,PINE AVE,ALBANY,GA,23704,DELC,100.0,210W,107.000,31.0,KWH,34.33,2018-11-15
90346,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-12
90348,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-12-11
90344,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-17
90222,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-11
90345,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,DELC,100.0,212W,261.000,32.0,KWH,53.44,2018-11-12
90347,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,DELC,100.0,212W,427.000,31.0,KWH,76.47,2018-12-11
90220,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-12
90219,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,DELC,100.0,212,31040.000,32.0,KWH,3986.12,2018-11-12
90221,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,DELC,100.0,212,41120.000,31.0,KWH,4945.55,2018-12-11
90343,19591,RADIUM SPRINGS RD,ALBANY,GA,19591,DELC,100.0,212W,230.000,30.0,KWH,49.15,2018-10-17
90217,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,DELC,100.0,212,43280.000,30.0,KWH,5105.53,2018-10-17
90218,19571,RADIUM SPRINGS RD,ALBANY,GA,19571,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-17
75088,1797,RANDOLPH ST,ALBANY,GA,1797,DELC,100.0,212W,1329.000,33.0,KWH,201.57,2018-12-03
75087,1797,RANDOLPH ST,ALBANY,GA,1797,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-01
75086,1797,RANDOLPH ST,ALBANY,GA,1797,DELC,100.0,212W,1085.000,33.0,KWH,167.73,2018-11-01
75085,1797,RANDOLPH ST,ALBANY,GA,1797,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-03
75084,1797,RANDOLPH ST,ALBANY,GA,1797,DELC,100.0,212W,1273.000,31.0,KWH,221.23,2018-10-03
75089,1797,RANDOLPH ST,ALBANY,GA,1797,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-03
521067,9774,SUNDALE,NaN,NaN,9774,DELC,100.0,212W,240.000,31.0,KWH,50.53,2018-12-06
521066,9774,SUNDALE,NaN,NaN,9774,DELC,100.0,212W,200.000,32.0,KWH,44.98,2018-11-07
521065,9774,SUNDALE,NaN,NaN,9774,DELC,100.0,212W,200.000,31.0,KWH,49.29,2018-10-09
47405,15621,SWIFT,ALBANY,GA,15621,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-10-17
47406,15621,SWIFT,ALBANY,GA,15621,CWTR,300.0,230,0.000,34.0,TGAL,11.85,2018-10-17
47407,15621,SWIFT,ALBANY,GA,15621,DELC,100.0,212,1880.000,29.0,KWH,285.68,2018-11-09
47408,15621,SWIFT,ALBANY,GA,15621,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-11-09
47404,15621,SWIFT,ALBANY,GA,15621,DELC,100.0,212,3280.000,34.0,KWH,445.33,2018-10-17
47409,15621,SWIFT,ALBANY,GA,15621,CWTR,300.0,230,0.000,29.0,TGAL,11.85,2018-11-09
47410,15621,SWIFT,ALBANY,GA,15621,DELC,100.0,212,3720.000,34.0,KWH,497.28,2018-12-10
47411,15621,SWIFT,ALBANY,GA,15621,NaN,150.0,NaN,NaN,NaN,NaN,10.51,2018-12-10
47412,15621,SWIFT,ALBANY,GA,15621,CWTR,300.0,230,0.000,34.0,TGAL,11.85,2018-12-10
518145,9547,THORNTON,NaN,NaN,9547,CWTR,300.0,231,6.000,32.0,TGAL,19.53,2018-10-09
518147,9547,THORNTON,NaN,NaN,9547,CWTR,300.0,231,6.000,31.0,TGAL,19.53,2018-11-07
518146,9547,THORNTON,NaN,NaN,9547,DELC,100.0,212W,1297.000,31.0,KWH,197.13,2018-11-07
518149,9547,THORNTON,NaN,NaN,9547,CWTR,300.0,231,7.000,32.0,TGAL,22.09,2018-12-06
518148,9547,THORNTON,NaN,NaN,9547,DELC,100.0,212W,2020.000,32.0,KWH,297.41,2018-12-06
518144,9547,THORNTON,NaN,NaN,9547,DELC,100.0,212W,1510.000,32.0,KWH,259.21,2018-10-09
38907,14737,TURNER FIELD RD,ALBANY,GA,14738,CELC,100.0,210W,156.000,30.0,KWH,41.60,2018-11-09
38906,14737,TURNER FIELD RD,ALBANY,GA,14738,CELC,100.0,210W,159.000,33.0,KWH,42.05,2018-10-17
38697,14708,TURNER FIELD RD,ALBANY,GA,14708,NaN,150.0,NaN,NaN,NaN,NaN,119.82,2018-12-10
38909,14737,TURNER FIELD RD,ALBANY,GA,14738,NaN,NaN,LATE,NaN,NaN,NaN,15.00,2018-12-13
38621,14697,TURNER FIELD RD,ALBANY,GA,14697,DELC,100.0,212,3160.000,30.0,KWH,452.09,2018-11-09
38622,14697,TURNER FIELD RD,ALBANY,GA,14697,DELC,100.0,212,4320.000,33.0,KWH,585.49,2018-12-10
38746,14713,TURNER FIELD RD,ALBANY,GA,14713,CWTR,300.0,230,9.000,33.0,TGAL,25.81,2018-10-17
38747,14713,TURNER FIELD RD,ALBANY,GA,14713,CSWR,400.0,252,9.000,33.0,NONE,39.19,2018-10-17
38748,14713,TURNER FIELD RD,ALBANY,GA,14713,CWTR,300.0,230,5.000,30.0,TGAL,16.97,2018-11-09
38912,14738,TURNER FIELD RD,ALBANY,GA,14738,CELC,101.0,210W,165.000,33.0,KWH,42.93,2018-12-10
38935,14743,TURNER FIELD RD,ALBANY,GA,14743,DELC,100.0,212W,480.000,31.0,KWH,89.69,2018-10-17
38908,14737,TURNER FIELD RD,ALBANY,GA,14738,CELC,100.0,210W,146.000,33.0,KWH,40.11,2018-12-10
38936,14743,TURNER FIELD RD,ALBANY,GA,14743,DELC,100.0,212W,400.000,31.0,KWH,77.80,2018-11-19
38623,14698,TURNER FIELD RD,ALBANY,GA,14698,NaN,150.0,NaN,NaN,NaN,NaN,73.57,2018-10-17
38624,14698,TURNER FIELD RD,ALBANY,GA,14698,NaN,150.0,NaN,NaN,NaN,NaN,73.57,2018-11-09
38625,14698,TURNER FIELD RD,ALBANY,GA,14698,NaN,150.0,NaN,NaN,NaN,NaN,73.57,2018-12-10
38749,14713,TURNER FIELD RD,ALBANY,GA,14713,CSWR,400.0,252,5.000,30.0,NONE,26.27,2018-11-09
38750,14713,TURNER FIELD RD,ALBANY,GA,14713,CWTR,300.0,230,5.000,33.0,TGAL,16.97,2018-12-10
38751,14713,TURNER FIELD RD,ALBANY,GA,14713,CSWR,400.0,252,5.000,33.0,NONE,26.27,2018-12-10
38627,14700,TURNER FIELD RD,ALBANY,GA,14700,NaN,150.0,NaN,NaN,NaN,NaN,33.64,2018-10-17
38937,14743,TURNER FIELD RD,ALBANY,GA,14743,DELC,100.0,212W,320.000,33.0,KWH,65.93,2018-12-10
38626,14700,TURNER FIELD RD,ALBANY,GA,14700,DELC,100.0,212,12360.000,32.0,KWH,1457.16,2018-10-17
38632,14700,TURNER FIELD RD,ALBANY,GA,14700,DELC,100.0,212,7000.000,31.0,KWH,939.01,2018-11-09
432067,53362,TURNER FIELD RD,NaN,NaN,59783,CELC,100.0,212W,9.000,29.0,KWH,18.49,2018-11-09
38687,14707,TURNER FIELD RD,ALBANY,GA,14707,CSWR,400.0,250,0.000,33.0,NONE,10.12,2018-10-17
38686,14707,TURNER FIELD RD,ALBANY,GA,14707,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-17
38755,14714,TURNER FIELD RD,ALBANY,GA,14714,GGAS,200.0,220,-579.000,31.0,CCF,-741.41,2018-11-09
38756,14714,TURNER FIELD RD,ALBANY,GA,14714,DELC,100.0,212W,1600.000,33.0,KWH,239.16,2018-12-10
38757,14714,TURNER FIELD RD,ALBANY,GA,14714,GGAS,200.0,220,1762.000,32.0,CCF,2256.26,2018-12-10
38640,14700,TURNER FIELD RD,ALBANY,GA,14700,CGAS,201.0,220,1102.000,33.0,CCF,1419.85,2018-12-10
38641,14700,TURNER FIELD RD,ALBANY,GA,14700,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-12-10
38945,14746,TURNER FIELD RD,ALBANY,GA,14746,NaN,NaN,LATE,NaN,NaN,NaN,15.00,2018-12-13
38688,14707,TURNER FIELD RD,ALBANY,GA,14707,CWTR,300.0,230,0.000,30.0,TGAL,11.85,2018-11-09
38944,14746,TURNER FIELD RD,ALBANY,GA,14746,DELC,100.0,212W,600.000,33.0,KWH,107.49,2018-12-10
38942,14746,TURNER FIELD RD,ALBANY,GA,14746,DELC,100.0,212W,720.000,33.0,KWH,125.29,2018-10-17
38941,14744,TURNER FIELD RD,ALBANY,GA,14744,NaN,NaN,LATE,NaN,NaN,NaN,15.00,2018-12-13
38940,14744,TURNER FIELD RD,ALBANY,GA,14744,DELC,100.0,212,4280.000,33.0,KWH,412.90,2018-12-10
38642,14700,TURNER FIELD RD,ALBANY,GA,14700,CSWR,400.0,252,0.000,33.0,NONE,10.12,2018-12-10
38643,14700,TURNER FIELD RD,ALBANY,GA,14700,NaN,500.0,NaN,NaN,NaN,NaN,127.75,2018-12-10
40747,14953,TURNER FIELD RD,ALBANY,GA,14953,NaN,150.0,NaN,NaN,NaN,NaN,285.94,2018-11-09
40746,14953,TURNER FIELD RD,ALBANY,GA,14953,NaN,150.0,NaN,NaN,NaN,NaN,285.94,2018-10-17
38758,14715,TURNER FIELD RD,ALBANY,GA,14715,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-10-17
38943,14746,TURNER FIELD RD,ALBANY,GA,14746,DELC,100.0,212W,320.000,30.0,KWH,65.93,2018-11-09
432068,53362,TURNER FIELD RD,NaN,NaN,59783,CELC,100.0,212W,13.000,34.0,KWH,19.04,2018-12-10
38938,14744,TURNER FIELD RD,ALBANY,GA,14744,DELC,100.0,212,4120.000,33.0,KWH,402.06,2018-10-17
38690,14707,TURNER FIELD RD,ALBANY,GA,14707,CWTR,300.0,230,0.000,33.0,TGAL,11.85,2018-12-10
432066,53362,TURNER FIELD RD,NaN,NaN,59783,CELC,100.0,212W,13.000,34.0,KWH,19.04,2018-10-17
38628,14700,TURNER FIELD RD,ALBANY,GA,14700,CGAS,201.0,220,33.000,32.0,CCF,53.09,2018-10-17
38629,14700,TURNER FIELD RD,ALBANY,GA,14700,CWTR,300.0,230,0.000,32.0,TGAL,11.85,2018-10-17

In [19]:
df.columns = [a.strip() for a in list(df)]

In [20]:
df.columns

Index(['Premise', 'Premise Address', 'City', 'State', 'Customer',
       'Service Type', 'Service Number', 'Service Rate', 'Consumption',
       'Days of Service', 'Unit of Measure', 'Charge Amount', 'Charge Date'],
      dtype='object')

In [21]:
df['Charge Date'].value_counts()

2018-10-22    19843
2018-10-17    18008
2018-10-19    16539
2018-11-26    15525
2018-11-21    15113
2018-12-20    14970
2018-12-21    14580
2018-10-23    14407
2018-10-24    14281
2018-11-27    14161
2018-10-25    13696
2018-12-26    13501
2018-12-05    12399
2018-12-17    11901
2018-12-19    11826
2018-11-20    11453
2018-11-16    10831
2018-10-18    10405
2018-12-10    10144
2018-12-11    10055
2018-12-18    10014
2018-11-29     9662
2018-12-28     9382
2018-11-09     9185
2018-11-19     9062
2018-11-12     8856
2018-11-28     8792
2018-12-27     8740
2018-12-07     8739
2018-10-15     8635
2018-11-08     8493
2018-10-26     8425
2018-10-05     8132
2018-11-05     7838
2018-12-06     7297
2018-10-03     7227
2018-12-03     6798
2018-10-09     6764
2018-11-01     6554
2018-12-12     6438
2018-11-07     6424
2018-12-14     6240
2018-12-04     6021
2018-12-13     6008
2018-11-15     5907
2018-10-29     5906
2018-10-04     5593
2018-11-13     5565
2018-11-02     5478
2018-11-14     5005
2018-10-08     4264
2018-11-06     3965
2018-10-30     3482
2018-11-30     1197
2018-10-01     1175
2018-12-25     1168
2018-10-02     1088
2018-12-16      968
2018-12-30      964
2018-12-31      870
2018-11-25      792
2018-12-24      783
2018-12-23      725
2018-12-09      636
2018-11-22      562
2018-12-02      443
2018-10-10      367
2018-12-01      291
2018-12-22      275
2018-12-29      268
2018-11-23      259
2018-10-06      228
2018-10-11      204
2018-11-24      198
2018-10-16      157
2018-12-15      129
2018-10-07      127
2018-10-31       65
2018-12-08       25
2018-11-03       18
2018-10-20       16
2018-10-13       11
2018-10-21        9
2018-11-17        7
2018-11-10        5
2018-10-12        5
2018-10-27        4
Name: Charge Date, dtype: int64

In [28]:
df_utility.head()

,ChargeID,ChargeID.1,ChargeID.1.1,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
0,0,0,0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012,1,9,27944
1,1,1,1,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012,1,9,27944
2,2,2,2,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012,1,9,27944
3,3,3,3,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012,1,9,27944
4,4,4,4,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012,1,9,27944

In [36]:
df_oct = df_utility[(df_utility['Month'] == 10) & (df_utility['Year'] == 2018)]

In [42]:
month_charge_date = df_oct['Charge Date'].str.split('-', expand=True)[1]

In [46]:
month_charge_date.head()

13689491    12
13689492    12
13689493    12
13689494    10
13689495    10
Name: 1, dtype: object

In [51]:
month_charge_date.iloc[4]

'10'

In [56]:
out = df_oct[month_charge_date.astype(int) != df_oct['Month']]

In [57]:
out.shape

(353505, 18)

In [61]:
out.head()

,ChargeID,ChargeID.1,ChargeID.1.1,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
13689491,13689491,13689491,13689491,10001,300 ACORN ST,216323.0,NaN,NaN,CDEP,NaN,NaN,NaN,200.00,2018-12-06,2018,10,6,1772
13689492,13689492,13689492,13689492,10001,300 ACORN ST,216323.0,NaN,NaN,NaN,NaN,NaN,NaN,40.00,2018-12-11,2018,10,11,1772
13689493,13689493,13689493,13689493,10001,300 ACORN ST,216323.0,NaN,NaN,CUTO,NaN,NaN,NaN,30.00,2018-12-16,2018,10,16,1772
13689501,13689501,13689501,13689501,10002,212 ACORN ST,10002.0,DELC,100.0,216,289.0,31.0,KWH,88.07,2018-11-07,2018,10,7,27944
13689502,13689502,13689502,13689502,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,22.49,2018-11-07,2018,10,7,27944

In [62]:
df_utility.head()

,ChargeID,ChargeID.1,ChargeID.1.1,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
0,0,0,0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012,1,9,27944
1,1,1,1,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012,1,9,27944
2,2,2,2,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012,1,9,27944
3,3,3,3,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012,1,9,27944
4,4,4,4,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012,1,9,27944

In [65]:
exclusion = df_utility[~df_utility.isin(out)]

In [73]:
sum(exclusion.isna().all(axis=1))

353505

In [88]:
dropout = exclusion.dropna(how='all')

In [89]:
dropout.shape

(14394890, 18)

In [90]:
dropout.head()

,ChargeID,ChargeID.1,ChargeID.1.1,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
0,0.0,0.0,0.0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012.0,1.0,9.0,27944.0
1,1.0,1.0,1.0,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012.0,1.0,9.0,27944.0
2,2.0,2.0,2.0,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012.0,1.0,9.0,27944.0
3,3.0,3.0,3.0,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012.0,1.0,9.0,27944.0
4,4.0,4.0,4.0,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012.0,1.0,9.0,27944.0

In [91]:
dropout.drop(['ChargeID', 'ChargeID.1', 'ChargeID.1.1', 'PrimaryID'], axis=1, inplace=True)

In [92]:
dropout.head()

,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day
0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012.0,1.0,9.0
1,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012.0,1.0,9.0
2,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012.0,1.0,9.0
3,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012.0,1.0,9.0
4,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012.0,1.0,9.0

In [93]:
dropout.to_csv('/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/ToDatabase/TotalUtilities_v03.csv', index=False)

In [94]:
df_fin = pd.read_csv('/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/ToDatabase/TotalUtilities_v04.csv')

/anaconda3/envs/cds/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (1,4,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [95]:
df_fin.head()

,ChargeID,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
0,0,10002,212 ACORN ST,10002.0,DELC,100.0,216,340.0,30.0,KWH,79.85,2012-01-09,2012.0,1.0,9.0,27944
1,1,10002,212 ACORN ST,10002.0,NaN,150.0,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012.0,1.0,9.0,27944
2,2,10002,212 ACORN ST,10002.0,CGAS,200.0,220,37.0,30.0,CCF,47.13,2012-01-09,2012.0,1.0,9.0,27944
3,3,10002,212 ACORN ST,10002.0,CWTR,300.0,230,1.0,30.0,TGAL,9.67,2012-01-09,2012.0,1.0,9.0,27944
4,4,10002,212 ACORN ST,10002.0,CSWR,400.0,250,1.0,30.0,NONE,10.93,2012-01-09,2012.0,1.0,9.0,27944