In [35]:
import pandas as pd
import numpy as np
import math

In [36]:
pd.options.display.max_columns = 300
pd.options.display.max_rows = 300

In [37]:
path = '/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/ToDatabase/'

In [38]:
df_address = pd.read_csv(path+'TestDB/Ship/Address_v02.csv')

In [39]:
df_housing = pd.read_csv(path+'TestDB/Ship/Project_v02.csv')

In [40]:
df_utility = pd.read_csv(path+'TestDB/Ship/Utility_v03.csv')

/anaconda3/envs/cds/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (1,4,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [41]:
df_weather = pd.read_csv(path+'TestDB/Ship/Weather_v03.csv')

In [42]:
df_tax = pd.read_csv(path+'TestDB/Ship/Tax_v02.csv')

In [43]:
df_real = pd.read_csv(path+'TestDB/Ship/RealEstate_v02.csv')

In [44]:
df_bg = pd.read_csv(path+'CensusBlock_v02.csv')

In [19]:
df_tract = pd.read_csv(path+'CensusTract_v02.csv')

In [20]:
all_df = [df_address, df_housing, df_utility, df_weather, df_tax, df_real, df_bg, df_tract]

# Steps
1. Identify datasets that I believe are ready to go
2. Identify datasets that have small changes
3. Identify datasets that have major changes

## Step 1

In [45]:
def duplicated(df):
    cols = list(df)
    uniques = []
    for col in cols:
        valuelist = df[col].value_counts()
        if len(valuelist) == 0:
            uniques.append(True)
        else:
            uniques.append(valuelist.iloc[0]==1)
    return uniques

def construct_summary(df):
    return pd.DataFrame({'Datatype': df.dtypes, 'Nulls': df.isna().any(),
             'Uniques': duplicated(df)})

#### Does the address table have correct columns, datatypes, and values?

In [46]:
new_cols = ['AddressID', 'Address', 'XCoord', 'YCoord', 'Tract', 'BlockGroup',
           'BlockGroupTract', 'Block', 'TractID', 'BlockGroupID', 'TaxID', 'RealEstateID']
df_address = df_address.loc[:,new_cols]
df_address.head()

,AddressID,Address,XCoord,YCoord,Tract,BlockGroup,BlockGroupTract,Block,TractID,BlockGroupID,TaxID,RealEstateID
0,1,501 S MADISON ST,31.570488,-84.162164,1500.0,1.0,1_1500,13.0,13,39,331735,1
1,2,525 LINCOLN AVE,31.569466,-84.161175,1500.0,1.0,1_1500,12.0,13,39,348937,26969
2,3,609 S JACKSON ST,31.568513,-84.153922,1403.0,1.0,1_1403,27.0,12,37,363997,2
3,4,602 S MONROE ST,31.568661,-84.158641,1403.0,1.0,1_1403,25.0,12,37,358361,3
4,5,509 W GORDON AVE,31.568554,-84.159772,1500.0,1.0,1_1500,17.0,13,39,421916,26969

In [47]:
df_address[['Tract', 'BlockGroup', 'Block']] = df_address[['Tract', 'BlockGroup', 'Block']].astype('Int64')

In [48]:
construct_summary(df_address)

                Datatype  Nulls  Uniques
AddressID          int64  False     True
Address           object  False     True
XCoord           float64   True    False
YCoord           float64   True    False
Tract              Int64   True    False
BlockGroup         Int64   True    False
BlockGroupTract   object   True    False
Block              Int64   True    False
TractID            int64  False    False
BlockGroupID       int64  False    False
TaxID              int64  False    False
RealEstateID       int64  False    False

#### Does the housing table have correct columns, datatypes, and values?

In [30]:
df_housing.drop(['IDISActivityIDFull', 'IDISActivityIDFirst', 'IDISActivityIDEnd'], axis=1, inplace=True)
df_housing.head()

,ProjectID,AddressID,ParcelID,Address,PlanYear,IDISProject,Project,IDISActivityID,ActivityStatus,Program,FundedAmount,DrawAmount,Balance,MultihomeType,Multihome,InitialDate,StatusDate
0,1,21205,0000Q/00025/009,1707 EDGERLY AVE,2007,6,Homeowner Rehabilitation,618,Completed,HOME,27033.46,27033.46,0.0,NaN,NaN,6/3/08,9/29/09
1,2,26764,0000U/00006/002,703 DARTMOUTH LN,2007,6,Homeowner Rehabilitation,634,Completed,HOME,30185.60,30185.60,0.0,NaN,NaN,7/7/08,12/22/09
2,3,21681,0000H/00047/005,1115 W WADDELL AVE,2007,6,Homeowner Rehabilitation,610,Completed,HOME,28678.19,28678.19,0.0,NaN,NaN,6/2/08,9/29/09
3,4,28936,0000X/00003/034,313 FORRESTAL LN,2007,6,Homeowner Rehabilitation,633,Completed,HOME,34694.47,34694.47,0.0,NaN,NaN,7/7/08,12/23/09
4,5,22321,00240/00003/024,1125 JOEL DR,2007,6,Homeowner Rehabilitation,600,Completed,HOME,30756.96,30756.96,0.0,NaN,NaN,5/19/08,9/29/09

In [31]:
construct_summary(df_housing)

               Datatype  Nulls  Uniques
ProjectID         int64  False     True
AddressID         int64  False    False
ParcelID         object   True    False
Address          object  False    False
PlanYear          int64  False    False
IDISProject       int64  False    False
Project          object  False    False
IDISActivityID    int64  False    False
ActivityStatus   object  False    False
Program          object  False    False
FundedAmount    float64  False    False
DrawAmount      float64   True    False
Balance         float64  False    False
MultihomeType    object   True    False
Multihome        object   True    False
InitialDate      object   True    False
StatusDate       object   True    False

#### Does the utility table have correct columns, datatypes, and values?

In [44]:
df_utility[['ServiceNumber', 'DaysOfService']] = df_utility[['ServiceNumber', 'DaysOfService']].astype('Int64')
df_utility.head()

,ChargeID,Premise,PremiseAddress,Customer,ServiceType,ServiceNumber,ServiceRate,Consumption,DaysOfService,UnitOfMeasure,ChargeAmount,ChargeDate,Year,Month,Day,AddressID,YearMonth,WeatherID
0,1,10002,212 ACORN ST,10002,DELC,100,216,340.0,30,KWH,79.85,2012-01-09,2012,1,9,27945,2012_1,133
1,2,10002,212 ACORN ST,10002,NaN,150,NaN,NaN,NaN,NaN,17.12,2012-01-09,2012,1,9,27945,2012_1,133
2,3,10002,212 ACORN ST,10002,CGAS,200,220,37.0,30,CCF,47.13,2012-01-09,2012,1,9,27945,2012_1,133
3,4,10002,212 ACORN ST,10002,CWTR,300,230,1.0,30,TGAL,9.67,2012-01-09,2012,1,9,27945,2012_1,133
4,5,10002,212 ACORN ST,10002,CSWR,400,250,1.0,30,NONE,10.93,2012-01-09,2012,1,9,27945,2012_1,133

In [45]:
construct_summary(df_utility)

               Datatype  Nulls  Uniques
ChargeID          int64  False     True
Premise          object   True    False
PremiseAddress   object  False    False
Customer          int64  False    False
ServiceType      object   True    False
ServiceNumber     Int64   True    False
ServiceRate      object   True    False
Consumption     float64   True    False
DaysOfService     Int64   True    False
UnitOfMeasure    object   True    False
ChargeAmount    float64  False    False
ChargeDate       object  False    False
Year              int64  False    False
Month             int64  False    False
Day               int64  False    False
AddressID         int64  False    False
YearMonth        object  False    False
WeatherID         int64  False    False

#### Does the weather table have correct columns, datatypes, and values?

In [46]:
df_weather.head()

,WeatherID,Year,Month,Date,MonthlyMaxTemp,MonthlyMinTemp,MonthlyMeanTemp,AWND,CLDD,HTDD,YearMonth
0,1,2001,1,2001-01-31T23:59:00,59.3,32.9,46.1,5.6,4,591,2001_1
1,2,2001,2,2001-02-28T23:59:00,69.8,47.3,58.6,5.8,18,187,2001_2
2,3,2001,3,2001-03-31T23:59:00,67.4,45.9,56.7,7.6,12,262,2001_3
3,4,2001,4,2001-04-30T23:59:00,79.5,53.7,66.6,5.8,116,69,2001_4
4,5,2001,5,2001-05-31T23:59:00,86.5,60.3,73.4,5.1,261,0,2001_5

In [49]:
construct_summary(df_weather)

                Datatype  Nulls  Uniques
WeatherID          int64  False     True
Year               int64  False    False
Month              int64  False    False
Date              object   True     True
MonthlyMaxTemp   float64  False    False
MonthlyMinTemp   float64  False    False
MonthlyMeanTemp  float64  False    False
AWND             float64   True    False
CLDD               int64  False    False
HTDD               int64  False    False
YearMonth         object  False     True

## Step 2

#### Tax

In [49]:
old = df_tax['Address']
replaced = old.replace("nan","",regex=True)
old[~old.isin(replaced)]

7               0 A C L RAILROAD nan
8               0 A C L RAILROAD nan
9               0 A C L RAILROAD nan
10              0 A C L RAILROAD nan
11              0 A C L RAILROAD nan
12              0 A C L RAILROAD nan
13              0 A C L RAILROAD nan
14              0 A C L RAILROAD nan
15              0 A C L RAILROAD nan
16              0 A C L RAILROAD nan
17              0 A C L RAILROAD nan
18              0 A C L RAILROAD nan
19              0 A C L RAILROAD nan
20              0 A C L RAILROAD nan
21              0 A C L RAILROAD nan
22              0 A C L RAILROAD nan
23              0 A C L RAILROAD nan
24              0 A C L RAILROAD nan
25              0 A C L RAILROAD nan
26              0 A C L RAILROAD nan
27              0 A C L RAILROAD nan
28              0 A C L RAILROAD nan
29              0 A C L RAILROAD nan
30              0 A C L RAILROAD nan
31              0 A C L RAILROAD nan
32              0 A C L RAILROAD nan
33              0 A C L RAILROAD nan
34              0 A C L RAILROAD nan
35              0 A C L RAILROAD nan
36              0 A C L RAILROAD nan
37              0 A C L RAILROAD nan
38              0 A C L RAILROAD nan
39              0 A C L RAILROAD nan
40              0 A C L RAILROAD nan
41              0 A C L RAILROAD nan
42              0 A C L RAILROAD nan
43              0 A C L RAILROAD nan
44              0 A C L RAILROAD nan
45              0 A C L RAILROAD nan
46              0 A C L RAILROAD nan
47              0 A C L RAILROAD nan
48              0 A C L RAILROAD nan
49              0 A C L RAILROAD nan
50              0 A C L RAILROAD nan
51              0 A C L RAILROAD nan
52              0 A C L RAILROAD nan
53              0 A C L RAILROAD nan
54              0 A C L RAILROAD nan
55              0 A C L RAILROAD nan
56              0 A C L RAILROAD nan
57              0 A C L RAILROAD nan
58              0 A C L RAILROAD nan
59              0 A C L RAILROAD nan
60              0 A C L RAILROAD nan
61              0 A C L RAILROAD nan
62              0 A C L RAILROAD nan
63              0 A C L RAILROAD nan
64              0 A C L RAILROAD nan
65              0 A C L RAILROAD nan
66              0 A C L RAILROAD nan
67              0 A C L RAILROAD nan
68              0 A C L RAILROAD nan
69              0 A C L RAILROAD nan
70              0 A C L RAILROAD nan
71              0 A C L RAILROAD nan
72              0 A C L RAILROAD nan
73              0 A C L RAILROAD nan
74              0 A C L RAILROAD nan
75              0 A C L RAILROAD nan
76              0 A C L RAILROAD nan
77              0 A C L RAILROAD nan
78              0 A C L RAILROAD nan
79              0 A C L RAILROAD nan
80              0 A C L RAILROAD nan
81              0 A C L RAILROAD nan
82              0 A C L RAILROAD nan
83              0 A C L RAILROAD nan
84              0 A C L RAILROAD nan
85              0 A C L RAILROAD nan
86              0 A C L RAILROAD nan
87              0 A C L RAILROAD nan
88              0 A C L RAILROAD nan
89              0 A C L RAILROAD nan
90              0 A C L RAILROAD nan
91              0 A C L RAILROAD nan
92              0 A C L RAILROAD nan
93              0 A C L RAILROAD nan
94              0 A C L RAILROAD nan
95              0 A C L RAILROAD nan
96              0 A C L RAILROAD nan
97              0 A C L RAILROAD nan
98              0 A C L RAILROAD nan
99              0 A C L RAILROAD nan
100             0 A C L RAILROAD nan
101             0 A C L RAILROAD nan
102             0 A C L RAILROAD nan
103             0 A C L RAILROAD nan
104             0 A C L RAILROAD nan
105             0 A C L RAILROAD nan
106             0 A C L RAILROAD nan
107             0 A C L RAILROAD nan
108             0 A C L RAILROAD nan
109             0 A C L RAILROAD nan
110             0 A C L RAILROAD nan
111             0 A C L RAILROAD nan
112             0 A C L RAILROAD nan
113             0 A C L RAILROAD nan
114             0 A C L RAILROAD nan
115             0 A C L RAILROAD nan
116             0 A C L RAILROAD nan
117             0 A C L RAILROAD nan
118             0 A C L RAILROAD nan
119             0 A C L RAILROAD nan
120             0 A C L RAILROAD nan
121             0 A C L RAILROAD nan
122             0 A C L RAILROAD nan
123             0 A C L RAILROAD nan
124             0 A C L RAILROAD nan
125             0 A C L RAILROAD nan
126             0 A C L RAILROAD nan
127             0 A C L RAILROAD nan
128             0 A C L RAILROAD nan
129             0 A C L RAILROAD nan
130             0 A C L RAILROAD nan
131             0 A C L RAILROAD nan
132             0 A C L RAILROAD nan
133             0 A C L RAILROAD nan
134             0 A C L RAILROAD nan
135             0 A C L RAILROAD nan
136             0 A C L RAILROAD nan
137             0 A C L RAILROAD nan
138             0 A C L RAILROAD nan
139             0 A C L RAILROAD nan
140             0 A C L RAILROAD nan
141             0 A C L RAILROAD nan
142             0 A C L RAILROAD nan
143             0 A C L RAILROAD nan
144             0 A C L RAILROAD nan
145             0 A C L RAILROAD nan
146             0 A C L RAILROAD nan
147             0 A C L RAILROAD nan
148             0 A C L RAILROAD nan
149             0 A C L RAILROAD nan
150             0 A C L RAILROAD nan
151             0 A C L RAILROAD nan
152             0 A C L RAILROAD nan
153             0 A C L RAILROAD nan
154             0 A C L RAILROAD nan
155             0 A C L RAILROAD nan
156             0 A C L RAILROAD nan
                     ...
383511    708 LIBERTY EXPRESSWAY nan
383512    708 LIBERTY EXPRESSWAY nan
383513    708 LIBERTY EXPRESSWAY nan
383514    708 LIBERTY EXPRESSWAY nan
383515    708 LIBERTY EXPRESSWAY nan
383516    708 LIBERTY EXPRESSWAY nan
383517    708 LIBERTY EXPRESSWAY nan
383518    708 LIBERTY EXPRESSWAY nan
390326    724 LIBERTY EXPRESSWAY nan
390327    724 LIBERTY EXPRESSWAY nan
390328    724 LIBERTY EXPRESSWAY nan
390329    724 LIBERTY EXPRESSWAY nan
390330    724 LIBERTY EXPRESSWAY nan
390331    724 LIBERTY EXPRESSWAY nan
390332    724 LIBERTY EXPRESSWAY nan
390333    724 LIBERTY EXPRESSWAY nan
390334    724 LIBERTY EXPRESSWAY nan
390335    724 LIBERTY EXPRESSWAY nan
390336    724 LIBERTY EXPRESSWAY nan
391022    728 LIBERTY EXPRESSWAY nan
391023    728 LIBERTY EXPRESSWAY nan
391024    728 LIBERTY EXPRESSWAY nan
391025    728 LIBERTY EXPRESSWAY nan
391026    728 LIBERTY EXPRESSWAY nan
391027    728 LIBERTY EXPRESSWAY nan
391028    728 LIBERTY EXPRESSWAY nan
391029    728 LIBERTY EXPRESSWAY nan
391030    728 LIBERTY EXPRESSWAY nan
391031    728 LIBERTY EXPRESSWAY nan
391032    728 LIBERTY EXPRESSWAY nan
391663    733 LIBERTY EXPRESSWAY nan
391664    733 LIBERTY EXPRESSWAY nan
391665    733 LIBERTY EXPRESSWAY nan
391666    733 LIBERTY EXPRESSWAY nan
391667    733 LIBERTY EXPRESSWAY nan
391668    733 LIBERTY EXPRESSWAY nan
391669    733 LIBERTY EXPRESSWAY nan
391670    733 LIBERTY EXPRESSWAY nan
391671    733 LIBERTY EXPRESSWAY nan
391672    733 LIBERTY EXPRESSWAY nan
391673    733 LIBERTY EXPRESSWAY nan
392554    800 LIBERTY EXPRESSWAY nan
392555    800 LIBERTY EXPRESSWAY nan
392556    800 LIBERTY EXPRESSWAY nan
392557    800 LIBERTY EXPRESSWAY nan
392558    800 LIBERTY EXPRESSWAY nan
392559    800 LIBERTY EXPRESSWAY nan
392560    800 LIBERTY EXPRESSWAY nan
392561    800 LIBERTY EXPRESSWAY nan
392562    800 LIBERTY EXPRESSWAY nan
392563    800 LIBERTY EXPRESSWAY nan
392564    800 LIBERTY EXPRESSWAY nan
397916    808 LIBERTY EXPRESSWAY nan
397917    808 LIBERTY EXPRESSWAY nan
397918    808 LIBERTY EXPRESSWAY nan
397919    808 LIBERTY EXPRESSWAY nan
397920    808 LIBERTY EXPRESSWAY nan
397921    808 LIBERTY EXPRESSWAY nan
397922    808 LIBERTY EXPRESSWAY nan
397923    808 LIBERTY EXPRESSWAY nan
397924    808 LIBERTY EXPRESSWAY nan
397925    808 LIBERTY EXPRESSWAY nan
398567    809 LIBERTY EXPRESSWAY nan
398568    809 LIBERTY EXPRESSWAY nan
398569    809 LIBERTY EXPRESSWAY nan
398570    809 LIBERTY EXPRESSWAY nan
398571    809 LIBERTY EXPRESSWAY nan
398572    809 LIBERTY EXPRESSWAY nan
398573    809 LIBERTY EXPRESSWAY nan
398574    809 LIBERTY EXPRESSWAY nan
398575    809 LIBERTY EXPRESSWAY nan
398576    809 LIBERTY EXPRESSWAY nan
398577    809 LIBERTY EXPRESSWAY nan
401946    816 LIBERTY EXPRESSWAY nan
401947    816 LIBERTY EXPRESSWAY nan
401948    816 LIBERTY EXPRESSWAY nan
401949    816 LIBERTY EXPRESSWAY nan
401950    816 LIBERTY EXPRESSWAY nan
401951    816 LIBERTY EXPRESSWAY nan
401952    816 LIBERTY EXPRESSWAY nan
401953    816 LIBERTY EXPRESSWAY nan
401954    816 LIBERTY EXPRESSWAY nan
401955    816 LIBERTY EXPRESSWAY nan
401956    816 LIBERTY EXPRESSWAY nan
403446    820 LIBERTY EXPRESSWAY nan
403447    820 LIBERTY EXPRESSWAY nan
403448    820 LIBERTY EXPRESSWAY nan
403449    820 LIBERTY EXPRESSWAY nan
403450    820 LIBERTY EXPRESSWAY nan
403451    820 LIBERTY EXPRESSWAY nan
403452    820 LIBERTY EXPRESSWAY nan
403453    820 LIBERTY EXPRESSWAY nan
403454    820 LIBERTY EXPRESSWAY nan
403455    820 LIBERTY EXPRESSWAY nan
403456    820 LIBERTY EXPRESSWAY nan
403808    821 LIBERTY EXPRESSWAY nan
403809    821 LIBERTY EXPRESSWAY nan
403810    821 LIBERTY EXPRESSWAY nan
403811    821 LIBERTY EXPRESSWAY nan
403812    821 LIBERTY EXPRESSWAY nan
403813    821 LIBERTY EXPRESSWAY nan
403814    821 LIBERTY EXPRESSWAY nan
403815    821 LIBERTY EXPRESSWAY nan
403816    821 LIBERTY EXPRESSWAY nan
403817    821 LIBERTY EXPRESSWAY nan
403818    821 LIBERTY EXPRESSWAY nan
405203    826 LIBERTY EXPRESSWAY nan
405204    826 LIBERTY EXPRESSWAY nan
405205    826 LIBERTY EXPRESSWAY nan
405206    826 LIBERTY EXPRESSWAY nan
405207    826 LIBERTY EXPRESSWAY nan
405208    826 LIBERTY EXPRESSWAY nan
405209    826 LIBERTY EXPRESSWAY nan
405210    826 LIBERTY EXPRESSWAY nan
405211    826 LIBERTY EXPRESSWAY nan
405212    826 LIBERTY EXPRESSWAY nan
405213    826 LIBERTY EXPRESSWAY nan
405873    829 LIBERTY EXPRESSWAY nan
405874    829 LIBERTY EXPRESSWAY nan
405875    829 LIBERTY EXPRESSWAY nan
405876    829 LIBERTY EXPRESSWAY nan
405877    829 LIBERTY EXPRESSWAY nan
405878    829 LIBERTY EXPRESSWAY nan
405879    829 LIBERTY EXPRESSWAY nan
405880    829 LIBERTY EXPRESSWAY nan
405881    829 LIBERTY EXPRESSWAY nan
405882    829 LIBERTY EXPRESSWAY nan
405883    829 LIBERTY EXPRESSWAY nan
406104    830 LIBERTY EXPRESSWAY nan
406105    830 LIBERTY EXPRESSWAY nan
406106    830 LIBERTY EXPRESSWAY nan
406107    830 LIBERTY EXPRESSWAY nan
406108    830 LIBERTY EXPRESSWAY nan
406109    830 LIBERTY EXPRESSWAY nan
406110    830 LIBERTY EXPRESSWAY nan
406111    830 LIBERTY EXPRESSWAY nan
406112    830 LIBERTY EXPRESSWAY nan
406113    830 LIBERTY EXPRESSWAY nan
406114    830 LIBERTY EXPRESSWAY nan
421027    932 LIBERTY EXPRESSWAY nan
421028    932 LIBERTY EXPRESSWAY nan
421029    932 LIBERTY EXPRESSWAY nan
421030    932 LIBERTY EXPRESSWAY nan
421031    932 LIBERTY EXPRESSWAY nan
421032    932 LIBERTY EXPRESSWAY nan
421033    932 LIBERTY EXPRESSWAY nan
421034    932 LIBERTY EXPRESSWAY nan
421035    932 LIBERTY EXPRESSWAY nan
421036    932 LIBERTY EXPRESSWAY nan
421037    932 LIBERTY EXPRESSWAY nan
Name: Address, Length: 2436, dtype: object

In [50]:
df_tax.loc[df_tax['Address'].str.contains("nan"), 'Address'] = df_tax.loc[df_tax['Address'].str.contains("nan"), 'Address'].replace("nan","", regex=True)

In [52]:
df_tax.to_csv(path+'TestDB/Ship/Tax_v03.csv', index=False)

#### Real Estate

In [84]:
df_real.head()

,RealEstateID,Address,LotSize,ZoningType,SizeZoningIdent,PropClass,YearBuilt,Size,Baths,Beds,Rooms,Floors,Condition,FoundationType,RoofCover,WallType,ImprovementYear,Assessment,Market,AddressID
0,1,501 S MADISON ST,0.34,Residential,R6,Single Family Residence / Townhouse,1927.0,2446.0,1.0,0.0,0.0,WOOD,FAIR,MASONRY,ASPHALT,COMPOSITION,0.0,16120.0,40300.0,1.0
1,2,609 S JACKSON ST,0.09,Residential,R6,Single Family Residence / Townhouse,1948.0,1640.0,1.0,3.0,0.0,WOOD,AVERAGE,MASONRY,ASPHALT,NaN,0.0,12560.0,31400.0,3.0
2,3,602 S MONROE ST,0.18,Commercial,R3,Vacant,NaN,1160.0,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,2520.0,6300.0,4.0
3,4,610 W GORDON AVE,0.18,Residential,R3,Single Family Residence / Townhouse,1941.0,1154.0,1.0,3.0,4.0,WOOD,AVERAGE,MASONRY,ASPHALT,COMPOSITION,0.0,10240.0,25600.0,6.0
4,5,700 W GORDON AVE,0.09,Residential,R3,Single Family Residence / Townhouse,1940.0,1488.0,1.0,3.0,7.0,WOOD,AVERAGE,MASONRY,ASPHALT,ALUMINUM/VINYL,0.0,16480.0,41200.0,7.0

In [91]:
df_real.loc[26968, 'AddressID'] = 30590

In [92]:
df_real.tail()

,RealEstateID,Address,LotSize,ZoningType,SizeZoningIdent,PropClass,YearBuilt,Size,Baths,Beds,Rooms,Floors,Condition,FoundationType,RoofCover,WallType,ImprovementYear,Assessment,Market,AddressID
26964,26965,2415 DAWSON RD,0.93,Commercial,NaN,Retail,1972.0,12681.0,0.0,0.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,200716.0,501790.0,13281.0
26965,26966,1924 LEDO RD,1.34,Other,NaN,Commercial,1972.0,3280.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,29080.0,72700.0,15916.0
26966,26967,1301 EVELYN AVE,13.62,Commercial,NaN,Commercial,1996.0,5950.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,472160.0,1180400.0,25821.0
26967,26968,320 E OGLETHORPE BLVD,3.14,Commercial,NaN,Service (general public),1963.0,11729.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,364240.0,910600.0,26504.0
26968,26969,NOT FOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30590.0

In [93]:
df_real[['YearBuilt', 'ImprovementYear', 'AddressID']] = df_real[['YearBuilt', 'ImprovementYear', 'AddressID']].astype('Int64')

In [94]:
construct_summary(df_real)

                Datatype  Nulls  Uniques
RealEstateID       int64  False     True
Address           object  False    False
LotSize          float64   True    False
ZoningType        object   True    False
SizeZoningIdent   object   True    False
PropClass         object   True    False
YearBuilt          Int64   True    False
Size             float64   True    False
Baths            float64   True    False
Beds             float64   True    False
Rooms            float64   True    False
Floors            object   True    False
Condition         object   True    False
FoundationType    object   True    False
RoofCover         object   True    False
WallType          object   True    False
ImprovementYear    Int64   True    False
Assessment       float64   True    False
Market           float64   True    False
AddressID          Int64  False    False

In [95]:
df_real.head()

,RealEstateID,Address,LotSize,ZoningType,SizeZoningIdent,PropClass,YearBuilt,Size,Baths,Beds,Rooms,Floors,Condition,FoundationType,RoofCover,WallType,ImprovementYear,Assessment,Market,AddressID
0,1,501 S MADISON ST,0.34,Residential,R6,Single Family Residence / Townhouse,1927,2446.0,1.0,0.0,0.0,WOOD,FAIR,MASONRY,ASPHALT,COMPOSITION,0,16120.0,40300.0,1
1,2,609 S JACKSON ST,0.09,Residential,R6,Single Family Residence / Townhouse,1948,1640.0,1.0,3.0,0.0,WOOD,AVERAGE,MASONRY,ASPHALT,NaN,0,12560.0,31400.0,3
2,3,602 S MONROE ST,0.18,Commercial,R3,Vacant,NaN,1160.0,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,0,2520.0,6300.0,4
3,4,610 W GORDON AVE,0.18,Residential,R3,Single Family Residence / Townhouse,1941,1154.0,1.0,3.0,4.0,WOOD,AVERAGE,MASONRY,ASPHALT,COMPOSITION,0,10240.0,25600.0,6
4,5,700 W GORDON AVE,0.09,Residential,R3,Single Family Residence / Townhouse,1940,1488.0,1.0,3.0,7.0,WOOD,AVERAGE,MASONRY,ASPHALT,ALUMINUM/VINYL,0,16480.0,41200.0,7

## Step 3

## First upload census and blockgroup with junction

In [138]:
def linker(df_modified, df_info, info_key_name, info_value_name, modified_col, not_found=None): # modified from map_addr_key
    id_dict = df_info.set_index(info_key_name).to_dict()[info_value_name]
    s_modified = df_modified[modified_col]
    linked_ids = [None] * len(df_modified)
    not_found_dict = {}
    counter = 0
    for i in range(len(s_modified)):
        if counter % 100000 == 0:
            print(str(counter))
        try:
            #linked_ids[i] = id_dict[s_modified[i]]
            #linked_ids[i].append()
        except KeyError:
            if not_found == None:
                print("FATAL ERROR. Corresponding key not found.")
            linked_ids[i] = id_dict[not_found]
            not_found_dict[i] = s_modified[i]
        counter += 1
    # Change this in the future to have linked ids be a series
    return linked_ids, pd.DataFrame(data={'key':list(not_found_dict.values()), 
                                          'location': list(not_found_dict.keys())})

In [139]:
addr_bg = pd.read_csv(path+'TestDB/Ship/AddrJunctBG.csv')

In [140]:
bg_tract = pd.read_csv(path+'TestDB/Ship/BGJunctTract.csv')

In [141]:
addr_bg.shape

(152854, 2)

In [142]:
bg_tract.shape

(4441, 2)

In [143]:
df_bg.insert(0, 'BlockGroupID', [i for i in range(1, len(df_bg)+1)])
df_tract.insert(0, 'TractID', [i for i in range(1, len(df_tract)+1)])
df_bg_spec = df_bg[['BlockGroup', 'Tract']]
df_bg.insert(1, 'BlockGroupTract', df_bg_spec.apply(create_blockgroup_spec, axis=1))
lis = [556, "NOT FOUND", np.nan, np.nan, np.nan, np.nan, np.nan]
lis.extend([np.nan]*98)
not_found_entry = pd.DataFrame([lis], columns=list(df_bg))
df_bg = df_bg.append(not_found_entry, ignore_index=True)

In [144]:
def create_blockgroup_spec(x):
    a = x.iloc[0]
    b = x.iloc[1]
    if not math.isnan(a) and not math.isnan(b):
        return str(int(a)) + "_" + str(int(b))

In [145]:
df_bg.tail()

,BlockGroupID,BlockGroupTract,GEO.id,Year,GEO.id2,Tract,BlockGroup,County,TotalMale,MaleUnder5,Male5To9,Male10To14,Male15To17,Male18And19,Male20,Male21,Male22To24,Male25To29,Male30To34,Male35To39,Male40To44,Male45To49,Male50To54,Male55To59,Male60And61,Male62To64,Male65And66,Male67To69,Male70To74,Male75To79,Male80To84,Male85AndOver,TotalFemale,FemaleUnder5,Female5To9,Female10To14,Female15To17,Female18And19,Female20,Female21,Female22To24,Female25To29,Female30To34,Female35To39,Female40To44,Female45To49,Female50To54,Female55To59,Female60And61,Female62To64,Female65And66,Female67To69,Female70To74,Female75To79,Female80To84,Female85AndOver,TotalLabor,TotalInLaborforce,TotalCivilLabor,EmployedCivlLabor,UnemployedCivilLabor,TotalArmedForces,TotalNotInLaborforce,TotalPopulation,TotalLessThan10k,Total10kTo14999,Total15kTo19999,Total20kTo24999,Total25kTo29999,Total30kTo34999,Total35kTo39999,Total40kTo44999,Total45kTo49999,Total50kTo59999,Total60kTo74999,Total75kTo99999,Total100kTo124999,Total125kTo149999,Total150kTo199999,Total200kOrMore,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,TotalHomes,TotalOccupiedHomes,TotalVacantHomes,TotalOwnedHomes,TotalRentedHomes
551,552,1_960100,1500000US130079601001,2017.0,1.300796e+11,960100.0,1.0,Baker County,403.0,33.0,41.0,16.0,21.0,0.0,6.0,4.0,6.0,16.0,40.0,6.0,28.0,27.0,57.0,0.0,9.0,26.0,18.0,11.0,31.0,0.0,7.0,0.0,466.0,32.0,31.0,20.0,13.0,0.0,4.0,0.0,37.0,30.0,27.0,0.0,14.0,21.0,44.0,44.0,16.0,9.0,12.0,21.0,21.0,13.0,36.0,21.0,684.0,350.0,350.0,350.0,0.0,0.0,334.0,869.0,88.0,47.0,6.0,9.0,18.0,28.0,7.0,14.0,16.0,22.0,40.0,44.0,22.0,10.0,7.0,0.0,827.0,513.0,314.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,35.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,524.0,378.0,146.0,217.0,161.0
552,553,2_960100,1500000US130079601002,2017.0,1.300796e+11,960100.0,2.0,Baker County,621.0,8.0,12.0,80.0,28.0,45.0,0.0,0.0,16.0,126.0,20.0,32.0,20.0,67.0,62.0,33.0,7.0,21.0,13.0,7.0,13.0,11.0,0.0,0.0,626.0,18.0,36.0,40.0,22.0,12.0,0.0,24.0,53.0,18.0,7.0,46.0,60.0,45.0,60.0,42.0,25.0,40.0,10.0,14.0,34.0,3.0,12.0,5.0,1038.0,488.0,488.0,461.0,27.0,0.0,550.0,1247.0,88.0,7.0,7.0,33.0,8.0,7.0,9.0,44.0,14.0,79.0,53.0,12.0,45.0,13.0,3.0,4.0,1200.0,411.0,771.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,47.0,2.0,0.0,0.0,0.0,0.0,45.0,0.0,0.0,0.0,595.0,426.0,169.0,308.0,118.0
553,554,1_960200,1500000US130079602001,2017.0,1.300796e+11,960200.0,1.0,Baker County,249.0,14.0,0.0,8.0,0.0,0.0,0.0,0.0,34.0,0.0,8.0,30.0,8.0,9.0,0.0,0.0,0.0,53.0,10.0,28.0,11.0,29.0,0.0,7.0,238.0,5.0,10.0,0.0,4.0,0.0,8.0,0.0,0.0,18.0,21.0,3.0,16.0,0.0,8.0,32.0,0.0,29.0,18.0,35.0,16.0,15.0,0.0,0.0,450.0,262.0,262.0,262.0,0.0,0.0,188.0,487.0,0.0,7.0,7.0,27.0,13.0,26.0,0.0,5.0,25.0,36.0,27.0,30.0,0.0,0.0,0.0,21.0,464.0,371.0,71.0,6.0,0.0,16.0,0.0,0.0,0.0,0.0,23.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,298.0,224.0,74.0,180.0,44.0
554,555,2_960200,1500000US130079602002,2017.0,1.300796e+11,960200.0,2.0,Baker County,274.0,10.0,0.0,42.0,21.0,12.0,0.0,0.0,0.0,8.0,13.0,26.0,5.0,34.0,15.0,11.0,12.0,21.0,12.0,11.0,16.0,5.0,0.0,0.0,374.0,7.0,23.0,26.0,34.0,18.0,9.0,0.0,0.0,22.0,18.0,22.0,11.0,14.0,5.0,40.0,11.0,21.0,18.0,19.0,22.0,26.0,0.0,8.0,507.0,219.0,219.0,213.0,6.0,0.0,288.0,648.0,55.0,0.0,10.0,23.0,44.0,24.0,14.0,0.0,18.0,30.0,5.0,36.0,0.0,0.0,34.0,0.0,586.0,400.0,186.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,353.0,293.0,60.0,211.0,82.0
555,556,NOT FOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
df_address.head()

,AddressID,Address,XCoord,YCoord,Tract,BlockGroup,BlockGroupTract,Block,TractID,BlockGroupID,TaxID,RealEstateID
0,1,501 S MADISON ST,31.570488,-84.162164,1500,1,1_1500,13,13,39,331735,1
1,2,525 LINCOLN AVE,31.569466,-84.161175,1500,1,1_1500,12,13,39,348937,26969
2,3,609 S JACKSON ST,31.568513,-84.153922,1403,1,1_1403,27,12,37,363997,2
3,4,602 S MONROE ST,31.568661,-84.158641,1403,1,1_1403,25,12,37,358361,3
4,5,509 W GORDON AVE,31.568554,-84.159772,1500,1,1_1500,17,13,39,421916,26969

In [159]:
junction_l = []
for i in range(len(df_address)):
    if i % 10000 == 0:
        print(i)
    addr_record = df_address.iloc[i]
    curr_combo = addr_record['BlockGroupTract']
    allmatches = df_bg['BlockGroupTract'][df_bg['BlockGroupTract'] == curr_combo].index
    if len(allmatches) == 0:
        junction_l.append(([i+1], [556]))
    else:
        junction_l.append((([i+1]*len(allmatches)), allmatches+1))
junction_one = []
junction_two = []
for i in range(len(junction_l)):
    to_append = junction_l[i]
    junction_one.append(to_append[0])
    junction_two.append(to_append[1])
junction_one = [x for lst in junction_one for x in lst]
junction_two = [x for lst in junction_two for x in lst]
junction = pd.DataFrame({'AddressID':junction_one, 'BlockGroupID':junction_two})

0
10000
20000
30000

In [173]:
junction.to_csv(path+'TestDB/Ship/AddrJunctBG_v02.csv', index=False)

In [193]:
bg_tract['TractID'] = bg_tract['TractID'] + 1

In [194]:
bg_tract.to_csv(path+'TestDB/Ship/BGJunctTract_v02.csv', index=False)

In [196]:
df_tract = df_tract.rename(columns={'tract':'Tract', 'county':'County'})

In [197]:
df_bg.head()

,BlockGroupID,BlockGroupTract,GEO.id,Year,GEO.id2,Tract,BlockGroup,County,TotalMale,MaleUnder5,Male5To9,Male10To14,Male15To17,Male18And19,Male20,Male21,Male22To24,Male25To29,Male30To34,Male35To39,Male40To44,Male45To49,Male50To54,Male55To59,Male60And61,Male62To64,Male65And66,Male67To69,Male70To74,Male75To79,Male80To84,Male85AndOver,TotalFemale,FemaleUnder5,Female5To9,Female10To14,Female15To17,Female18And19,Female20,Female21,Female22To24,Female25To29,Female30To34,Female35To39,Female40To44,Female45To49,Female50To54,Female55To59,Female60And61,Female62To64,Female65And66,Female67To69,Female70To74,Female75To79,Female80To84,Female85AndOver,TotalLabor,TotalInLaborforce,TotalCivilLabor,EmployedCivlLabor,UnemployedCivilLabor,TotalArmedForces,TotalNotInLaborforce,TotalPopulation,TotalLessThan10k,Total10kTo14999,Total15kTo19999,Total20kTo24999,Total25kTo29999,Total30kTo34999,Total35kTo39999,Total40kTo44999,Total45kTo49999,Total50kTo59999,Total60kTo74999,Total75kTo99999,Total100kTo124999,Total125kTo149999,Total150kTo199999,Total200kOrMore,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,TotalHomes,TotalOccupiedHomes,TotalVacantHomes,TotalOwnedHomes,TotalRentedHomes
0,1,1_100,1500000US130950001001,2013.0,1.309500e+11,100.0,1.0,Dougherty County,807.0,58.0,75.0,176.0,9.0,56.0,0.0,0.0,26.0,32.0,17.0,33.0,69.0,0.0,96.0,45.0,28.0,51.0,26.0,0.0,10.0,0.0,0.0,0.0,818.0,72.0,100.0,12.0,0.0,0.0,0.0,10.0,33.0,47.0,33.0,69.0,47.0,127.0,82.0,53.0,27.0,22.0,0.0,0.0,30.0,21.0,0.0,33.0,1132.0,702.0,702.0,473.0,229.0,0.0,430.0,1625.0,85.0,69.0,4.0,38.0,84.0,10.0,15.0,27.0,44.0,25.0,45.0,0.0,66.0,0.0,0.0,0.0,1590.0,206.0,1372.0,0.0,0.0,0.0,0.0,12.0,0.0,12.0,35.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,512.0,512.0,0.0,357.0,155.0
1,2,2_100,1500000US130950001002,2013.0,1.309500e+11,100.0,2.0,Dougherty County,232.0,0.0,30.0,0.0,50.0,13.0,0.0,0.0,11.0,0.0,0.0,14.0,0.0,12.0,0.0,31.0,0.0,23.0,0.0,0.0,0.0,34.0,0.0,14.0,251.0,15.0,0.0,68.0,16.0,0.0,0.0,0.0,0.0,15.0,16.0,13.0,27.0,11.0,48.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,11.0,0.0,370.0,266.0,266.0,242.0,24.0,0.0,104.0,483.0,48.0,22.0,31.0,43.0,0.0,11.0,12.0,14.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,369.0,37.0,332.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,114.0,0.0,0.0,0.0,0.0,0.0,114.0,0.0,0.0,0.0,256.0,194.0,62.0,93.0,101.0
2,3,3_100,1500000US130950001003,2013.0,1.309500e+11,100.0,3.0,Dougherty County,375.0,67.0,166.0,8.0,0.0,37.0,0.0,0.0,0.0,0.0,6.0,13.0,0.0,15.0,17.0,0.0,0.0,13.0,0.0,0.0,0.0,11.0,22.0,0.0,896.0,283.0,109.0,17.0,0.0,0.0,0.0,0.0,146.0,193.0,6.0,0.0,37.0,0.0,8.0,0.0,0.0,13.0,16.0,0.0,68.0,0.0,0.0,0.0,621.0,295.0,295.0,194.0,101.0,0.0,326.0,1271.0,260.0,17.0,30.0,107.0,24.0,0.0,49.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1271.0,149.0,1099.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,668.0,504.0,164.0,73.0,431.0
3,4,4_100,1500000US130950001004,2013.0,1.309500e+11,100.0,4.0,Dougherty County,642.0,41.0,79.0,43.0,0.0,39.0,43.0,35.0,38.0,21.0,32.0,17.0,67.0,77.0,45.0,17.0,8.0,19.0,0.0,0.0,21.0,0.0,0.0,0.0,735.0,0.0,0.0,32.0,39.0,54.0,90.0,51.0,50.0,57.0,0.0,31.0,60.0,91.0,73.0,60.0,0.0,0.0,0.0,0.0,47.0,0.0,0.0,0.0,1160.0,806.0,806.0,580.0,226.0,0.0,354.0,1377.0,198.0,32.0,53.0,49.0,55.0,0.0,14.0,0.0,57.0,77.0,43.0,21.0,19.0,17.0,0.0,0.0,1337.0,135.0,1202.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,35.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,737.0,635.0,102.0,121.0,514.0
4,5,5_100,1500000US130950001005,2013.0,1.309500e+11,100.0,5.0,Dougherty County,207.0,0.0,19.0,19.0,0.0,0.0,0.0,9.0,7.0,57.0,12.0,13.0,12.0,26.0,11.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,11.0,0.0,314.0,4.0,0.0,53.0,0.0,17.0,0.0,0.0,29.0,25.0,0.0,26.0,84.0,38.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,26.0,0.0,426.0,320.0,320.0,257.0,63.0,0.0,106.0,521.0,32.0,9.0,72.0,22.0,33.0,0.0,17.0,0.0,11.0,12.0,30.0,12.0,13.0,0.0,0.0,0.0,499.0,168.0,309.0,11.0,0.0,0.0,0.0,11.0,0.0,11.0,22.0,11.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,336.0,263.0,73.0,121.0,142.0

In [198]:
df_tract.to_csv(path+'TestDB/Ship/Tract_v03.csv', index=False)

In [199]:
df_bg.to_csv(path+'TestDB/Ship/BlockGroup_v03.csv', index=False)

In [200]:
construct_summary(df_bg)

                           Datatype  Nulls  Uniques
BlockGroupID                  int64  False     True
BlockGroupTract              object  False    False
GEO.id                       object   True    False
Year                        float64   True    False
GEO.id2                     float64   True    False
Tract                       float64   True    False
BlockGroup                  float64   True    False
County                       object   True    False
TotalMale                   float64   True    False
MaleUnder5                  float64   True    False
Male5To9                    float64   True    False
Male10To14                  float64   True    False
Male15To17                  float64   True    False
Male18And19                 float64   True    False
Male20                      float64   True    False
Male21                      float64   True    False
Male22To24                  float64   True    False
Male25To29                  float64   True    False
Male30To34                  float64   True    False
Male35To39                  float64   True    False
Male40To44                  float64   True    False
Male45To49                  float64   True    False
Male50To54                  float64   True    False
Male55To59                  float64   True    False
Male60And61                 float64   True    False
Male62To64                  float64   True    False
Male65And66                 float64   True    False
Male67To69                  float64   True    False
Male70To74                  float64   True    False
Male75To79                  float64   True    False
Male80To84                  float64   True    False
Male85AndOver               float64   True    False
TotalFemale                 float64   True    False
FemaleUnder5                float64   True    False
Female5To9                  float64   True    False
Female10To14                float64   True    False
Female15To17                float64   True    False
Female18And19               float64   True    False
Female20                    float64   True    False
Female21                    float64   True    False
Female22To24                float64   True    False
Female25To29                float64   True    False
Female30To34                float64   True    False
Female35To39                float64   True    False
Female40To44                float64   True    False
Female45To49                float64   True    False
Female50To54                float64   True    False
Female55To59                float64   True    False
Female60And61               float64   True    False
Female62To64                float64   True    False
Female65And66               float64   True    False
Female67To69                float64   True    False
Female70To74                float64   True    False
Female75To79                float64   True    False
Female80To84                float64   True    False
Female85AndOver             float64   True    False
TotalLabor                  float64   True    False
TotalInLaborforce           float64   True    False
TotalCivilLabor             float64   True    False
EmployedCivlLabor           float64   True    False
UnemployedCivilLabor        float64   True    False
TotalArmedForces            float64   True    False
TotalNotInLaborforce        float64   True    False
TotalPopulation             float64   True    False
TotalLessThan10k            float64   True    False
Total10kTo14999             float64   True    False
Total15kTo19999             float64   True    False
Total20kTo24999             float64   True    False
Total25kTo29999             float64   True    False
Total30kTo34999             float64   True    False
Total35kTo39999             float64   True    False
Total40kTo44999             float64   True    False
Total45kTo49999             float64   True    False
Total50kTo59999             float64   True    False
Total60kTo74999             float64   True    False
Total75kTo99999             float64   True    False
Total100kTo124999           float64   True    False
Total125kTo149999           float64   True    False
Total150kTo199999           float64   True    False
Total200kOrMore             float64   True    False
NonHispanic                 float64   True    False
NonHispanicWhite            float64   True    False
NonHispanicBlack            float64   True    False
NonHispanicNative           float64   True    False
NonHispanicAsian            float64   True    False
NonHispanicPacificIslander  float64   True    False
NonHispanicOtherRace        float64   True    False
NonHispanic2Plus            float64   True    False
NonHispanic2PlusIncOther    float64   True    False
NonHispanic2PlusExcOther    float64   True    False
Hispanic                    float64   True    False
HispanicWhite               float64   True    False
HispanicBlack               float64   True    False
HispanicNative              float64   True    False
HispanicAsian               float64   True    False
HispanicPacificIslander     float64   True    False
HispanicOtherRace           float64   True    False
Hispanic2Plus               float64   True    False
Hispanic2PlusIncOther       float64   True    False
Hispanic2PlusExcOther       float64   True    False
TotalHomes                  float64   True    False
TotalOccupiedHomes          float64   True    False
TotalVacantHomes            float64   True    False
TotalOwnedHomes             float64   True    False
TotalRentedHomes            float64   True    False

In [201]:
cols = list(df_bg)

In [202]:
remove = ['BlockGroupID', 'BlockGroupTract', 'GEO.id', 'County']
cols = [c for c in cols if c not in remove]

In [208]:
df_bg.loc[:,cols] = df_bg.loc[:,cols].astype('Int64')

In [210]:
df_bg.to_csv(path+'TestDB/Ship/BlockGroup_v03.csv', index=False) #reupload

In [211]:
df_tract.head()

,TractID,GEO.id,GEO.id2,Tract,County,Year,HTotal,FTotal,MTotal,NfTotal,HIncomeLessThan10k,FIncomeLessThan10k,MIncomeLessThan10k,NfIncomeLessThan10k,HIncome10kTo14999,FIncome10kTo14999,MIncome10kTo14999,NfIncome10kTo14999,HIncome15kTo24999,FIncome15kTo24999,MIncome15kTo24999,NfIncome15kTo24999,HIncome25kTo34999,FIncome25kTo34999,MIncome25kTo34999,NfIncome25kTo34999,HIncome35kTo49999,FIncome35kTo49999,MIncome35kTo49999,NfIncome35kTo49999,HIncome50kTo74999,FIncome50kTo74999,MIncome50kTo74999,NfIncome50kTo74999,HIncome75kTo99999,FIncome75kTo99999,MIncome75kTo99999,NfIncome75kTo99999,HIncome100kTo149999,FIncome100kTo149999,MIncome100kTo149999,NfIncome100kTo149999,HIncome150kTo199999,FIncome150kTo199999,MIncome150kTo199999,NfIncome150kTo199999,HIncome200kOrMore,FIncome200kOrMore,MIncome200kOrMore,NfIncome200kOrMore,HIncomeMedian,FIncomeMedian,MIncomeMedian,NfIncomeMedian,HIncomeMean,FIncomeMean,MIncomeMean,NfIncomeMean,TotalPopulation,MaleTotal,FemaleTotal,TotalAgeUnder5,MaleAgeUnder5,FemaleAgeUnder5,TotalAge5To9,MaleAge5To9,FemaleAge5To9,TotalAge10To14,MaleAge10To14,FemaleAge10To14,TotalAge15To19,MaleAge15To19,FemaleAge15To19,TotalAge20To24,MaleAge20To24,FemaleAge20To24,TotalAge25To29,MaleAge25To29,FemaleAge25To29,TotalAge30To34,MaleAge30To34,FemaleAge30To34,TotalAge35To39,MaleAge35To39,FemaleAge35To39,TotalAge40To44,MaleAge40To44,FemaleAge40To44,TotalAge45To49,MaleAge45To49,FemaleAge45To49,TotalAge50To54,MaleAge50To54,FemaleAge50To54,TotalAge55To59,MaleAge55To59,FemaleAge55To59,TotalAge60To64,MaleAge60To64,FemaleAge60To64,TotalAge65To69,MaleAge65To69,FemaleAge65To69,TotalAge70To74,MaleAge70To74,FemaleAge70To74,TotalAge75To79,MaleAge75To79,FemaleAge75To79,TotalAge80To84,MaleAge80To84,FemaleAge80To84,TotalAge85AndOver,MaleAge85AndOver,FemaleAge85AndOver,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,Total16AndOver,LFPRate16AndOver,EmpRatio16AndOver,UnempRate16AndOver,TotalAge16To19,LFPRateAge16To19,EmpRatioAge16To19,UnempRateAge16To19,TotalAge20To24.1,LFPRateAge20To24,EmpRatioAge20To24,UnempRateAge20To24,TotalAge25To29.1,LFPRateAge25To29,EmpRatioAge25To29,UnempRateAge25To29,TotalAge30To34.1,LFPRateAge30To34,EmpRatioAge30To34,UnempRateAge30To34,TotalAge35To44,LFPRateAge35To44,EmpRatioAge35To44,UnempRateAge35To44,TotalAge45To54,LFPRateAge45To54,EmpRatioAge45To54,UnempRateAge45To54,TotalAge55To59.1,LFPRateAge55To59,EmpRatioAge55To59,UnempRateAge55To59,TotalAge60To64.1,LFPRateAge60To64,EmpRatioAge60To64,UnempRateAge60To64,TotalAge65To74,LFPRateAge65To74,EmpRatioAge65To74,UnempRateAge65To74,TotalAge75AndOver,LFPRateAge75AndOver,EmpRatioAge75AndOver,UnempRateAge75AndOver,TotalWhite,LFPRateWhite,EmpRatioWhite,UnempRateWhite,TotalBlack,LFPRateBlack,EmpRatioBlack,UnempRateBlack,TotalNative,LFPRateNative,EmpRatioNative,UnempRateNative,TotalAsian,LFPRateAsian,EmpRatioAsian,UnempRateAsian,TotalPacificIslander,LFPRatePacificIslander,EmpRatioPacificIslander,UnempRatePacificIslander,TotalOtherRace,LFPRateOtherRace,EmpRatioOtherRace,UnempRateOtherRace,Total2Plus,LFPRate2Plus,EmpRatio2Plus,UnempRate2Plus,TotalHispanic,LFPRateHispanic,EmpRatioHispanic,UnempRateHispanic,TotalWhiteNonHispanic,LFPRateWhiteNonHispanic,EmpRatioWhiteNonHispanic,UnempRateWhiteNonHispanic,Total20To64,LFPRate20To64,EmpRatio20To64,UnempRate20To64,Total20To64Male,LFPRate20To64Male,EmpRatio20To64Male,UnempRate20To64Male,Total20To64Female,LFPRate20To64Female,EmpRatio20To64Female,UnempRate20To64Female,Total20To64FemaleChildrenUnder18,LFPRate20To64FemaleChildrenUnder18,EmpRatio20To64FemaleChildrenUnder18,UnempRate20To64FemaleChildrenUnder18,Total20To64FemaleChildrenUnder6,LFPRate20To64FemaleChildrenUnder6,EmpRatio20To64FemaleChildrenUnder6,UnempRate20To64FemaleChildrenUnder6,Total20To64FemaleChildrenUnder6And6To17,LFPRate20To64FemaleChildrenUnder6And6To17,EmpRatio20To64FemaleChildrenUnder6And6To17,UnempRate20To64FemaleChildrenUnder6And6To17,Total20To64FemaleChildren6To17,LFPRate20To64FemaleChildren6To17,EmpRatio20To64FemaleChildren6To17,UnempRate20To64FemaleChildren6To17,TotalBPL,LFPRateBPL,EmpRatioBPL,UnempRateBPL,TotalAPL,LFPRateAPL,EmpRatioAPL,UnempRateAPL,TotalDisabled,LFPRateDisabled,EmpRatioDisabled,UnempRateDisabled,TotalEdu25To64,LFPRateEdu25To64,EmpRatioEdu25To64,UnempRateEdu25To64,TotalEdu25To64LessHS,LFPRateEdu25To64LessHS,EmpRatioEdu25To64LessHS,UnempRateEdu25To64LessHS,TotalEdu25To64HS,LFPRateEdu25To64HS,EmpRatioEdu25To64HS,UnempRateEdu25To64HS,TotalEdu25To64SomeCollege,LFPRateEdu25To64SomeCollege,EmpRatioEdu25To64SomeCollege,UnempRateEdu25To64SomeCollege,TotalEdu25To64Bachelors,LFPRateEdu25To64Bachelors,EmpRatioEdu25To64Bachelors,UnempRateEdu25To64Bachelors
0,1,1400000US13007960200,1.300796e+10,960200.0,Baker County,2017.0,517.0,311.0,253.0,206.0,10.6,1.6,0.0,24.3,1.4,0.0,0.0,3.4,13.0,9.3,11.5,18.4,20.7,7.7,9.5,40.3,12.0,12.5,12.3,11.2,19.0,31.5,32.4,0.0,12.8,19.6,21.3,2.4,0.0,0.0,0.0,0.0,6.6,10.9,4.7,0.0,4.1,6.8,8.3,0.0,45486.0,54926.0,52574.0,28106.0,58316.0,80776.0,NaN,24407.0,1135.0,523.0,612.0,36.0,24.0,12.0,33.0,0.0,33.0,76.0,50.0,26.0,89.0,33.0,56.0,51.0,34.0,17.0,48.0,8.0,40.0,60.0,21.0,39.0,81.0,56.0,25.0,40.0,13.0,27.0,57.0,43.0,14.0,28.0,15.0,13.0,83.0,11.0,72.0,147.0,86.0,61.0,151.0,61.0,90.0,65.0,27.0,38.0,75.0,34.0,41.0,0.0,0.0,0.0,15.0,7.0,8.0,1050.0,771.0,257.0,6.0,0.0,16.0,0.0,0.0,0.0,0.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,957.0,50.3,49.6,1.2,56.0,0.0,0.0,NaN,51.0,82.4,82.4,0.0,48.0,93.8,93.8,0.0,60.0,85.0,76.7,9.8,121.0,75.2,74.4,1.1,85.0,76.5,76.5,0.0,83.0,89.2,89.2,0.0,147.0,38.8,38.8,0.0,216.0,19.9,19.9,0.0,90.0,14.4,14.4,0.0,695.0,52.4,52.2,0.3,240.0,39.6,37.5,5.3,6.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,16.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,67.0,67.2,67.2,0.0,628.0,50.8,50.6,0.3,595.0,71.4,70.4,1.4,287.0,72.8,72.8,0.0,308.0,70.1,68.2,2.8,73.0,53.4,46.6,12.8,9.0,0.0,0.0,NaN,21.0,100.0,76.2,23.8,43.0,41.9,41.9,0.0,70.0,8.6,0.0,100.0,525.0,79.8,79.8,0.0,109.0,58.7,57.8,1.6,544.0,70.4,69.3,1.6,40.0,12.5,0.0,100.0,248.0,69.4,69.0,0.6,214.0,76.6,76.6,0.0,42.0,100.0,100.0,0.0
1,2,1400000US13007960100,1.300796e+10,960100.0,Baker County,2017.0,804.0,528.0,345.0,276.0,21.9,11.0,10.1,42.8,6.7,7.4,4.9,5.4,6.8,3.0,4.6,14.1,7.6,10.4,7.0,3.3,12.9,12.1,13.3,13.4,24.1,30.5,28.4,13.4,7.0,10.6,16.2,0.0,11.2,12.3,11.3,7.6,1.2,1.9,2.9,0.0,0.5,0.8,1.2,0.0,43594.0,52614.0,54844.0,17083.0,48346.0,57024.0,NaN,31070.0,2116.0,1024.0,1092.0,91.0,41.0,50.0,120.0,53.0,67.0,156.0,96.0,60.0,141.0,94.0,47.0,150.0,32.0,118.0,190.0,142.0,48.0,94.0,60.0,34.0,84.0,38.0,46.0,122.0,48.0,74.0,160.0,94.0,66.0,223.0,119.0,104.0,119.0,33.0,86.0,153.0,63.0,90.0,106.0,49.0,57.0,99.0,44.0,55.0,27.0,11.0,16.0,55.0,7.0,48.0,26.0,0.0,26.0,2027.0,924.0,1085.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,89.0,37.0,7.0,0.0,0.0,0.0,45.0,0.0,0.0,0.0,1722.0,48.7,47.1,3.2,114.0,16.7,14.9,10.5,150.0,52.0,52.0,0.0,190.0,55.8,55.8,0.0,94.0,78.7,67.0,14.9,206.0,57.8,57.8,0.0,383.0,66.8,65.3,2.3,119.0,80.7,73.9,8.3,153.0,42.5,42.5,0.0,205.0,12.2,12.2,0.0,108.0,0.0,0.0,NaN,817.0,59.6,58.0,2.7,852.0,37.3,35.7,4.4,0.0,NaN,NaN,NaN,8.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,45.0,55.6,55.6,0.0,0.0,NaN,NaN,NaN,64.0,68.8,68.8,0.0,798.0,58.6,57.0,2.8,1295.0,61.3,59.4,3.1,629.0,57.7,55.0,4.7,666.0,64.7,63.5,1.9,216.0,67.6,67.6,0.0,89.0,42.7,42.7,0.0,21.0,76.2,76.2,0.0,106.0,86.8,86.8,0.0,277.0,16.2,16.2,0.0,1018.0,73.6,71.1,3.3,241.0,28.2,23.7,16.2,1145.0,62.5,60.3,3.5,295.0,42.7,42.7,0.0,383.0,65.5,61.9,5.6,331.0,71.9,68.6,4.6,136.0,74.3,74.3,0.0
2,3,1400000US13321950600,1.332195e+10,950600.0,Worth County,2017.0,854.0,653.0,591.0,201.0,4.1,0.8,0.8,14.9,4.8,4.0,3.0,7.5,16.0,15.5,16.2,17.9,14.6,9.2,10.2,32.3,16.4,15.8,16.6,18.4,23.1,29.4,29.8,2.5,11.4,12.9,12.4,6.5,4.9,6.4,5.8,0.0,4.0,5.2,4.2,0.0,0.7,0.9,1.0,0.0,38649.0,51969.0,51156.0,27120.0,54027.0,61804.0,NaN,28761.0,2264.0,1369.0,895.0,114.0,84.0,30.0,158.0,153.0,5.0,138.0,107.0,31.0,86.0,59.0,27.0,125.0,57.0,68.0,109.0,63.0,46.0,138.0,87.0,51.0,116.0,79.0,37.0,149.0,90.0,59.0,135.0,50.0,85.0,158.0,121.0,37.0,223.0,77.0,146.0,156.0,72.0,84.0,232.0,156.0,76.0,126.0,68.0,58.0,70.0,35.0,35.0,21.0,11.0,10.0,10.0,0.0,10.0,2030.0,1745.0,285.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,234.0,155.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,1818.0,58.7,52.9,9.6,50.0,24.0,0.0,100.0,125.0,100.0,68.8,28.3,109.0,91.7,91.7,0.0,138.0,50.0,35.5,29.0,265.0,80.8,78.1,3.3,293.0,58.7,56.0,4.7,223.0,70.0,63.2,9.6,156.0,52.6,52.6,0.0,358.0,37.2,35.5,4.5,101.0,5.0,5.0,0.0,1483.0,60.7,54.8,9.3,280.0,54.6,47.9,12.4,55.0,27.3,27.3,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,94.0,57.4,57.4,0.0,1444.0,59.6,53.5,9.7,1309.0,70.1,63.3,9.2,696.0,80.5,74.3,6.8,613.0,58.4,50.9,12.8,166.0,59.0,47.0,20.4,14.0,100.0,100.0,0.0,37.0,32.4,32.4,0.0,115.0,62.6,45.2,27.8,181.0,60.2,37.6,34.6,1128.0,71.7,67.5,5.9,245.0,51.8,42.0,18.9,1184.0,67.0,62.8,6.3,205.0,59.5,59.5,0.0,430.0,65.1,58.6,10.0,450.0,66.7,61.8,7.3,99.0,91.9,91.9,0.0
3,4,1400000US13321950500,1.332195e+10,950500.0,Worth County,2017.0,1674.0,1135.0,642.0,539.0,18.2,17.8,1.9,18.9,6.5,2.6,0.0,14.8,10.8,6.5,7.5,21.7,12.4,11.5,11.4,14.3,14.8,18.3,9.7,6.7,17.7,21.2,32.9,9.3,13.8,13.6,21.8,14.3,3.8,5.6,10.0,0.0,1.5,2.2,3.9,0.0,0.4,0.6,1.1,0.0,36458.0,44208.0,66090.0,23059.0,44636.0,50183.0,NaN,32214.0,4027.0,1984.0,2043.0,197.0,72.0,125.0,250.0,152.0,98.0,120.0,41.0,79.0,300.0,218.0,82.0,424.0,222.0,202.0,201.0,81.0,120.0,212.0,64.0,148.0,91.0,31.0,60.0,351.0,178.0,173.0,174.0,81.0,93.0,414.0,227.0,187.0,286.0,163.0,123.0,306.0,174.0,132.0,156.0,61.0,95.0,227.0,83.0,144.0,119.0,59.0,60.0,84.0,48.0,36.0,115.0,29.0,86.0,3968.0,1842.0,1906.0,0.0,32.0,0.0,76.0,112.0,11.0,101.0,59.0,32.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,3432.0,56.8,52.6,7.4,272.0,37.9,37.9,0.0,424.0,72.2,57.8,19.9,201.0,67.2,61.7,8.1,212.0,56.1,32.5,42.0,442.0,77.8,74.2,4.7,588.0,78.7,77.7,1.3,286.0,65.4,65.4,0.0,306.0,58.5,58.5,0.0,383.0,27.7,27.7,0.0,318.0,2.2,2.2,0.0,1655.0,53.4,51.7,3.2,1646.0,58.0,50.9,12.2,0.0,NaN,NaN,NaN,32.0,71.9,71.9,0.0,0.0,NaN,NaN,NaN,71.0,100.0,100.0,0.0,28.0,60.7,60.7,0.0,59.0,89.8,89.8,0.0,1623.0,52.9,51.1,3.3,2459.0,70.5,64.6,8.3,1221.0,79.2,69.7,12.0,1238.0,61.9,59.6,3.7,408.0,66.7,64.0,4.0,79.0,88.6,88.6,0.0,37.0,100.0,70.3,29.7,292.0,56.5,56.5,0.0,458.0,33.8,27.9,17.4,1971.0,80.1,74.1,7.4,283.0,21.6,21.6,0.0,2035.0,70.1,66.0,5.8,317.0,47.6,31.9,33.1,974.0,63.4,62.8,1.0,569.0,86.8,84.9,2.2,175.0,93.7,84.6,9.8
4,5,1400000US13321950400,1.332195e+10,950400.0,Worth County,2017.0,1573.0,1163.0,949.0,410.0,7.0,1.2,1.3,23.4,7.9,7.1,3.3,10.2,15.9,14.4,10.4,20.5,10.2,8.9,8.3,13.9,17.5,18.4,21.2,14.9,16.7,18.1,18.8,13.4,12.8,16.3,18.9,1.7,6.5,8.1,8.6,2.0,3.9,5.3,6.5,0.0,1.7,2.2,2.7,0.0,43720.0,50096.0,58359.0,24076.0,59481.0,70036.0,NaN,29068.0,4393.0,2168.0,2225.0,274.0,117.0,157.0,240.0,146.0,94.0,382.0,183.0,199.0,370.0,154.0,216.0,243.0,136.0,107.0,194.0,106.0,88.0,272.0,159.0,113.0,244.0,70.0,174.0,251.0,185.0,66.0,278.0,108.0,170.0,249.0,132.0,117.0,398.0,251.0,147.0,252.0,92.0,160.0,201.0,113.0,88.0,212.0,98.0,114.0,152.0,60.0,92.0,78.0,22.0,56.0,103.0,36.0,67.0,4341.0,3360.0,923.0,0.0,16.0,0.0,0.0,42.0,0.0,42.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3389.0,55.4,50.2,9.4,262.0,40.5,27.5,32.1,243.0,80.2,79.0,1.5,194.0,64.4,51.0,20.8,272.0,71.3,64.3,9.8,495.0,77.8,75.2,3.4,527.0,80.1,78.0,2.6,398.0,68.1,57.5,15.5,252.0,50.0,38.5,23.0,413.0,9.0,9.0,0.0,333.0,5.4,5.4,0.0,2632.0,59.2,54.1,8.5,699.0,45.8,39.5,13.8,0.0,NaN,NaN,NaN,16.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,42.0,4.8,4.8,0.0,0.0,NaN,NaN,NaN,2632.0,59.2,54.1,8.5,2381.0,72.2,66.1,8.3,1239.0,81.8,75.7,7.5,1142.0,61.6,55.8,9.5,412.0,75.0,64.1,14.6,47.0,72.3,61.7,14.7,75.0,94.7,69.3,26.8,290.0,70.3,63.1,10.3,456.0,52.4,44.1,15.9,1925.0,76.8,71.4,7.1,485.0,36.1,22.9,36.6,2138.0,71.2,64.7,9.2,438.0,56.8,49.5,12.9,748.0,72.9,65.5,10.1,705.0,76.3,70.5,7.6,247.0,77.3,72.5,6.3

In [234]:
def containsdecimal(num):
    if not math.isnan(num):
        word = str(num).split(".")
        return word[1] == '1'
    else:
        return True

In [223]:
tract_summary = construct_summary(df_tract)

In [229]:
tract_summary['Datatype'][3] == 'float64'

True

In [225]:
tract_summary

                                            Datatype  Nulls  Uniques
TractID                                        int64  False     True
GEO.id                                        object  False    False
GEO.id2                                      float64  False    False
Tract                                        float64  False    False
County                                        object  False    False
Year                                         float64  False    False
HTotal                                       float64  False    False
FTotal                                       float64  False    False
MTotal                                       float64  False    False
NfTotal                                      float64  False    False
HIncomeLessThan10k                           float64  False    False
FIncomeLessThan10k                           float64  False    False
MIncomeLessThan10k                           float64  False    False
NfIncomeLessThan10k                          float64  False    False
HIncome10kTo14999                            float64  False    False
FIncome10kTo14999                            float64  False    False
MIncome10kTo14999                            float64  False    False
NfIncome10kTo14999                           float64  False    False
HIncome15kTo24999                            float64  False    False
FIncome15kTo24999                            float64  False    False
MIncome15kTo24999                            float64  False    False
NfIncome15kTo24999                           float64  False    False
HIncome25kTo34999                            float64  False    False
FIncome25kTo34999                            float64  False    False
MIncome25kTo34999                            float64  False    False
NfIncome25kTo34999                           float64  False    False
HIncome35kTo49999                            float64  False    False
FIncome35kTo49999                            float64  False    False
MIncome35kTo49999                            float64  False    False
NfIncome35kTo49999                           float64  False    False
HIncome50kTo74999                            float64  False    False
FIncome50kTo74999                            float64  False    False
MIncome50kTo74999                            float64  False    False
NfIncome50kTo74999                           float64  False    False
HIncome75kTo99999                            float64  False    False
FIncome75kTo99999                            float64  False    False
MIncome75kTo99999                            float64  False    False
NfIncome75kTo99999                           float64  False    False
HIncome100kTo149999                          float64  False    False
FIncome100kTo149999                          float64  False    False
MIncome100kTo149999                          float64  False    False
NfIncome100kTo149999                         float64  False    False
HIncome150kTo199999                          float64  False    False
FIncome150kTo199999                          float64  False    False
MIncome150kTo199999                          float64  False    False
NfIncome150kTo199999                         float64  False    False
HIncome200kOrMore                            float64  False    False
FIncome200kOrMore                            float64  False    False
MIncome200kOrMore                            float64  False    False
NfIncome200kOrMore                           float64  False    False
HIncomeMedian                                float64  False    False
FIncomeMedian                                float64  False    False
MIncomeMedian                                float64   True    False
NfIncomeMedian                               float64   True    False
HIncomeMean                                  float64  False    False
FIncomeMean                                  float64  False    False
MIncomeMean                                  float64   True     True
NfIncomeMean                                 float64  False    False
TotalPopulation                              float64  False    False
MaleTotal                                    float64  False    False
FemaleTotal                                  float64  False    False
TotalAgeUnder5                               float64  False    False
MaleAgeUnder5                                float64  False    False
FemaleAgeUnder5                              float64  False    False
TotalAge5To9                                 float64  False    False
MaleAge5To9                                  float64  False    False
FemaleAge5To9                                float64  False    False
TotalAge10To14                               float64  False    False
MaleAge10To14                                float64  False    False
FemaleAge10To14                              float64  False    False
TotalAge15To19                               float64  False    False
MaleAge15To19                                float64  False    False
FemaleAge15To19                              float64  False    False
TotalAge20To24                               float64  False    False
MaleAge20To24                                float64  False    False
FemaleAge20To24                              float64  False    False
TotalAge25To29                               float64  False    False
MaleAge25To29                                float64  False    False
FemaleAge25To29                              float64  False    False
TotalAge30To34                               float64  False    False
MaleAge30To34                                float64  False    False
FemaleAge30To34                              float64  False    False
TotalAge35To39                               float64  False    False
MaleAge35To39                                float64  False    False
FemaleAge35To39                              float64  False    False
TotalAge40To44                               float64  False    False
MaleAge40To44                                float64  False    False
FemaleAge40To44                              float64  False    False
TotalAge45To49                               float64  False    False
MaleAge45To49                                float64  False    False
FemaleAge45To49                              float64  False    False
TotalAge50To54                               float64  False    False
MaleAge50To54                                float64  False    False
FemaleAge50To54                              float64  False    False
TotalAge55To59                               float64  False    False
MaleAge55To59                                float64  False    False
FemaleAge55To59                              float64  False    False
TotalAge60To64                               float64  False    False
MaleAge60To64                                float64  False    False
FemaleAge60To64                              float64  False    False
TotalAge65To69                               float64  False    False
MaleAge65To69                                float64  False    False
FemaleAge65To69                              float64  False    False
TotalAge70To74                               float64  False    False
MaleAge70To74                                float64  False    False
FemaleAge70To74                              float64  False    False
TotalAge75To79                               float64  False    False
MaleAge75To79                                float64  False    False
FemaleAge75To79                              float64  False    False
TotalAge80To84                               float64  False    False
MaleAge80To84                                float64  False    False
FemaleAge80To84                              float64  False    False
TotalAge85AndOver                            float64  False    False
MaleAge85AndOver                             float64  False    False
FemaleAge85AndOver                           float64  False    False
NonHispanic                                  float64  False    False
NonHispanicWhite                             float64  False    False
NonHispanicBlack                             float64  False    False
NonHispanicNative                            float64  False    False
NonHispanicAsian                             float64  False    False
NonHispanicPacificIslander                   float64  False    False
NonHispanicOtherRace                         float64  False    False
NonHispanic2Plus                             float64  False    False
NonHispanic2PlusIncOther                     float64  False    False
NonHispanic2PlusExcOther                     float64  False    False
Hispanic                                     float64  False    False
HispanicWhite                                float64  False    False
HispanicBlack                                float64  False    False
HispanicNative                               float64  False    False
HispanicAsian                                float64  False    False
HispanicPacificIslander                      float64  False    False
HispanicOtherRace                            float64  False    False
Hispanic2Plus                                float64  False    False
Hispanic2PlusIncOther                        float64  False    False
Hispanic2PlusExcOther                        float64  False    False
Total16AndOver                               float64  False    False
LFPRate16AndOver                             float64   True    False
EmpRatio16AndOver                            float64   True    False
UnempRate16AndOver                           float64  False    False
TotalAge16To19                               float64  False    False
LFPRateAge16To19                             float64   True    False
EmpRatioAge16To19                            float64   True    False
UnempRateAge16To19                           float64   True    False
TotalAge20To24.1                             float64  False    False
LFPRateAge20To24                             float64   True    False
EmpRatioAge20To24                            float64   True    False
UnempRateAge20To24                           float64  False    False
TotalAge25To29.1                             float64   True    False
LFPRateAge25To29                             float64   True    False
EmpRatioAge25To29                            float64   True    False
UnempRateAge25To29                           float64   True    False
TotalAge30To34.1                             float64   True    False
LFPRateAge30To34                             float64   True    False
EmpRatioAge30To34                            float64   True    False
UnempRateAge30To34                           float64   True    False
TotalAge35To44                               float64   True    False
LFPRateAge35To44                             float64   True    False
EmpRatioAge35To44                            float64   True    False
UnempRateAge35To44                           float64   True    False
TotalAge45To54                               float64  False    False
LFPRateAge45To54                             float64   True    False
EmpRatioAge45To54                            float64   True    False
UnempRateAge45To54                           float64  False    False
TotalAge55To59.1                             float64   True    False
LFPRateAge55To59                             float64   True    False
EmpRatioAge55To59                            float64   True    False
UnempRateAge55To59                           float64   True    False
TotalAge60To64.1                             float64   True    False
LFPRateAge60To64                             float64   True    False
EmpRatioAge60To64                            float64   True    False
UnempRateAge60To64                           float64   True    False
TotalAge65To74                               float64  False    False
LFPRateAge65To74                             float64   True    False
EmpRatioAge65To74                            float64   True    False
UnempRateAge65To74                           float64   True    False
TotalAge75AndOver                            float64  False    False
LFPRateAge75AndOver                          float64   True    False
EmpRatioAge75AndOver                         float64   True    False
UnempRateAge75AndOver                        float64   True    False
TotalWhite                                   float64   True    False
LFPRateWhite                                 float64   True    False
EmpRatioWhite                                float64   True    False
UnempRateWhite                               float64   True    False
TotalBlack                                   float64   True    False
LFPRateBlack                                 float64   True    False
EmpRatioBlack                                float64   True    False
UnempRateBlack                               float64   True    False
TotalNative                                  float64   True    False
LFPRateNative                                float64   True    False
EmpRatioNative                               float64   True    False
UnempRateNative                              float64   True    False
TotalAsian                                   float64   True    False
LFPRateAsian                                 float64   True    False
EmpRatioAsian                                float64   True    False
UnempRateAsian                               float64   True    False
TotalPacificIslander                         float64   True    False
LFPRatePacificIslander                       float64   True    False
EmpRatioPacificIslander                      float64   True    False
UnempRatePacificIslander                     float64   True    False
TotalOtherRace                               float64   True    False
LFPRateOtherRace                             float64   True    False
EmpRatioOtherRace                            float64   True    False
UnempRateOtherRace                           float64   True    False
Total2Plus                                   float64  False    False
LFPRate2Plus                                 float64   True    False
EmpRatio2Plus                                float64   True    False
UnempRate2Plus                               float64   True    False
TotalHispanic                                float64  False    False
LFPRateHispanic                              float64   True    False
EmpRatioHispanic                             float64   True    False
UnempRateHispanic                            float64   True    False
TotalWhiteNonHispanic                        float64  False    False
LFPRateWhiteNonHispanic                      float64   True    False
EmpRatioWhiteNonHispanic                     float64   True    False
UnempRateWhiteNonHispanic                    float64   True    False
Total20To64                                  float64  False    False
LFPRate20To64                                float64   True    False
EmpRatio20To64                               float64   True    False
UnempRate20To64                              float64  False    False
Total20To64Male                              float64   True    False
LFPRate20To64Male                            float64   True    False
EmpRatio20To64Male                           float64   True    False
UnempRate20To64Male                          float64   True    False
Total20To64Female                            float64   True    False
LFPRate20To64Female                          float64   True    False
EmpRatio20To64Female                         float64   True    False
UnempRate20To64Female                        float64   True    False
Total20To64FemaleChildrenUnder18             float64   True    False
LFPRate20To64FemaleChildrenUnder18           float64   True    False
EmpRatio20To64FemaleChildrenUnder18          float64   True    False
UnempRate20To64FemaleChildrenUnder18         float64   True    False
Total20To64FemaleChildrenUnder6              float64   True    False
LFPRate20To64FemaleChildrenUnder6            float64   True    False
EmpRatio20To64FemaleChildrenUnder6           float64   True    False
UnempRate20To64FemaleChildrenUnder6          float64   True    False
Total20To64FemaleChildrenUnder6And6To17      float64   True    False
LFPRate20To64FemaleChildrenUnder6And6To17    float64   True    False
EmpRatio20To64FemaleChildrenUnder6And6To17   float64   True    False
UnempRate20To64FemaleChildrenUnder6And6To17  float64   True    False
Total20To64FemaleChildren6To17               float64   True    False
LFPRate20To64FemaleChildren6To17             float64   True    False
EmpRatio20To64FemaleChildren6To17            float64   True    False
UnempRate20To64FemaleChildren6To17           float64   True    False
TotalBPL                                     float64   True    False
LFPRateBPL                                   float64   True    False
EmpRatioBPL                                  float64   True    False
UnempRateBPL                                 float64   True    False
TotalAPL                                     float64   True    False
LFPRateAPL                                   float64   True    False
EmpRatioAPL                                  float64   True    False
UnempRateAPL                                 float64   True    False
TotalDisabled                                float64   True    False
LFPRateDisabled                              float64   True    False
EmpRatioDisabled                             float64   True    False
UnempRateDisabled                            float64   True    False
TotalEdu25To64                               float64  False    False
LFPRateEdu25To64                             float64   True    False
EmpRatioEdu25To64                            float64   True    False
UnempRateEdu25To64                           float64  False    False
TotalEdu25To64LessHS                         float64   True    False
LFPRateEdu25To64LessHS                       float64   True    False
EmpRatioEdu25To64LessHS                      float64   True    False
UnempRateEdu25To64LessHS                     float64   True    False
TotalEdu25To64HS                             float64   True    False
LFPRateEdu25To64HS                           float64   True    False
EmpRatioEdu25To64HS                          float64   True    False
UnempRateEdu25To64HS                         float64   True    False
TotalEdu25To64SomeCollege                    float64   True    False
LFPRateEdu25To64SomeCollege                  float64   True    False
EmpRatioEdu25To64SomeCollege                 float64   True    False
UnempRateEdu25To64SomeCollege                float64   True    False
TotalEdu25To64Bachelors                      float64   True    False
LFPRateEdu25To64Bachelors                    float64   True    False
EmpRatioEdu25To64Bachelors                   float64   True    False
UnempRateEdu25To64Bachelors                  float64   True    False

In [233]:
df_tract['MIncomeMedian']

0       52574.0
1       54844.0
2       51156.0
3       66090.0
4       58359.0
5       73957.0
6       47849.0
7       43250.0
8       24907.0
9       67045.0
10      52262.0
11     112026.0
12      90182.0
13      59688.0
14     115677.0
15      91325.0
16      76523.0
17      51875.0
18      79428.0
19      30571.0
20          NaN
21      38274.0
22      68056.0
23      51786.0
24      45865.0
25      64375.0
26      64485.0
27      59050.0
28      51667.0
29      55000.0
30      62188.0
31      35950.0
32      68321.0
33      41614.0
34      62679.0
35      44453.0
36      64605.0
37     107262.0
38      63981.0
39     108125.0
40      38750.0
41      47949.0
42      54808.0
43      51321.0
44      57841.0
45      50774.0
46      60774.0
47      56654.0
48      69631.0
49      45208.0
50      42813.0
51      24732.0
52      63000.0
53      52042.0
54     101397.0
55      88093.0
56      58726.0
57     120083.0
58      73903.0
59      82738.0
60      49531.0
61      72429.0
62      31176.0
63          NaN
64      37917.0
65      54038.0
66      63438.0
67      45417.0
68      60313.0
69      61964.0
70      56125.0
71      49259.0
72      49803.0
73      55870.0
74      37533.0
75      84583.0
76      39500.0
77      64803.0
78      42639.0
79      66442.0
80     103400.0
81      61417.0
82     100865.0
83      42933.0
84      63466.0
85      48424.0
86          NaN
87          NaN
88          NaN
89          NaN
90          NaN
91          NaN
92          NaN
93          NaN
94          NaN
95          NaN
96          NaN
97          NaN
98          NaN
99          NaN
100         NaN
101         NaN
102         NaN
103         NaN
104         NaN
105         NaN
106         NaN
107         NaN
108         NaN
109     51000.0
110     46654.0
111         NaN
112         NaN
113         NaN
114     63173.0
115         NaN
116     55234.0
117         NaN
118         NaN
119         NaN
120         NaN
121     40313.0
122     72685.0
123         NaN
124         NaN
125         NaN
126         NaN
127         NaN
128         NaN
129     67344.0
130     66917.0
131     51641.0
132     54047.0
133     52763.0
134     68794.0
135     53850.0
136     44643.0
137     18750.0
138     63239.0
139     49173.0
140     85668.0
141     75905.0
142     56027.0
143    100625.0
144     70341.0
145     80341.0
146     53750.0
147     72415.0
148     26688.0
149     56667.0
         ...
194     65125.0
195     51765.0
196     48125.0
197     57500.0
198     70809.0
199     35547.0
200     80536.0
201     52500.0
202     56190.0
203     40955.0
204     68438.0
205     38349.0
206     58250.0
207     38068.0
208     49000.0
209    103276.0
210     57365.0
211     89333.0
212     41473.0
213     41339.0
214     51500.0
215     58529.0
216     54583.0
217     51250.0
218     51520.0
219     53696.0
220     69025.0
221     61597.0
222     48158.0
223     50833.0
224     62333.0
225     57644.0
226     81944.0
227     73370.0
228     53661.0
229     97932.0
230     71857.0
231     79255.0
232     61488.0
233     69209.0
234     30125.0
235     46538.0
236     30625.0
237     64219.0
238     60385.0
239     53279.0
240     55673.0
241     67125.0
242     37411.0
243     80250.0
244     53144.0
245     55491.0
246     42409.0
247     68534.0
248     38157.0
249     41386.0
250     49676.0
251     34592.0
252    104013.0
253     75563.0
254     95645.0
255     41953.0
256     44167.0
257     40250.0
258     58869.0
259     57083.0
260     50726.0
261     52214.0
262     55345.0
263     67614.0
264     61050.0
265     48359.0
266     50809.0
267     76250.0
268     52083.0
269     84020.0
270     69107.0
271     52174.0
272     97908.0
273     68194.0
274     76087.0
275     59750.0
276     64110.0
277     31688.0
278     28750.0
279     41325.0
280     63125.0
281     49500.0
282     50611.0
283     56179.0
284     71518.0
285     36083.0
286     78718.0
287     51861.0
288     56250.0
289     46225.0
290     63878.0
291     37342.0
292     35875.0
293     49750.0
294     40573.0
295    102300.0
296     74938.0
297     92440.0
298     45278.0
299     41360.0
300     40500.0
301     34330.0
302     51384.0
303     49013.0
304     51838.0
305     56094.0
306     69770.0
307     50972.0
308     50375.0
309     47865.0
310     56979.0
311     59018.0
312     87786.0
313     65429.0
314     48917.0
315     96635.0
316     80809.0
317     73085.0
318     71779.0
319     73710.0
320     38841.0
321     42587.0
322     39036.0
323     57083.0
324     50208.0
325     49500.0
326     53882.0
327     65875.0
328     38438.0
329     76321.0
330     49395.0
331     51512.0
332     53603.0
333     62321.0
334     45375.0
335     44432.0
336     53153.0
337     39904.0
338    101389.0
339     77115.0
340     95972.0
341     48411.0
342     39074.0
343     39730.0
Name: MIncomeMedian, Length: 344, dtype: float64

In [235]:
tmp = {}
cols = list(df_tract)
for i in range(len(cols)):
    col = cols[i]
    isfloat = tract_summary['Datatype'][i] == 'float64'
    if isfloat:
        try:
            boo = df_tract[col].apply(containsdecimal).any()
            tmp[col] = boo
        except:
            print(col)

In [236]:
tmp

{'GEO.id2': False,
 'Tract': False,
 'Year': False,
 'HTotal': False,
 'FTotal': False,
 'MTotal': False,
 'NfTotal': False,
 'HIncomeLessThan10k': True,
 'FIncomeLessThan10k': True,
 'MIncomeLessThan10k': True,
 'NfIncomeLessThan10k': True,
 'HIncome10kTo14999': True,
 'FIncome10kTo14999': True,
 'MIncome10kTo14999': True,
 'NfIncome10kTo14999': True,
 'HIncome15kTo24999': True,
 'FIncome15kTo24999': True,
 'MIncome15kTo24999': True,
 'NfIncome15kTo24999': True,
 'HIncome25kTo34999': True,
 'FIncome25kTo34999': True,
 'MIncome25kTo34999': True,
 'NfIncome25kTo34999': True,
 'HIncome35kTo49999': True,
 'FIncome35kTo49999': True,
 'MIncome35kTo49999': True,
 'NfIncome35kTo49999': True,
 'HIncome50kTo74999': True,
 'FIncome50kTo74999': True,
 'MIncome50kTo74999': True,
 'NfIncome50kTo74999': True,
 'HIncome75kTo99999': True,
 'FIncome75kTo99999': True,
 'MIncome75kTo99999': True,
 'NfIncome75kTo99999': True,
 'HIncome100kTo149999': True,
 'FIncome100kTo149999': True,
 'MIncome100kTo149999': True,
 'NfIncome100kTo149999': True,
 'HIncome150kTo199999': True,
 'FIncome150kTo199999': True,
 'MIncome150kTo199999': True,
 'NfIncome150kTo199999': True,
 'HIncome200kOrMore': True,
 'FIncome200kOrMore': True,
 'MIncome200kOrMore': True,
 'NfIncome200kOrMore': True,
 'HIncomeMedian': False,
 'FIncomeMedian': False,
 'MIncomeMedian': True,
 'NfIncomeMedian': True,
 'HIncomeMean': False,
 'FIncomeMean': False,
 'MIncomeMean': True,
 'NfIncomeMean': False,
 'TotalPopulation': False,
 'MaleTotal': False,
 'FemaleTotal': False,
 'TotalAgeUnder5': True,
 'MaleAgeUnder5': True,
 'FemaleAgeUnder5': True,
 'TotalAge5To9': True,
 'MaleAge5To9': True,
 'FemaleAge5To9': True,
 'TotalAge10To14': True,
 'MaleAge10To14': True,
 'FemaleAge10To14': True,
 'TotalAge15To19': True,
 'MaleAge15To19': True,
 'FemaleAge15To19': True,
 'TotalAge20To24': True,
 'MaleAge20To24': True,
 'FemaleAge20To24': True,
 'TotalAge25To29': True,
 'MaleAge25To29': True,
 'FemaleAge25To29': True,
 'TotalAge30To34': True,
 'MaleAge30To34': True,
 'FemaleAge30To34': True,
 'TotalAge35To39': True,
 'MaleAge35To39': True,
 'FemaleAge35To39': True,
 'TotalAge40To44': True,
 'MaleAge40To44': True,
 'FemaleAge40To44': True,
 'TotalAge45To49': True,
 'MaleAge45To49': True,
 'FemaleAge45To49': True,
 'TotalAge50To54': True,
 'MaleAge50To54': True,
 'FemaleAge50To54': True,
 'TotalAge55To59': True,
 'MaleAge55To59': True,
 'FemaleAge55To59': True,
 'TotalAge60To64': True,
 'MaleAge60To64': True,
 'FemaleAge60To64': True,
 'TotalAge65To69': True,
 'MaleAge65To69': True,
 'FemaleAge65To69': True,
 'TotalAge70To74': True,
 'MaleAge70To74': True,
 'FemaleAge70To74': True,
 'TotalAge75To79': True,
 'MaleAge75To79': True,
 'FemaleAge75To79': True,
 'TotalAge80To84': True,
 'MaleAge80To84': True,
 'FemaleAge80To84': True,
 'TotalAge85AndOver': True,
 'MaleAge85AndOver': True,
 'FemaleAge85AndOver': True,
 'NonHispanic': False,
 'NonHispanicWhite': False,
 'NonHispanicBlack': False,
 'NonHispanicNative': False,
 'NonHispanicAsian': False,
 'NonHispanicPacificIslander': False,
 'NonHispanicOtherRace': False,
 'NonHispanic2Plus': False,
 'NonHispanic2PlusIncOther': False,
 'NonHispanic2PlusExcOther': False,
 'Hispanic': False,
 'HispanicWhite': False,
 'HispanicBlack': False,
 'HispanicNative': False,
 'HispanicAsian': False,
 'HispanicPacificIslander': False,
 'HispanicOtherRace': False,
 'Hispanic2Plus': False,
 'Hispanic2PlusIncOther': False,
 'Hispanic2PlusExcOther': False,
 'Total16AndOver': False,
 'LFPRate16AndOver': True,
 'EmpRatio16AndOver': True,
 'UnempRate16AndOver': True,
 'TotalAge16To19': False,
 'LFPRateAge16To19': True,
 'EmpRatioAge16To19': True,
 'UnempRateAge16To19': True,
 'TotalAge20To24.1': False,
 'LFPRateAge20To24': True,
 'EmpRatioAge20To24': True,
 'UnempRateAge20To24': True,
 'TotalAge25To29.1': True,
 'LFPRateAge25To29': True,
 'EmpRatioAge25To29': True,
 'UnempRateAge25To29': True,
 'TotalAge30To34.1': True,
 'LFPRateAge30To34': True,
 'EmpRatioAge30To34': True,
 'UnempRateAge30To34': True,
 'TotalAge35To44': True,
 'LFPRateAge35To44': True,
 'EmpRatioAge35To44': True,
 'UnempRateAge35To44': True,
 'TotalAge45To54': False,
 'LFPRateAge45To54': True,
 'EmpRatioAge45To54': True,
 'UnempRateAge45To54': True,
 'TotalAge55To59.1': True,
 'LFPRateAge55To59': True,
 'EmpRatioAge55To59': True,
 'UnempRateAge55To59': True,
 'TotalAge60To64.1': True,
 'LFPRateAge60To64': True,
 'EmpRatioAge60To64': True,
 'UnempRateAge60To64': True,
 'TotalAge65To74': False,
 'LFPRateAge65To74': True,
 'EmpRatioAge65To74': True,
 'UnempRateAge65To74': True,
 'TotalAge75AndOver': False,
 'LFPRateAge75AndOver': True,
 'EmpRatioAge75AndOver': True,
 'UnempRateAge75AndOver': True,
 'TotalWhite': True,
 'LFPRateWhite': True,
 'EmpRatioWhite': True,
 'UnempRateWhite': True,
 'TotalBlack': True,
 'LFPRateBlack': True,
 'EmpRatioBlack': True,
 'UnempRateBlack': True,
 'TotalNative': True,
 'LFPRateNative': True,
 'EmpRatioNative': True,
 'UnempRateNative': True,
 'TotalAsian': True,
 'LFPRateAsian': True,
 'EmpRatioAsian': True,
 'UnempRateAsian': True,
 'TotalPacificIslander': True,
 'LFPRatePacificIslander': True,
 'EmpRatioPacificIslander': True,
 'UnempRatePacificIslander': True,
 'TotalOtherRace': True,
 'LFPRateOtherRace': True,
 'EmpRatioOtherRace': True,
 'UnempRateOtherRace': True,
 'Total2Plus': False,
 'LFPRate2Plus': True,
 'EmpRatio2Plus': True,
 'UnempRate2Plus': True,
 'TotalHispanic': False,
 'LFPRateHispanic': True,
 'EmpRatioHispanic': True,
 'UnempRateHispanic': True,
 'TotalWhiteNonHispanic': False,
 'LFPRateWhiteNonHispanic': True,
 'EmpRatioWhiteNonHispanic': True,
 'UnempRateWhiteNonHispanic': True,
 'Total20To64': False,
 'LFPRate20To64': True,
 'EmpRatio20To64': True,
 'UnempRate20To64': True,
 'Total20To64Male': True,
 'LFPRate20To64Male': True,
 'EmpRatio20To64Male': True,
 'UnempRate20To64Male': True,
 'Total20To64Female': True,
 'LFPRate20To64Female': True,
 'EmpRatio20To64Female': True,
 'UnempRate20To64Female': True,
 'Total20To64FemaleChildrenUnder18': True,
 'LFPRate20To64FemaleChildrenUnder18': True,
 'EmpRatio20To64FemaleChildrenUnder18': True,
 'UnempRate20To64FemaleChildrenUnder18': True,
 'Total20To64FemaleChildrenUnder6': True,
 'LFPRate20To64FemaleChildrenUnder6': True,
 'EmpRatio20To64FemaleChildrenUnder6': True,
 'UnempRate20To64FemaleChildrenUnder6': True,
 'Total20To64FemaleChildrenUnder6And6To17': True,
 'LFPRate20To64FemaleChildrenUnder6And6To17': True,
 'EmpRatio20To64FemaleChildrenUnder6And6To17': True,
 'UnempRate20To64FemaleChildrenUnder6And6To17': True,
 'Total20To64FemaleChildren6To17': True,
 'LFPRate20To64FemaleChildren6To17': True,
 'EmpRatio20To64FemaleChildren6To17': True,
 'UnempRate20To64FemaleChildren6To17': True,
 'TotalBPL': True,
 'LFPRateBPL': True,
 'EmpRatioBPL': True,
 'UnempRateBPL': True,
 'TotalAPL': True,
 'LFPRateAPL': True,
 'EmpRatioAPL': True,
 'UnempRateAPL': True,
 'TotalDisabled': True,
 'LFPRateDisabled': True,
 'EmpRatioDisabled': True,
 'UnempRateDisabled': True,
 'TotalEdu25To64': False,
 'LFPRateEdu25To64': True,
 'EmpRatioEdu25To64': True,
 'UnempRateEdu25To64': True,
 'TotalEdu25To64LessHS': True,
 'LFPRateEdu25To64LessHS': True,
 'EmpRatioEdu25To64LessHS': True,
 'UnempRateEdu25To64LessHS': True,
 'TotalEdu25To64HS': True,
 'LFPRateEdu25To64HS': True,
 'EmpRatioEdu25To64HS': True,
 'UnempRateEdu25To64HS': True,
 'TotalEdu25To64SomeCollege': True,
 'LFPRateEdu25To64SomeCollege': True,
 'EmpRatioEdu25To64SomeCollege': True,
 'UnempRateEdu25To64SomeCollege': True,
 'TotalEdu25To64Bachelors': True,
 'LFPRateEdu25To64Bachelors': True,
 'EmpRatioEdu25To64Bachelors': True,
 'UnempRateEdu25To64Bachelors': True}

In [238]:
df_tract.head()

,TractID,GEO.id,GEO.id2,Tract,County,Year,HTotal,FTotal,MTotal,NfTotal,HIncomeLessThan10k,FIncomeLessThan10k,MIncomeLessThan10k,NfIncomeLessThan10k,HIncome10kTo14999,FIncome10kTo14999,MIncome10kTo14999,NfIncome10kTo14999,HIncome15kTo24999,FIncome15kTo24999,MIncome15kTo24999,NfIncome15kTo24999,HIncome25kTo34999,FIncome25kTo34999,MIncome25kTo34999,NfIncome25kTo34999,HIncome35kTo49999,FIncome35kTo49999,MIncome35kTo49999,NfIncome35kTo49999,HIncome50kTo74999,FIncome50kTo74999,MIncome50kTo74999,NfIncome50kTo74999,HIncome75kTo99999,FIncome75kTo99999,MIncome75kTo99999,NfIncome75kTo99999,HIncome100kTo149999,FIncome100kTo149999,MIncome100kTo149999,NfIncome100kTo149999,HIncome150kTo199999,FIncome150kTo199999,MIncome150kTo199999,NfIncome150kTo199999,HIncome200kOrMore,FIncome200kOrMore,MIncome200kOrMore,NfIncome200kOrMore,HIncomeMedian,FIncomeMedian,MIncomeMedian,NfIncomeMedian,HIncomeMean,FIncomeMean,MIncomeMean,NfIncomeMean,TotalPopulation,MaleTotal,FemaleTotal,TotalAgeUnder5,MaleAgeUnder5,FemaleAgeUnder5,TotalAge5To9,MaleAge5To9,FemaleAge5To9,TotalAge10To14,MaleAge10To14,FemaleAge10To14,TotalAge15To19,MaleAge15To19,FemaleAge15To19,TotalAge20To24,MaleAge20To24,FemaleAge20To24,TotalAge25To29,MaleAge25To29,FemaleAge25To29,TotalAge30To34,MaleAge30To34,FemaleAge30To34,TotalAge35To39,MaleAge35To39,FemaleAge35To39,TotalAge40To44,MaleAge40To44,FemaleAge40To44,TotalAge45To49,MaleAge45To49,FemaleAge45To49,TotalAge50To54,MaleAge50To54,FemaleAge50To54,TotalAge55To59,MaleAge55To59,FemaleAge55To59,TotalAge60To64,MaleAge60To64,FemaleAge60To64,TotalAge65To69,MaleAge65To69,FemaleAge65To69,TotalAge70To74,MaleAge70To74,FemaleAge70To74,TotalAge75To79,MaleAge75To79,FemaleAge75To79,TotalAge80To84,MaleAge80To84,FemaleAge80To84,TotalAge85AndOver,MaleAge85AndOver,FemaleAge85AndOver,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,Total16AndOver,LFPRate16AndOver,EmpRatio16AndOver,UnempRate16AndOver,TotalAge16To19,LFPRateAge16To19,EmpRatioAge16To19,UnempRateAge16To19,TotalAge20To24.1,LFPRateAge20To24,EmpRatioAge20To24,UnempRateAge20To24,TotalAge25To29.1,LFPRateAge25To29,EmpRatioAge25To29,UnempRateAge25To29,TotalAge30To34.1,LFPRateAge30To34,EmpRatioAge30To34,UnempRateAge30To34,TotalAge35To44,LFPRateAge35To44,EmpRatioAge35To44,UnempRateAge35To44,TotalAge45To54,LFPRateAge45To54,EmpRatioAge45To54,UnempRateAge45To54,TotalAge55To59.1,LFPRateAge55To59,EmpRatioAge55To59,UnempRateAge55To59,TotalAge60To64.1,LFPRateAge60To64,EmpRatioAge60To64,UnempRateAge60To64,TotalAge65To74,LFPRateAge65To74,EmpRatioAge65To74,UnempRateAge65To74,TotalAge75AndOver,LFPRateAge75AndOver,EmpRatioAge75AndOver,UnempRateAge75AndOver,TotalWhite,LFPRateWhite,EmpRatioWhite,UnempRateWhite,TotalBlack,LFPRateBlack,EmpRatioBlack,UnempRateBlack,TotalNative,LFPRateNative,EmpRatioNative,UnempRateNative,TotalAsian,LFPRateAsian,EmpRatioAsian,UnempRateAsian,TotalPacificIslander,LFPRatePacificIslander,EmpRatioPacificIslander,UnempRatePacificIslander,TotalOtherRace,LFPRateOtherRace,EmpRatioOtherRace,UnempRateOtherRace,Total2Plus,LFPRate2Plus,EmpRatio2Plus,UnempRate2Plus,TotalHispanic,LFPRateHispanic,EmpRatioHispanic,UnempRateHispanic,TotalWhiteNonHispanic,LFPRateWhiteNonHispanic,EmpRatioWhiteNonHispanic,UnempRateWhiteNonHispanic,Total20To64,LFPRate20To64,EmpRatio20To64,UnempRate20To64,Total20To64Male,LFPRate20To64Male,EmpRatio20To64Male,UnempRate20To64Male,Total20To64Female,LFPRate20To64Female,EmpRatio20To64Female,UnempRate20To64Female,Total20To64FemaleChildrenUnder18,LFPRate20To64FemaleChildrenUnder18,EmpRatio20To64FemaleChildrenUnder18,UnempRate20To64FemaleChildrenUnder18,Total20To64FemaleChildrenUnder6,LFPRate20To64FemaleChildrenUnder6,EmpRatio20To64FemaleChildrenUnder6,UnempRate20To64FemaleChildrenUnder6,Total20To64FemaleChildrenUnder6And6To17,LFPRate20To64FemaleChildrenUnder6And6To17,EmpRatio20To64FemaleChildrenUnder6And6To17,UnempRate20To64FemaleChildrenUnder6And6To17,Total20To64FemaleChildren6To17,LFPRate20To64FemaleChildren6To17,EmpRatio20To64FemaleChildren6To17,UnempRate20To64FemaleChildren6To17,TotalBPL,LFPRateBPL,EmpRatioBPL,UnempRateBPL,TotalAPL,LFPRateAPL,EmpRatioAPL,UnempRateAPL,TotalDisabled,LFPRateDisabled,EmpRatioDisabled,UnempRateDisabled,TotalEdu25To64,LFPRateEdu25To64,EmpRatioEdu25To64,UnempRateEdu25To64,TotalEdu25To64LessHS,LFPRateEdu25To64LessHS,EmpRatioEdu25To64LessHS,UnempRateEdu25To64LessHS,TotalEdu25To64HS,LFPRateEdu25To64HS,EmpRatioEdu25To64HS,UnempRateEdu25To64HS,TotalEdu25To64SomeCollege,LFPRateEdu25To64SomeCollege,EmpRatioEdu25To64SomeCollege,UnempRateEdu25To64SomeCollege,TotalEdu25To64Bachelors,LFPRateEdu25To64Bachelors,EmpRatioEdu25To64Bachelors,UnempRateEdu25To64Bachelors
0,1,1400000US13007960200,1.300796e+10,960200.0,Baker County,2017.0,517.0,311.0,253.0,206.0,10.6,1.6,0.0,24.3,1.4,0.0,0.0,3.4,13.0,9.3,11.5,18.4,20.7,7.7,9.5,40.3,12.0,12.5,12.3,11.2,19.0,31.5,32.4,0.0,12.8,19.6,21.3,2.4,0.0,0.0,0.0,0.0,6.6,10.9,4.7,0.0,4.1,6.8,8.3,0.0,45486.0,54926.0,52574.0,28106.0,58316.0,80776.0,NaN,24407.0,1135.0,523.0,612.0,36.0,24.0,12.0,33.0,0.0,33.0,76.0,50.0,26.0,89.0,33.0,56.0,51.0,34.0,17.0,48.0,8.0,40.0,60.0,21.0,39.0,81.0,56.0,25.0,40.0,13.0,27.0,57.0,43.0,14.0,28.0,15.0,13.0,83.0,11.0,72.0,147.0,86.0,61.0,151.0,61.0,90.0,65.0,27.0,38.0,75.0,34.0,41.0,0.0,0.0,0.0,15.0,7.0,8.0,1050.0,771.0,257.0,6.0,0.0,16.0,0.0,0.0,0.0,0.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,957.0,50.3,49.6,1.2,56.0,0.0,0.0,NaN,51.0,82.4,82.4,0.0,48.0,93.8,93.8,0.0,60.0,85.0,76.7,9.8,121.0,75.2,74.4,1.1,85.0,76.5,76.5,0.0,83.0,89.2,89.2,0.0,147.0,38.8,38.8,0.0,216.0,19.9,19.9,0.0,90.0,14.4,14.4,0.0,695.0,52.4,52.2,0.3,240.0,39.6,37.5,5.3,6.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,16.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,67.0,67.2,67.2,0.0,628.0,50.8,50.6,0.3,595.0,71.4,70.4,1.4,287.0,72.8,72.8,0.0,308.0,70.1,68.2,2.8,73.0,53.4,46.6,12.8,9.0,0.0,0.0,NaN,21.0,100.0,76.2,23.8,43.0,41.9,41.9,0.0,70.0,8.6,0.0,100.0,525.0,79.8,79.8,0.0,109.0,58.7,57.8,1.6,544.0,70.4,69.3,1.6,40.0,12.5,0.0,100.0,248.0,69.4,69.0,0.6,214.0,76.6,76.6,0.0,42.0,100.0,100.0,0.0
1,2,1400000US13007960100,1.300796e+10,960100.0,Baker County,2017.0,804.0,528.0,345.0,276.0,21.9,11.0,10.1,42.8,6.7,7.4,4.9,5.4,6.8,3.0,4.6,14.1,7.6,10.4,7.0,3.3,12.9,12.1,13.3,13.4,24.1,30.5,28.4,13.4,7.0,10.6,16.2,0.0,11.2,12.3,11.3,7.6,1.2,1.9,2.9,0.0,0.5,0.8,1.2,0.0,43594.0,52614.0,54844.0,17083.0,48346.0,57024.0,NaN,31070.0,2116.0,1024.0,1092.0,91.0,41.0,50.0,120.0,53.0,67.0,156.0,96.0,60.0,141.0,94.0,47.0,150.0,32.0,118.0,190.0,142.0,48.0,94.0,60.0,34.0,84.0,38.0,46.0,122.0,48.0,74.0,160.0,94.0,66.0,223.0,119.0,104.0,119.0,33.0,86.0,153.0,63.0,90.0,106.0,49.0,57.0,99.0,44.0,55.0,27.0,11.0,16.0,55.0,7.0,48.0,26.0,0.0,26.0,2027.0,924.0,1085.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,89.0,37.0,7.0,0.0,0.0,0.0,45.0,0.0,0.0,0.0,1722.0,48.7,47.1,3.2,114.0,16.7,14.9,10.5,150.0,52.0,52.0,0.0,190.0,55.8,55.8,0.0,94.0,78.7,67.0,14.9,206.0,57.8,57.8,0.0,383.0,66.8,65.3,2.3,119.0,80.7,73.9,8.3,153.0,42.5,42.5,0.0,205.0,12.2,12.2,0.0,108.0,0.0,0.0,NaN,817.0,59.6,58.0,2.7,852.0,37.3,35.7,4.4,0.0,NaN,NaN,NaN,8.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,45.0,55.6,55.6,0.0,0.0,NaN,NaN,NaN,64.0,68.8,68.8,0.0,798.0,58.6,57.0,2.8,1295.0,61.3,59.4,3.1,629.0,57.7,55.0,4.7,666.0,64.7,63.5,1.9,216.0,67.6,67.6,0.0,89.0,42.7,42.7,0.0,21.0,76.2,76.2,0.0,106.0,86.8,86.8,0.0,277.0,16.2,16.2,0.0,1018.0,73.6,71.1,3.3,241.0,28.2,23.7,16.2,1145.0,62.5,60.3,3.5,295.0,42.7,42.7,0.0,383.0,65.5,61.9,5.6,331.0,71.9,68.6,4.6,136.0,74.3,74.3,0.0
2,3,1400000US13321950600,1.332195e+10,950600.0,Worth County,2017.0,854.0,653.0,591.0,201.0,4.1,0.8,0.8,14.9,4.8,4.0,3.0,7.5,16.0,15.5,16.2,17.9,14.6,9.2,10.2,32.3,16.4,15.8,16.6,18.4,23.1,29.4,29.8,2.5,11.4,12.9,12.4,6.5,4.9,6.4,5.8,0.0,4.0,5.2,4.2,0.0,0.7,0.9,1.0,0.0,38649.0,51969.0,51156.0,27120.0,54027.0,61804.0,NaN,28761.0,2264.0,1369.0,895.0,114.0,84.0,30.0,158.0,153.0,5.0,138.0,107.0,31.0,86.0,59.0,27.0,125.0,57.0,68.0,109.0,63.0,46.0,138.0,87.0,51.0,116.0,79.0,37.0,149.0,90.0,59.0,135.0,50.0,85.0,158.0,121.0,37.0,223.0,77.0,146.0,156.0,72.0,84.0,232.0,156.0,76.0,126.0,68.0,58.0,70.0,35.0,35.0,21.0,11.0,10.0,10.0,0.0,10.0,2030.0,1745.0,285.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,234.0,155.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,1818.0,58.7,52.9,9.6,50.0,24.0,0.0,100.0,125.0,100.0,68.8,28.3,109.0,91.7,91.7,0.0,138.0,50.0,35.5,29.0,265.0,80.8,78.1,3.3,293.0,58.7,56.0,4.7,223.0,70.0,63.2,9.6,156.0,52.6,52.6,0.0,358.0,37.2,35.5,4.5,101.0,5.0,5.0,0.0,1483.0,60.7,54.8,9.3,280.0,54.6,47.9,12.4,55.0,27.3,27.3,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,94.0,57.4,57.4,0.0,1444.0,59.6,53.5,9.7,1309.0,70.1,63.3,9.2,696.0,80.5,74.3,6.8,613.0,58.4,50.9,12.8,166.0,59.0,47.0,20.4,14.0,100.0,100.0,0.0,37.0,32.4,32.4,0.0,115.0,62.6,45.2,27.8,181.0,60.2,37.6,34.6,1128.0,71.7,67.5,5.9,245.0,51.8,42.0,18.9,1184.0,67.0,62.8,6.3,205.0,59.5,59.5,0.0,430.0,65.1,58.6,10.0,450.0,66.7,61.8,7.3,99.0,91.9,91.9,0.0
3,4,1400000US13321950500,1.332195e+10,950500.0,Worth County,2017.0,1674.0,1135.0,642.0,539.0,18.2,17.8,1.9,18.9,6.5,2.6,0.0,14.8,10.8,6.5,7.5,21.7,12.4,11.5,11.4,14.3,14.8,18.3,9.7,6.7,17.7,21.2,32.9,9.3,13.8,13.6,21.8,14.3,3.8,5.6,10.0,0.0,1.5,2.2,3.9,0.0,0.4,0.6,1.1,0.0,36458.0,44208.0,66090.0,23059.0,44636.0,50183.0,NaN,32214.0,4027.0,1984.0,2043.0,197.0,72.0,125.0,250.0,152.0,98.0,120.0,41.0,79.0,300.0,218.0,82.0,424.0,222.0,202.0,201.0,81.0,120.0,212.0,64.0,148.0,91.0,31.0,60.0,351.0,178.0,173.0,174.0,81.0,93.0,414.0,227.0,187.0,286.0,163.0,123.0,306.0,174.0,132.0,156.0,61.0,95.0,227.0,83.0,144.0,119.0,59.0,60.0,84.0,48.0,36.0,115.0,29.0,86.0,3968.0,1842.0,1906.0,0.0,32.0,0.0,76.0,112.0,11.0,101.0,59.0,32.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,3432.0,56.8,52.6,7.4,272.0,37.9,37.9,0.0,424.0,72.2,57.8,19.9,201.0,67.2,61.7,8.1,212.0,56.1,32.5,42.0,442.0,77.8,74.2,4.7,588.0,78.7,77.7,1.3,286.0,65.4,65.4,0.0,306.0,58.5,58.5,0.0,383.0,27.7,27.7,0.0,318.0,2.2,2.2,0.0,1655.0,53.4,51.7,3.2,1646.0,58.0,50.9,12.2,0.0,NaN,NaN,NaN,32.0,71.9,71.9,0.0,0.0,NaN,NaN,NaN,71.0,100.0,100.0,0.0,28.0,60.7,60.7,0.0,59.0,89.8,89.8,0.0,1623.0,52.9,51.1,3.3,2459.0,70.5,64.6,8.3,1221.0,79.2,69.7,12.0,1238.0,61.9,59.6,3.7,408.0,66.7,64.0,4.0,79.0,88.6,88.6,0.0,37.0,100.0,70.3,29.7,292.0,56.5,56.5,0.0,458.0,33.8,27.9,17.4,1971.0,80.1,74.1,7.4,283.0,21.6,21.6,0.0,2035.0,70.1,66.0,5.8,317.0,47.6,31.9,33.1,974.0,63.4,62.8,1.0,569.0,86.8,84.9,2.2,175.0,93.7,84.6,9.8
4,5,1400000US13321950400,1.332195e+10,950400.0,Worth County,2017.0,1573.0,1163.0,949.0,410.0,7.0,1.2,1.3,23.4,7.9,7.1,3.3,10.2,15.9,14.4,10.4,20.5,10.2,8.9,8.3,13.9,17.5,18.4,21.2,14.9,16.7,18.1,18.8,13.4,12.8,16.3,18.9,1.7,6.5,8.1,8.6,2.0,3.9,5.3,6.5,0.0,1.7,2.2,2.7,0.0,43720.0,50096.0,58359.0,24076.0,59481.0,70036.0,NaN,29068.0,4393.0,2168.0,2225.0,274.0,117.0,157.0,240.0,146.0,94.0,382.0,183.0,199.0,370.0,154.0,216.0,243.0,136.0,107.0,194.0,106.0,88.0,272.0,159.0,113.0,244.0,70.0,174.0,251.0,185.0,66.0,278.0,108.0,170.0,249.0,132.0,117.0,398.0,251.0,147.0,252.0,92.0,160.0,201.0,113.0,88.0,212.0,98.0,114.0,152.0,60.0,92.0,78.0,22.0,56.0,103.0,36.0,67.0,4341.0,3360.0,923.0,0.0,16.0,0.0,0.0,42.0,0.0,42.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3389.0,55.4,50.2,9.4,262.0,40.5,27.5,32.1,243.0,80.2,79.0,1.5,194.0,64.4,51.0,20.8,272.0,71.3,64.3,9.8,495.0,77.8,75.2,3.4,527.0,80.1,78.0,2.6,398.0,68.1,57.5,15.5,252.0,50.0,38.5,23.0,413.0,9.0,9.0,0.0,333.0,5.4,5.4,0.0,2632.0,59.2,54.1,8.5,699.0,45.8,39.5,13.8,0.0,NaN,NaN,NaN,16.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,42.0,4.8,4.8,0.0,0.0,NaN,NaN,NaN,2632.0,59.2,54.1,8.5,2381.0,72.2,66.1,8.3,1239.0,81.8,75.7,7.5,1142.0,61.6,55.8,9.5,412.0,75.0,64.1,14.6,47.0,72.3,61.7,14.7,75.0,94.7,69.3,26.8,290.0,70.3,63.1,10.3,456.0,52.4,44.1,15.9,1925.0,76.8,71.4,7.1,485.0,36.1,22.9,36.6,2138.0,71.2,64.7,9.2,438.0,56.8,49.5,12.9,748.0,72.9,65.5,10.1,705.0,76.3,70.5,7.6,247.0,77.3,72.5,6.3

In [240]:
cols = list(df_tract)
for i in range(len(cols)):
    col = cols[i]
    isfloat = tract_summary['Datatype'][i] == 'float64'
    if isfloat:
        if not tmp[col]:
            df_tract[col] = df_tract[col].astype('Int64')

In [242]:
construct_summary(df_tract)

                                            Datatype  Nulls  Uniques
TractID                                        int64  False     True
GEO.id                                        object  False    False
GEO.id2                                        Int64  False    False
Tract                                          Int64  False    False
County                                        object  False    False
Year                                           Int64  False    False
HTotal                                         Int64  False    False
FTotal                                         Int64  False    False
MTotal                                         Int64  False    False
NfTotal                                        Int64  False    False
HIncomeLessThan10k                           float64  False    False
FIncomeLessThan10k                           float64  False    False
MIncomeLessThan10k                           float64  False    False
NfIncomeLessThan10k                          float64  False    False
HIncome10kTo14999                            float64  False    False
FIncome10kTo14999                            float64  False    False
MIncome10kTo14999                            float64  False    False
NfIncome10kTo14999                           float64  False    False
HIncome15kTo24999                            float64  False    False
FIncome15kTo24999                            float64  False    False
MIncome15kTo24999                            float64  False    False
NfIncome15kTo24999                           float64  False    False
HIncome25kTo34999                            float64  False    False
FIncome25kTo34999                            float64  False    False
MIncome25kTo34999                            float64  False    False
NfIncome25kTo34999                           float64  False    False
HIncome35kTo49999                            float64  False    False
FIncome35kTo49999                            float64  False    False
MIncome35kTo49999                            float64  False    False
NfIncome35kTo49999                           float64  False    False
HIncome50kTo74999                            float64  False    False
FIncome50kTo74999                            float64  False    False
MIncome50kTo74999                            float64  False    False
NfIncome50kTo74999                           float64  False    False
HIncome75kTo99999                            float64  False    False
FIncome75kTo99999                            float64  False    False
MIncome75kTo99999                            float64  False    False
NfIncome75kTo99999                           float64  False    False
HIncome100kTo149999                          float64  False    False
FIncome100kTo149999                          float64  False    False
MIncome100kTo149999                          float64  False    False
NfIncome100kTo149999                         float64  False    False
HIncome150kTo199999                          float64  False    False
FIncome150kTo199999                          float64  False    False
MIncome150kTo199999                          float64  False    False
NfIncome150kTo199999                         float64  False    False
HIncome200kOrMore                            float64  False    False
FIncome200kOrMore                            float64  False    False
MIncome200kOrMore                            float64  False    False
NfIncome200kOrMore                           float64  False    False
HIncomeMedian                                  Int64  False    False
FIncomeMedian                                  Int64  False    False
MIncomeMedian                                float64   True    False
NfIncomeMedian                               float64   True    False
HIncomeMean                                    Int64  False    False
FIncomeMean                                    Int64  False    False
MIncomeMean                                  float64   True     True
NfIncomeMean                                   Int64  False    False
TotalPopulation                                Int64  False    False
MaleTotal                                      Int64  False    False
FemaleTotal                                    Int64  False    False
TotalAgeUnder5                               float64  False    False
MaleAgeUnder5                                float64  False    False
FemaleAgeUnder5                              float64  False    False
TotalAge5To9                                 float64  False    False
MaleAge5To9                                  float64  False    False
FemaleAge5To9                                float64  False    False
TotalAge10To14                               float64  False    False
MaleAge10To14                                float64  False    False
FemaleAge10To14                              float64  False    False
TotalAge15To19                               float64  False    False
MaleAge15To19                                float64  False    False
FemaleAge15To19                              float64  False    False
TotalAge20To24                               float64  False    False
MaleAge20To24                                float64  False    False
FemaleAge20To24                              float64  False    False
TotalAge25To29                               float64  False    False
MaleAge25To29                                float64  False    False
FemaleAge25To29                              float64  False    False
TotalAge30To34                               float64  False    False
MaleAge30To34                                float64  False    False
FemaleAge30To34                              float64  False    False
TotalAge35To39                               float64  False    False
MaleAge35To39                                float64  False    False
FemaleAge35To39                              float64  False    False
TotalAge40To44                               float64  False    False
MaleAge40To44                                float64  False    False
FemaleAge40To44                              float64  False    False
TotalAge45To49                               float64  False    False
MaleAge45To49                                float64  False    False
FemaleAge45To49                              float64  False    False
TotalAge50To54                               float64  False    False
MaleAge50To54                                float64  False    False
FemaleAge50To54                              float64  False    False
TotalAge55To59                               float64  False    False
MaleAge55To59                                float64  False    False
FemaleAge55To59                              float64  False    False
TotalAge60To64                               float64  False    False
MaleAge60To64                                float64  False    False
FemaleAge60To64                              float64  False    False
TotalAge65To69                               float64  False    False
MaleAge65To69                                float64  False    False
FemaleAge65To69                              float64  False    False
TotalAge70To74                               float64  False    False
MaleAge70To74                                float64  False    False
FemaleAge70To74                              float64  False    False
TotalAge75To79                               float64  False    False
MaleAge75To79                                float64  False    False
FemaleAge75To79                              float64  False    False
TotalAge80To84                               float64  False    False
MaleAge80To84                                float64  False    False
FemaleAge80To84                              float64  False    False
TotalAge85AndOver                            float64  False    False
MaleAge85AndOver                             float64  False    False
FemaleAge85AndOver                           float64  False    False
NonHispanic                                    Int64  False    False
NonHispanicWhite                               Int64  False    False
NonHispanicBlack                               Int64  False    False
NonHispanicNative                              Int64  False    False
NonHispanicAsian                               Int64  False    False
NonHispanicPacificIslander                     Int64  False    False
NonHispanicOtherRace                           Int64  False    False
NonHispanic2Plus                               Int64  False    False
NonHispanic2PlusIncOther                       Int64  False    False
NonHispanic2PlusExcOther                       Int64  False    False
Hispanic                                       Int64  False    False
HispanicWhite                                  Int64  False    False
HispanicBlack                                  Int64  False    False
HispanicNative                                 Int64  False    False
HispanicAsian                                  Int64  False    False
HispanicPacificIslander                        Int64  False    False
HispanicOtherRace                              Int64  False    False
Hispanic2Plus                                  Int64  False    False
Hispanic2PlusIncOther                          Int64  False    False
Hispanic2PlusExcOther                          Int64  False    False
Total16AndOver                                 Int64  False    False
LFPRate16AndOver                             float64   True    False
EmpRatio16AndOver                            float64   True    False
UnempRate16AndOver                           float64  False    False
TotalAge16To19                                 Int64  False    False
LFPRateAge16To19                             float64   True    False
EmpRatioAge16To19                            float64   True    False
UnempRateAge16To19                           float64   True    False
TotalAge20To24.1                               Int64  False    False
LFPRateAge20To24                             float64   True    False
EmpRatioAge20To24                            float64   True    False
UnempRateAge20To24                           float64  False    False
TotalAge25To29.1                             float64   True    False
LFPRateAge25To29                             float64   True    False
EmpRatioAge25To29                            float64   True    False
UnempRateAge25To29                           float64   True    False
TotalAge30To34.1                             float64   True    False
LFPRateAge30To34                             float64   True    False
EmpRatioAge30To34                            float64   True    False
UnempRateAge30To34                           float64   True    False
TotalAge35To44                               float64   True    False
LFPRateAge35To44                             float64   True    False
EmpRatioAge35To44                            float64   True    False
UnempRateAge35To44                           float64   True    False
TotalAge45To54                                 Int64  False    False
LFPRateAge45To54                             float64   True    False
EmpRatioAge45To54                            float64   True    False
UnempRateAge45To54                           float64  False    False
TotalAge55To59.1                             float64   True    False
LFPRateAge55To59                             float64   True    False
EmpRatioAge55To59                            float64   True    False
UnempRateAge55To59                           float64   True    False
TotalAge60To64.1                             float64   True    False
LFPRateAge60To64                             float64   True    False
EmpRatioAge60To64                            float64   True    False
UnempRateAge60To64                           float64   True    False
TotalAge65To74                                 Int64  False    False
LFPRateAge65To74                             float64   True    False
EmpRatioAge65To74                            float64   True    False
UnempRateAge65To74                           float64   True    False
TotalAge75AndOver                              Int64  False    False
LFPRateAge75AndOver                          float64   True    False
EmpRatioAge75AndOver                         float64   True    False
UnempRateAge75AndOver                        float64   True    False
TotalWhite                                   float64   True    False
LFPRateWhite                                 float64   True    False
EmpRatioWhite                                float64   True    False
UnempRateWhite                               float64   True    False
TotalBlack                                   float64   True    False
LFPRateBlack                                 float64   True    False
EmpRatioBlack                                float64   True    False
UnempRateBlack                               float64   True    False
TotalNative                                  float64   True    False
LFPRateNative                                float64   True    False
EmpRatioNative                               float64   True    False
UnempRateNative                              float64   True    False
TotalAsian                                   float64   True    False
LFPRateAsian                                 float64   True    False
EmpRatioAsian                                float64   True    False
UnempRateAsian                               float64   True    False
TotalPacificIslander                         float64   True    False
LFPRatePacificIslander                       float64   True    False
EmpRatioPacificIslander                      float64   True    False
UnempRatePacificIslander                     float64   True    False
TotalOtherRace                               float64   True    False
LFPRateOtherRace                             float64   True    False
EmpRatioOtherRace                            float64   True    False
UnempRateOtherRace                           float64   True    False
Total2Plus                                     Int64  False    False
LFPRate2Plus                                 float64   True    False
EmpRatio2Plus                                float64   True    False
UnempRate2Plus                               float64   True    False
TotalHispanic                                  Int64  False    False
LFPRateHispanic                              float64   True    False
EmpRatioHispanic                             float64   True    False
UnempRateHispanic                            float64   True    False
TotalWhiteNonHispanic                          Int64  False    False
LFPRateWhiteNonHispanic                      float64   True    False
EmpRatioWhiteNonHispanic                     float64   True    False
UnempRateWhiteNonHispanic                    float64   True    False
Total20To64                                    Int64  False    False
LFPRate20To64                                float64   True    False
EmpRatio20To64                               float64   True    False
UnempRate20To64                              float64  False    False
Total20To64Male                              float64   True    False
LFPRate20To64Male                            float64   True    False
EmpRatio20To64Male                           float64   True    False
UnempRate20To64Male                          float64   True    False
Total20To64Female                            float64   True    False
LFPRate20To64Female                          float64   True    False
EmpRatio20To64Female                         float64   True    False
UnempRate20To64Female                        float64   True    False
Total20To64FemaleChildrenUnder18             float64   True    False
LFPRate20To64FemaleChildrenUnder18           float64   True    False
EmpRatio20To64FemaleChildrenUnder18          float64   True    False
UnempRate20To64FemaleChildrenUnder18         float64   True    False
Total20To64FemaleChildrenUnder6              float64   True    False
LFPRate20To64FemaleChildrenUnder6            float64   True    False
EmpRatio20To64FemaleChildrenUnder6           float64   True    False
UnempRate20To64FemaleChildrenUnder6          float64   True    False
Total20To64FemaleChildrenUnder6And6To17      float64   True    False
LFPRate20To64FemaleChildrenUnder6And6To17    float64   True    False
EmpRatio20To64FemaleChildrenUnder6And6To17   float64   True    False
UnempRate20To64FemaleChildrenUnder6And6To17  float64   True    False
Total20To64FemaleChildren6To17               float64   True    False
LFPRate20To64FemaleChildren6To17             float64   True    False
EmpRatio20To64FemaleChildren6To17            float64   True    False
UnempRate20To64FemaleChildren6To17           float64   True    False
TotalBPL                                     float64   True    False
LFPRateBPL                                   float64   True    False
EmpRatioBPL                                  float64   True    False
UnempRateBPL                                 float64   True    False
TotalAPL                                     float64   True    False
LFPRateAPL                                   float64   True    False
EmpRatioAPL                                  float64   True    False
UnempRateAPL                                 float64   True    False
TotalDisabled                                float64   True    False
LFPRateDisabled                              float64   True    False
EmpRatioDisabled                             float64   True    False
UnempRateDisabled                            float64   True    False
TotalEdu25To64                                 Int64  False    False
LFPRateEdu25To64                             float64   True    False
EmpRatioEdu25To64                            float64   True    False
UnempRateEdu25To64                           float64  False    False
TotalEdu25To64LessHS                         float64   True    False
LFPRateEdu25To64LessHS                       float64   True    False
EmpRatioEdu25To64LessHS                      float64   True    False
UnempRateEdu25To64LessHS                     float64   True    False
TotalEdu25To64HS                             float64   True    False
LFPRateEdu25To64HS                           float64   True    False
EmpRatioEdu25To64HS                          float64   True    False
UnempRateEdu25To64HS                         float64   True    False
TotalEdu25To64SomeCollege                    float64   True    False
LFPRateEdu25To64SomeCollege                  float64   True    False
EmpRatioEdu25To64SomeCollege                 float64   True    False
UnempRateEdu25To64SomeCollege                float64   True    False
TotalEdu25To64Bachelors                      float64   True    False
LFPRateEdu25To64Bachelors                    float64   True    False
EmpRatioEdu25To64Bachelors                   float64   True    False
UnempRateEdu25To64Bachelors                  float64   True    False

In [247]:
tract_summary = construct_summary(df_tract)

In [259]:
def sql_helper(summary):
    lines = []
    for i in range(len(summary)):
        col_name = summary.index[i]
        datatype = str(summary.iloc[i]['Datatype'])
        nulls = summary.iloc[i]['Nulls']
        line = ""
        line += '[' + col_name +'] '
        if datatype == 'object':
            line += "[VARCHAR](255) "
        elif datatype == 'int64' or datatype == 'Int64':
            line += "[INT] "
        elif datatype == 'float64':
            line += "[FLOAT] "
        else:
            line += "Inspect " + str(i) + ": " + col_name
        if nulls:
            line += "NULL,"
        else:
            line += "NOT NULL,"
        lines.append(line)
    return lines

In [260]:
def sql_helper_write(lines, name):
    with open(name+'_sql_helper.txt', 'w') as f:
        for line in lines:
            f.write(line+'\n')

In [261]:
lines = sql_helper(tract_summary)
sql_helper_write(lines, 'tract')

In [262]:
df_tract.to_csv(path+'TestDB/Ship/Tract_v03.csv', index=False)

In [263]:
block_summary = construct_summary(df_bg)

In [265]:
lines = sql_helper(block_summary)
sql_helper_write(lines, 'block_group')

In [4]:
df_tract = pd.read_csv(path+'TestDB/Ship/Tract_v03.csv')

## change everything to floats actually because it's easier that way

In [21]:
df_tract = pd.read_csv(path+'TestDB/Ship/Tract_v03.csv')

In [32]:
df_tract.iloc[:,6:] = df_tract.iloc[:,6:].astype('float')

In [34]:
df_tract.to_csv(path+'TestDB/Ship/Tract_v04.csv')

In [54]:
list(df_tract)

['TractID',
 'GEO.id',
 'GEO.id2',
 'Tract',
 'County',
 'Year',
 'HTotal',
 'FTotal',
 'MTotal',
 'NfTotal',
 'HIncomeLessThan10k',
 'FIncomeLessThan10k',
 'MIncomeLessThan10k',
 'NfIncomeLessThan10k',
 'HIncome10kTo14999',
 'FIncome10kTo14999',
 'MIncome10kTo14999',
 'NfIncome10kTo14999',
 'HIncome15kTo24999',
 'FIncome15kTo24999',
 'MIncome15kTo24999',
 'NfIncome15kTo24999',
 'HIncome25kTo34999',
 'FIncome25kTo34999',
 'MIncome25kTo34999',
 'NfIncome25kTo34999',
 'HIncome35kTo49999',
 'FIncome35kTo49999',
 'MIncome35kTo49999',
 'NfIncome35kTo49999',
 'HIncome50kTo74999',
 'FIncome50kTo74999',
 'MIncome50kTo74999',
 'NfIncome50kTo74999',
 'HIncome75kTo99999',
 'FIncome75kTo99999',
 'MIncome75kTo99999',
 'NfIncome75kTo99999',
 'HIncome100kTo149999',
 'FIncome100kTo149999',
 'MIncome100kTo149999',
 'NfIncome100kTo149999',
 'HIncome150kTo199999',
 'FIncome150kTo199999',
 'MIncome150kTo199999',
 'NfIncome150kTo199999',
 'HIncome200kOrMore',
 'FIncome200kOrMore',
 'MIncome200kOrMore',
 'NfIncome200kOrMore',
 'HIncomeMedian',
 'FIncomeMedian',
 'MIncomeMedian',
 'NfIncomeMedian',
 'HIncomeMean',
 'FIncomeMean',
 'MIncomeMean',
 'NfIncomeMean',
 'TotalPopulation',
 'MaleTotal',
 'FemaleTotal',
 'TotalAgeUnder5',
 'MaleAgeUnder5',
 'FemaleAgeUnder5',
 'TotalAge5To9',
 'MaleAge5To9',
 'FemaleAge5To9',
 'TotalAge10To14',
 'MaleAge10To14',
 'FemaleAge10To14',
 'TotalAge15To19',
 'MaleAge15To19',
 'FemaleAge15To19',
 'TotalAge20To24',
 'MaleAge20To24',
 'FemaleAge20To24',
 'TotalAge25To29',
 'MaleAge25To29',
 'FemaleAge25To29',
 'TotalAge30To34',
 'MaleAge30To34',
 'FemaleAge30To34',
 'TotalAge35To39',
 'MaleAge35To39',
 'FemaleAge35To39',
 'TotalAge40To44',
 'MaleAge40To44',
 'FemaleAge40To44',
 'TotalAge45To49',
 'MaleAge45To49',
 'FemaleAge45To49',
 'TotalAge50To54',
 'MaleAge50To54',
 'FemaleAge50To54',
 'TotalAge55To59',
 'MaleAge55To59',
 'FemaleAge55To59',
 'TotalAge60To64',
 'MaleAge60To64',
 'FemaleAge60To64',
 'TotalAge65To69',
 'MaleAge65To69',
 'FemaleAge65To69',
 'TotalAge70To74',
 'MaleAge70To74',
 'FemaleAge70To74',
 'TotalAge75To79',
 'MaleAge75To79',
 'FemaleAge75To79',
 'TotalAge80To84',
 'MaleAge80To84',
 'FemaleAge80To84',
 'TotalAge85AndOver',
 'MaleAge85AndOver',
 'FemaleAge85AndOver',
 'NonHispanic',
 'NonHispanicWhite',
 'NonHispanicBlack',
 'NonHispanicNative',
 'NonHispanicAsian',
 'NonHispanicPacificIslander',
 'NonHispanicOtherRace',
 'NonHispanic2Plus',
 'NonHispanic2PlusIncOther',
 'NonHispanic2PlusExcOther',
 'Hispanic',
 'HispanicWhite',
 'HispanicBlack',
 'HispanicNative',
 'HispanicAsian',
 'HispanicPacificIslander',
 'HispanicOtherRace',
 'Hispanic2Plus',
 'Hispanic2PlusIncOther',
 'Hispanic2PlusExcOther',
 'Total16AndOver',
 'LFPRate16AndOver',
 'EmpRatio16AndOver',
 'UnempRate16AndOver',
 'TotalAge16To19',
 'LFPRateAge16To19',
 'EmpRatioAge16To19',
 'UnempRateAge16To19',
 'TotalAge20To24.1',
 'LFPRateAge20To24',
 'EmpRatioAge20To24',
 'UnempRateAge20To24',
 'TotalAge25To29.1',
 'LFPRateAge25To29',
 'EmpRatioAge25To29',
 'UnempRateAge25To29',
 'TotalAge30To34.1',
 'LFPRateAge30To34',
 'EmpRatioAge30To34',
 'UnempRateAge30To34',
 'TotalAge35To44',
 'LFPRateAge35To44',
 'EmpRatioAge35To44',
 'UnempRateAge35To44',
 'TotalAge45To54',
 'LFPRateAge45To54',
 'EmpRatioAge45To54',
 'UnempRateAge45To54',
 'TotalAge55To59.1',
 'LFPRateAge55To59',
 'EmpRatioAge55To59',
 'UnempRateAge55To59',
 'TotalAge60To64.1',
 'LFPRateAge60To64',
 'EmpRatioAge60To64',
 'UnempRateAge60To64',
 'TotalAge65To74',
 'LFPRateAge65To74',
 'EmpRatioAge65To74',
 'UnempRateAge65To74',
 'TotalAge75AndOver',
 'LFPRateAge75AndOver',
 'EmpRatioAge75AndOver',
 'UnempRateAge75AndOver',
 'TotalWhite',
 'LFPRateWhite',
 'EmpRatioWhite',
 'UnempRateWhite',
 'TotalBlack',
 'LFPRateBlack',
 'EmpRatioBlack',
 'UnempRateBlack',
 'TotalNative',
 'LFPRateNative',
 'EmpRatioNative',
 'UnempRateNative',
 'TotalAsian',
 'LFPRateAsian',
 'EmpRatioAsian',
 'UnempRateAsian',
 'TotalPacificIslander',
 'LFPRatePacificIslander',
 'EmpRatioPacificIslander',
 'UnempRatePacificIslander',
 'TotalOtherRace',
 'LFPRateOtherRace',
 'EmpRatioOtherRace',
 'UnempRateOtherRace',
 'Total2Plus',
 'LFPRate2Plus',
 'EmpRatio2Plus',
 'UnempRate2Plus',
 'TotalHispanic',
 'LFPRateHispanic',
 'EmpRatioHispanic',
 'UnempRateHispanic',
 'TotalWhiteNonHispanic',
 'LFPRateWhiteNonHispanic',
 'EmpRatioWhiteNonHispanic',
 'UnempRateWhiteNonHispanic',
 'Total20To64',
 'LFPRate20To64',
 'EmpRatio20To64',
 'UnempRate20To64',
 'Total20To64Male',
 'LFPRate20To64Male',
 'EmpRatio20To64Male',
 'UnempRate20To64Male',
 'Total20To64Female',
 'LFPRate20To64Female',
 'EmpRatio20To64Female',
 'UnempRate20To64Female',
 'Total20To64FemaleChildrenUnder18',
 'LFPRate20To64FemaleChildrenUnder18',
 'EmpRatio20To64FemaleChildrenUnder18',
 'UnempRate20To64FemaleChildrenUnder18',
 'Total20To64FemaleChildrenUnder6',
 'LFPRate20To64FemaleChildrenUnder6',
 'EmpRatio20To64FemaleChildrenUnder6',
 'UnempRate20To64FemaleChildrenUnder6',
 'Total20To64FemaleChildrenUnder6And6To17',
 'LFPRate20To64FemaleChildrenUnder6And6To17',
 'EmpRatio20To64FemaleChildrenUnder6And6To17',
 'UnempRate20To64FemaleChildrenUnder6And6To17',
 'Total20To64FemaleChildren6To17',
 'LFPRate20To64FemaleChildren6To17',
 'EmpRatio20To64FemaleChildren6To17',
 'UnempRate20To64FemaleChildren6To17',
 'TotalBPL',
 'LFPRateBPL',
 'EmpRatioBPL',
 'UnempRateBPL',
 'TotalAPL',
 'LFPRateAPL',
 'EmpRatioAPL',
 'UnempRateAPL',
 'TotalDisabled',
 'LFPRateDisabled',
 'EmpRatioDisabled',
 'UnempRateDisabled',
 'TotalEdu25To64',
 'LFPRateEdu25To64',
 'EmpRatioEdu25To64',
 'UnempRateEdu25To64',
 'TotalEdu25To64LessHS',
 'LFPRateEdu25To64LessHS',
 'EmpRatioEdu25To64LessHS',
 'UnempRateEdu25To64LessHS',
 'TotalEdu25To64HS',
 'LFPRateEdu25To64HS',
 'EmpRatioEdu25To64HS',
 'UnempRateEdu25To64HS',
 'TotalEdu25To64SomeCollege',
 'LFPRateEdu25To64SomeCollege',
 'EmpRatioEdu25To64SomeCollege',
 'UnempRateEdu25To64SomeCollege',
 'TotalEdu25To64Bachelors',
 'LFPRateEdu25To64Bachelors',
 'EmpRatioEdu25To64Bachelors',
 'UnempRateEdu25To64Bachelors']

In [56]:
df_tract = df_tract.rename(columns={'TotalAge20To24.1':'TotalAge20To24', 'TotalAge25To29.1':'TotalAge25To29',
                     'TotalAge30To34.1':'TotalAge30To34', 'TotalAge55To59.1':'TotalAge55To59',
                        'TotalAge60To64.1':'TotalAge60To64'})

In [58]:
df_tract.to_csv(path+'TestDB/Ship/Tract_v04.csv', index=False)

In [63]:
df_tax[['Year', 'TSYear', 'TSMonth', 'TSDay']] = df_tax[['Year', 'TSYear', 'TSMonth', 'TSDay']].astype('Int64')

In [66]:
df_tax.to_csv(path+'TestDB/Ship/Tax_v03.csv', index=False)

In [64]:
df_tract.head()

,TractID,GEO.id,GEO.id2,Tract,County,Year,HTotal,FTotal,MTotal,NfTotal,HIncomeLessThan10k,FIncomeLessThan10k,MIncomeLessThan10k,NfIncomeLessThan10k,HIncome10kTo14999,FIncome10kTo14999,MIncome10kTo14999,NfIncome10kTo14999,HIncome15kTo24999,FIncome15kTo24999,MIncome15kTo24999,NfIncome15kTo24999,HIncome25kTo34999,FIncome25kTo34999,MIncome25kTo34999,NfIncome25kTo34999,HIncome35kTo49999,FIncome35kTo49999,MIncome35kTo49999,NfIncome35kTo49999,HIncome50kTo74999,FIncome50kTo74999,MIncome50kTo74999,NfIncome50kTo74999,HIncome75kTo99999,FIncome75kTo99999,MIncome75kTo99999,NfIncome75kTo99999,HIncome100kTo149999,FIncome100kTo149999,MIncome100kTo149999,NfIncome100kTo149999,HIncome150kTo199999,FIncome150kTo199999,MIncome150kTo199999,NfIncome150kTo199999,HIncome200kOrMore,FIncome200kOrMore,MIncome200kOrMore,NfIncome200kOrMore,HIncomeMedian,FIncomeMedian,MIncomeMedian,NfIncomeMedian,HIncomeMean,FIncomeMean,MIncomeMean,NfIncomeMean,TotalPopulation,MaleTotal,FemaleTotal,TotalAgeUnder5,MaleAgeUnder5,FemaleAgeUnder5,TotalAge5To9,MaleAge5To9,FemaleAge5To9,TotalAge10To14,MaleAge10To14,FemaleAge10To14,TotalAge15To19,MaleAge15To19,FemaleAge15To19,TotalAge20To24,MaleAge20To24,FemaleAge20To24,TotalAge25To29,MaleAge25To29,FemaleAge25To29,TotalAge30To34,MaleAge30To34,FemaleAge30To34,TotalAge35To39,MaleAge35To39,FemaleAge35To39,TotalAge40To44,MaleAge40To44,FemaleAge40To44,TotalAge45To49,MaleAge45To49,FemaleAge45To49,TotalAge50To54,MaleAge50To54,FemaleAge50To54,TotalAge55To59,MaleAge55To59,FemaleAge55To59,TotalAge60To64,MaleAge60To64,FemaleAge60To64,TotalAge65To69,MaleAge65To69,FemaleAge65To69,TotalAge70To74,MaleAge70To74,FemaleAge70To74,TotalAge75To79,MaleAge75To79,FemaleAge75To79,TotalAge80To84,MaleAge80To84,FemaleAge80To84,TotalAge85AndOver,MaleAge85AndOver,FemaleAge85AndOver,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,Total16AndOver,LFPRate16AndOver,EmpRatio16AndOver,UnempRate16AndOver,TotalAge16To19,LFPRateAge16To19,EmpRatioAge16To19,UnempRateAge16To19,TotalAge20To24,LFPRateAge20To24,EmpRatioAge20To24,UnempRateAge20To24,TotalAge25To29,LFPRateAge25To29,EmpRatioAge25To29,UnempRateAge25To29,TotalAge30To34,LFPRateAge30To34,EmpRatioAge30To34,UnempRateAge30To34,TotalAge35To44,LFPRateAge35To44,EmpRatioAge35To44,UnempRateAge35To44,TotalAge45To54,LFPRateAge45To54,EmpRatioAge45To54,UnempRateAge45To54,TotalAge55To59,LFPRateAge55To59,EmpRatioAge55To59,UnempRateAge55To59,TotalAge60To64,LFPRateAge60To64,EmpRatioAge60To64,UnempRateAge60To64,TotalAge65To74,LFPRateAge65To74,EmpRatioAge65To74,UnempRateAge65To74,TotalAge75AndOver,LFPRateAge75AndOver,EmpRatioAge75AndOver,UnempRateAge75AndOver,TotalWhite,LFPRateWhite,EmpRatioWhite,UnempRateWhite,TotalBlack,LFPRateBlack,EmpRatioBlack,UnempRateBlack,TotalNative,LFPRateNative,EmpRatioNative,UnempRateNative,TotalAsian,LFPRateAsian,EmpRatioAsian,UnempRateAsian,TotalPacificIslander,LFPRatePacificIslander,EmpRatioPacificIslander,UnempRatePacificIslander,TotalOtherRace,LFPRateOtherRace,EmpRatioOtherRace,UnempRateOtherRace,Total2Plus,LFPRate2Plus,EmpRatio2Plus,UnempRate2Plus,TotalHispanic,LFPRateHispanic,EmpRatioHispanic,UnempRateHispanic,TotalWhiteNonHispanic,LFPRateWhiteNonHispanic,EmpRatioWhiteNonHispanic,UnempRateWhiteNonHispanic,Total20To64,LFPRate20To64,EmpRatio20To64,UnempRate20To64,Total20To64Male,LFPRate20To64Male,EmpRatio20To64Male,UnempRate20To64Male,Total20To64Female,LFPRate20To64Female,EmpRatio20To64Female,UnempRate20To64Female,Total20To64FemaleChildrenUnder18,LFPRate20To64FemaleChildrenUnder18,EmpRatio20To64FemaleChildrenUnder18,UnempRate20To64FemaleChildrenUnder18,Total20To64FemaleChildrenUnder6,LFPRate20To64FemaleChildrenUnder6,EmpRatio20To64FemaleChildrenUnder6,UnempRate20To64FemaleChildrenUnder6,Total20To64FemaleChildrenUnder6And6To17,LFPRate20To64FemaleChildrenUnder6And6To17,EmpRatio20To64FemaleChildrenUnder6And6To17,UnempRate20To64FemaleChildrenUnder6And6To17,Total20To64FemaleChildren6To17,LFPRate20To64FemaleChildren6To17,EmpRatio20To64FemaleChildren6To17,UnempRate20To64FemaleChildren6To17,TotalBPL,LFPRateBPL,EmpRatioBPL,UnempRateBPL,TotalAPL,LFPRateAPL,EmpRatioAPL,UnempRateAPL,TotalDisabled,LFPRateDisabled,EmpRatioDisabled,UnempRateDisabled,TotalEdu25To64,LFPRateEdu25To64,EmpRatioEdu25To64,UnempRateEdu25To64,TotalEdu25To64LessHS,LFPRateEdu25To64LessHS,EmpRatioEdu25To64LessHS,UnempRateEdu25To64LessHS,TotalEdu25To64HS,LFPRateEdu25To64HS,EmpRatioEdu25To64HS,UnempRateEdu25To64HS,TotalEdu25To64SomeCollege,LFPRateEdu25To64SomeCollege,EmpRatioEdu25To64SomeCollege,UnempRateEdu25To64SomeCollege,TotalEdu25To64Bachelors,LFPRateEdu25To64Bachelors,EmpRatioEdu25To64Bachelors,UnempRateEdu25To64Bachelors
0,1,1400000US13007960200,13007960200,960200,Baker County,2017,517.0,311.0,253.0,206.0,10.6,1.6,0.0,24.3,1.4,0.0,0.0,3.4,13.0,9.3,11.5,18.4,20.7,7.7,9.5,40.3,12.0,12.5,12.3,11.2,19.0,31.5,32.4,0.0,12.8,19.6,21.3,2.4,0.0,0.0,0.0,0.0,6.6,10.9,4.7,0.0,4.1,6.8,8.3,0.0,45486.0,54926.0,52574.0,28106.0,58316.0,80776.0,NaN,24407.0,1135.0,523.0,612.0,36.0,24.0,12.0,33.0,0.0,33.0,76.0,50.0,26.0,89.0,33.0,56.0,51.0,34.0,17.0,48.0,8.0,40.0,60.0,21.0,39.0,81.0,56.0,25.0,40.0,13.0,27.0,57.0,43.0,14.0,28.0,15.0,13.0,83.0,11.0,72.0,147.0,86.0,61.0,151.0,61.0,90.0,65.0,27.0,38.0,75.0,34.0,41.0,0.0,0.0,0.0,15.0,7.0,8.0,1050.0,771.0,257.0,6.0,0.0,16.0,0.0,0.0,0.0,0.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,957.0,50.3,49.6,1.2,56.0,0.0,0.0,NaN,51.0,82.4,82.4,0.0,48.0,93.8,93.8,0.0,60.0,85.0,76.7,9.8,121.0,75.2,74.4,1.1,85.0,76.5,76.5,0.0,83.0,89.2,89.2,0.0,147.0,38.8,38.8,0.0,216.0,19.9,19.9,0.0,90.0,14.4,14.4,0.0,695.0,52.4,52.2,0.3,240.0,39.6,37.5,5.3,6.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,16.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,67.0,67.2,67.2,0.0,628.0,50.8,50.6,0.3,595.0,71.4,70.4,1.4,287.0,72.8,72.8,0.0,308.0,70.1,68.2,2.8,73.0,53.4,46.6,12.8,9.0,0.0,0.0,NaN,21.0,100.0,76.2,23.8,43.0,41.9,41.9,0.0,70.0,8.6,0.0,100.0,525.0,79.8,79.8,0.0,109.0,58.7,57.8,1.6,544.0,70.4,69.3,1.6,40.0,12.5,0.0,100.0,248.0,69.4,69.0,0.6,214.0,76.6,76.6,0.0,42.0,100.0,100.0,0.0
1,2,1400000US13007960100,13007960100,960100,Baker County,2017,804.0,528.0,345.0,276.0,21.9,11.0,10.1,42.8,6.7,7.4,4.9,5.4,6.8,3.0,4.6,14.1,7.6,10.4,7.0,3.3,12.9,12.1,13.3,13.4,24.1,30.5,28.4,13.4,7.0,10.6,16.2,0.0,11.2,12.3,11.3,7.6,1.2,1.9,2.9,0.0,0.5,0.8,1.2,0.0,43594.0,52614.0,54844.0,17083.0,48346.0,57024.0,NaN,31070.0,2116.0,1024.0,1092.0,91.0,41.0,50.0,120.0,53.0,67.0,156.0,96.0,60.0,141.0,94.0,47.0,150.0,32.0,118.0,190.0,142.0,48.0,94.0,60.0,34.0,84.0,38.0,46.0,122.0,48.0,74.0,160.0,94.0,66.0,223.0,119.0,104.0,119.0,33.0,86.0,153.0,63.0,90.0,106.0,49.0,57.0,99.0,44.0,55.0,27.0,11.0,16.0,55.0,7.0,48.0,26.0,0.0,26.0,2027.0,924.0,1085.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,89.0,37.0,7.0,0.0,0.0,0.0,45.0,0.0,0.0,0.0,1722.0,48.7,47.1,3.2,114.0,16.7,14.9,10.5,150.0,52.0,52.0,0.0,190.0,55.8,55.8,0.0,94.0,78.7,67.0,14.9,206.0,57.8,57.8,0.0,383.0,66.8,65.3,2.3,119.0,80.7,73.9,8.3,153.0,42.5,42.5,0.0,205.0,12.2,12.2,0.0,108.0,0.0,0.0,NaN,817.0,59.6,58.0,2.7,852.0,37.3,35.7,4.4,0.0,NaN,NaN,NaN,8.0,100.0,100.0,0.0,0.0,NaN,NaN,NaN,45.0,55.6,55.6,0.0,0.0,NaN,NaN,NaN,64.0,68.8,68.8,0.0,798.0,58.6,57.0,2.8,1295.0,61.3,59.4,3.1,629.0,57.7,55.0,4.7,666.0,64.7,63.5,1.9,216.0,67.6,67.6,0.0,89.0,42.7,42.7,0.0,21.0,76.2,76.2,0.0,106.0,86.8,86.8,0.0,277.0,16.2,16.2,0.0,1018.0,73.6,71.1,3.3,241.0,28.2,23.7,16.2,1145.0,62.5,60.3,3.5,295.0,42.7,42.7,0.0,383.0,65.5,61.9,5.6,331.0,71.9,68.6,4.6,136.0,74.3,74.3,0.0
2,3,1400000US13321950600,13321950600,950600,Worth County,2017,854.0,653.0,591.0,201.0,4.1,0.8,0.8,14.9,4.8,4.0,3.0,7.5,16.0,15.5,16.2,17.9,14.6,9.2,10.2,32.3,16.4,15.8,16.6,18.4,23.1,29.4,29.8,2.5,11.4,12.9,12.4,6.5,4.9,6.4,5.8,0.0,4.0,5.2,4.2,0.0,0.7,0.9,1.0,0.0,38649.0,51969.0,51156.0,27120.0,54027.0,61804.0,NaN,28761.0,2264.0,1369.0,895.0,114.0,84.0,30.0,158.0,153.0,5.0,138.0,107.0,31.0,86.0,59.0,27.0,125.0,57.0,68.0,109.0,63.0,46.0,138.0,87.0,51.0,116.0,79.0,37.0,149.0,90.0,59.0,135.0,50.0,85.0,158.0,121.0,37.0,223.0,77.0,146.0,156.0,72.0,84.0,232.0,156.0,76.0,126.0,68.0,58.0,70.0,35.0,35.0,21.0,11.0,10.0,10.0,0.0,10.0,2030.0,1745.0,285.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,234.0,155.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,1818.0,58.7,52.9,9.6,50.0,24.0,0.0,100.0,125.0,100.0,68.8,28.3,109.0,91.7,91.7,0.0,138.0,50.0,35.5,29.0,265.0,80.8,78.1,3.3,293.0,58.7,56.0,4.7,223.0,70.0,63.2,9.6,156.0,52.6,52.6,0.0,358.0,37.2,35.5,4.5,101.0,5.0,5.0,0.0,1483.0,60.7,54.8,9.3,280.0,54.6,47.9,12.4,55.0,27.3,27.3,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,94.0,57.4,57.4,0.0,1444.0,59.6,53.5,9.7,1309.0,70.1,63.3,9.2,696.0,80.5,74.3,6.8,613.0,58.4,50.9,12.8,166.0,59.0,47.0,20.4,14.0,100.0,100.0,0.0,37.0,32.4,32.4,0.0,115.0,62.6,45.2,27.8,181.0,60.2,37.6,34.6,1128.0,71.7,67.5,5.9,245.0,51.8,42.0,18.9,1184.0,67.0,62.8,6.3,205.0,59.5,59.5,0.0,430.0,65.1,58.6,10.0,450.0,66.7,61.8,7.3,99.0,91.9,91.9,0.0
3,4,1400000US13321950500,13321950500,950500,Worth County,2017,1674.0,1135.0,642.0,539.0,18.2,17.8,1.9,18.9,6.5,2.6,0.0,14.8,10.8,6.5,7.5,21.7,12.4,11.5,11.4,14.3,14.8,18.3,9.7,6.7,17.7,21.2,32.9,9.3,13.8,13.6,21.8,14.3,3.8,5.6,10.0,0.0,1.5,2.2,3.9,0.0,0.4,0.6,1.1,0.0,36458.0,44208.0,66090.0,23059.0,44636.0,50183.0,NaN,32214.0,4027.0,1984.0,2043.0,197.0,72.0,125.0,250.0,152.0,98.0,120.0,41.0,79.0,300.0,218.0,82.0,424.0,222.0,202.0,201.0,81.0,120.0,212.0,64.0,148.0,91.0,31.0,60.0,351.0,178.0,173.0,174.0,81.0,93.0,414.0,227.0,187.0,286.0,163.0,123.0,306.0,174.0,132.0,156.0,61.0,95.0,227.0,83.0,144.0,119.0,59.0,60.0,84.0,48.0,36.0,115.0,29.0,86.0,3968.0,1842.0,1906.0,0.0,32.0,0.0,76.0,112.0,11.0,101.0,59.0,32.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,3432.0,56.8,52.6,7.4,272.0,37.9,37.9,0.0,424.0,72.2,57.8,19.9,201.0,67.2,61.7,8.1,212.0,56.1,32.5,42.0,442.0,77.8,74.2,4.7,588.0,78.7,77.7,1.3,286.0,65.4,65.4,0.0,306.0,58.5,58.5,0.0,383.0,27.7,27.7,0.0,318.0,2.2,2.2,0.0,1655.0,53.4,51.7,3.2,1646.0,58.0,50.9,12.2,0.0,NaN,NaN,NaN,32.0,71.9,71.9,0.0,0.0,NaN,NaN,NaN,71.0,100.0,100.0,0.0,28.0,60.7,60.7,0.0,59.0,89.8,89.8,0.0,1623.0,52.9,51.1,3.3,2459.0,70.5,64.6,8.3,1221.0,79.2,69.7,12.0,1238.0,61.9,59.6,3.7,408.0,66.7,64.0,4.0,79.0,88.6,88.6,0.0,37.0,100.0,70.3,29.7,292.0,56.5,56.5,0.0,458.0,33.8,27.9,17.4,1971.0,80.1,74.1,7.4,283.0,21.6,21.6,0.0,2035.0,70.1,66.0,5.8,317.0,47.6,31.9,33.1,974.0,63.4,62.8,1.0,569.0,86.8,84.9,2.2,175.0,93.7,84.6,9.8
4,5,1400000US13321950400,13321950400,950400,Worth County,2017,1573.0,1163.0,949.0,410.0,7.0,1.2,1.3,23.4,7.9,7.1,3.3,10.2,15.9,14.4,10.4,20.5,10.2,8.9,8.3,13.9,17.5,18.4,21.2,14.9,16.7,18.1,18.8,13.4,12.8,16.3,18.9,1.7,6.5,8.1,8.6,2.0,3.9,5.3,6.5,0.0,1.7,2.2,2.7,0.0,43720.0,50096.0,58359.0,24076.0,59481.0,70036.0,NaN,29068.0,4393.0,2168.0,2225.0,274.0,117.0,157.0,240.0,146.0,94.0,382.0,183.0,199.0,370.0,154.0,216.0,243.0,136.0,107.0,194.0,106.0,88.0,272.0,159.0,113.0,244.0,70.0,174.0,251.0,185.0,66.0,278.0,108.0,170.0,249.0,132.0,117.0,398.0,251.0,147.0,252.0,92.0,160.0,201.0,113.0,88.0,212.0,98.0,114.0,152.0,60.0,92.0,78.0,22.0,56.0,103.0,36.0,67.0,4341.0,3360.0,923.0,0.0,16.0,0.0,0.0,42.0,0.0,42.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3389.0,55.4,50.2,9.4,262.0,40.5,27.5,32.1,243.0,80.2,79.0,1.5,194.0,64.4,51.0,20.8,272.0,71.3,64.3,9.8,495.0,77.8,75.2,3.4,527.0,80.1,78.0,2.6,398.0,68.1,57.5,15.5,252.0,50.0,38.5,23.0,413.0,9.0,9.0,0.0,333.0,5.4,5.4,0.0,2632.0,59.2,54.1,8.5,699.0,45.8,39.5,13.8,0.0,NaN,NaN,NaN,16.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,42.0,4.8,4.8,0.0,0.0,NaN,NaN,NaN,2632.0,59.2,54.1,8.5,2381.0,72.2,66.1,8.3,1239.0,81.8,75.7,7.5,1142.0,61.6,55.8,9.5,412.0,75.0,64.1,14.6,47.0,72.3,61.7,14.7,75.0,94.7,69.3,26.8,290.0,70.3,63.1,10.3,456.0,52.4,44.1,15.9,1925.0,76.8,71.4,7.1,485.0,36.1,22.9,36.6,2138.0,71.2,64.7,9.2,438.0,56.8,49.5,12.9,748.0,72.9,65.5,10.1,705.0,76.3,70.5,7.6,247.0,77.3,72.5,6.3

In [68]:
bg_tract = pd.read_csv(path+'TestDB/Ship/BGJunctTract_v02.csv')

In [72]:
df_bg = pd.read_csv(path+'TestDB/Ship/BlockGroup_v03.csv')

In [88]:
df_bg.iloc[555:558]

,BlockGroupID,BlockGroupTract,GEO.id,Year,GEO.id2,Tract,BlockGroup,County,TotalMale,MaleUnder5,Male5To9,Male10To14,Male15To17,Male18And19,Male20,Male21,Male22To24,Male25To29,Male30To34,Male35To39,Male40To44,Male45To49,Male50To54,Male55To59,Male60And61,Male62To64,Male65And66,Male67To69,Male70To74,Male75To79,Male80To84,Male85AndOver,TotalFemale,FemaleUnder5,Female5To9,Female10To14,Female15To17,Female18And19,Female20,Female21,Female22To24,Female25To29,Female30To34,Female35To39,Female40To44,Female45To49,Female50To54,Female55To59,Female60And61,Female62To64,Female65And66,Female67To69,Female70To74,Female75To79,Female80To84,Female85AndOver,TotalLabor,TotalInLaborforce,TotalCivilLabor,EmployedCivlLabor,UnemployedCivilLabor,TotalArmedForces,TotalNotInLaborforce,TotalPopulation,TotalLessThan10k,Total10kTo14999,Total15kTo19999,Total20kTo24999,Total25kTo29999,Total30kTo34999,Total35kTo39999,Total40kTo44999,Total45kTo49999,Total50kTo59999,Total60kTo74999,Total75kTo99999,Total100kTo124999,Total125kTo149999,Total150kTo199999,Total200kOrMore,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,TotalHomes,TotalOccupiedHomes,TotalVacantHomes,TotalOwnedHomes,TotalRentedHomes
555,556,NOT FOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
bg_tract[bg_tract['TractID']==346]

      BlockGroupID  TractID
4440           556      346

In [94]:
bg_tract.loc[4440, 'TractID'] = 345

In [85]:
df_tract.tail()

,TractID,GEO.id,GEO.id2,Tract,County,Year,HTotal,FTotal,MTotal,NfTotal,HIncomeLessThan10k,FIncomeLessThan10k,MIncomeLessThan10k,NfIncomeLessThan10k,HIncome10kTo14999,FIncome10kTo14999,MIncome10kTo14999,NfIncome10kTo14999,HIncome15kTo24999,FIncome15kTo24999,MIncome15kTo24999,NfIncome15kTo24999,HIncome25kTo34999,FIncome25kTo34999,MIncome25kTo34999,NfIncome25kTo34999,HIncome35kTo49999,FIncome35kTo49999,MIncome35kTo49999,NfIncome35kTo49999,HIncome50kTo74999,FIncome50kTo74999,MIncome50kTo74999,NfIncome50kTo74999,HIncome75kTo99999,FIncome75kTo99999,MIncome75kTo99999,NfIncome75kTo99999,HIncome100kTo149999,FIncome100kTo149999,MIncome100kTo149999,NfIncome100kTo149999,HIncome150kTo199999,FIncome150kTo199999,MIncome150kTo199999,NfIncome150kTo199999,HIncome200kOrMore,FIncome200kOrMore,MIncome200kOrMore,NfIncome200kOrMore,HIncomeMedian,FIncomeMedian,MIncomeMedian,NfIncomeMedian,HIncomeMean,FIncomeMean,MIncomeMean,NfIncomeMean,TotalPopulation,MaleTotal,FemaleTotal,TotalAgeUnder5,MaleAgeUnder5,FemaleAgeUnder5,TotalAge5To9,MaleAge5To9,FemaleAge5To9,TotalAge10To14,MaleAge10To14,FemaleAge10To14,TotalAge15To19,MaleAge15To19,FemaleAge15To19,TotalAge20To24,MaleAge20To24,FemaleAge20To24,TotalAge25To29,MaleAge25To29,FemaleAge25To29,TotalAge30To34,MaleAge30To34,FemaleAge30To34,TotalAge35To39,MaleAge35To39,FemaleAge35To39,TotalAge40To44,MaleAge40To44,FemaleAge40To44,TotalAge45To49,MaleAge45To49,FemaleAge45To49,TotalAge50To54,MaleAge50To54,FemaleAge50To54,TotalAge55To59,MaleAge55To59,FemaleAge55To59,TotalAge60To64,MaleAge60To64,FemaleAge60To64,TotalAge65To69,MaleAge65To69,FemaleAge65To69,TotalAge70To74,MaleAge70To74,FemaleAge70To74,TotalAge75To79,MaleAge75To79,FemaleAge75To79,TotalAge80To84,MaleAge80To84,FemaleAge80To84,TotalAge85AndOver,MaleAge85AndOver,FemaleAge85AndOver,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,Total16AndOver,LFPRate16AndOver,EmpRatio16AndOver,UnempRate16AndOver,TotalAge16To19,LFPRateAge16To19,EmpRatioAge16To19,UnempRateAge16To19,TotalAge20To24,LFPRateAge20To24,EmpRatioAge20To24,UnempRateAge20To24,TotalAge25To29,LFPRateAge25To29,EmpRatioAge25To29,UnempRateAge25To29,TotalAge30To34,LFPRateAge30To34,EmpRatioAge30To34,UnempRateAge30To34,TotalAge35To44,LFPRateAge35To44,EmpRatioAge35To44,UnempRateAge35To44,TotalAge45To54,LFPRateAge45To54,EmpRatioAge45To54,UnempRateAge45To54,TotalAge55To59,LFPRateAge55To59,EmpRatioAge55To59,UnempRateAge55To59,TotalAge60To64,LFPRateAge60To64,EmpRatioAge60To64,UnempRateAge60To64,TotalAge65To74,LFPRateAge65To74,EmpRatioAge65To74,UnempRateAge65To74,TotalAge75AndOver,LFPRateAge75AndOver,EmpRatioAge75AndOver,UnempRateAge75AndOver,TotalWhite,LFPRateWhite,EmpRatioWhite,UnempRateWhite,TotalBlack,LFPRateBlack,EmpRatioBlack,UnempRateBlack,TotalNative,LFPRateNative,EmpRatioNative,UnempRateNative,TotalAsian,LFPRateAsian,EmpRatioAsian,UnempRateAsian,TotalPacificIslander,LFPRatePacificIslander,EmpRatioPacificIslander,UnempRatePacificIslander,TotalOtherRace,LFPRateOtherRace,EmpRatioOtherRace,UnempRateOtherRace,Total2Plus,LFPRate2Plus,EmpRatio2Plus,UnempRate2Plus,TotalHispanic,LFPRateHispanic,EmpRatioHispanic,UnempRateHispanic,TotalWhiteNonHispanic,LFPRateWhiteNonHispanic,EmpRatioWhiteNonHispanic,UnempRateWhiteNonHispanic,Total20To64,LFPRate20To64,EmpRatio20To64,UnempRate20To64,Total20To64Male,LFPRate20To64Male,EmpRatio20To64Male,UnempRate20To64Male,Total20To64Female,LFPRate20To64Female,EmpRatio20To64Female,UnempRate20To64Female,Total20To64FemaleChildrenUnder18,LFPRate20To64FemaleChildrenUnder18,EmpRatio20To64FemaleChildrenUnder18,UnempRate20To64FemaleChildrenUnder18,Total20To64FemaleChildrenUnder6,LFPRate20To64FemaleChildrenUnder6,EmpRatio20To64FemaleChildrenUnder6,UnempRate20To64FemaleChildrenUnder6,Total20To64FemaleChildrenUnder6And6To17,LFPRate20To64FemaleChildrenUnder6And6To17,EmpRatio20To64FemaleChildrenUnder6And6To17,UnempRate20To64FemaleChildrenUnder6And6To17,Total20To64FemaleChildren6To17,LFPRate20To64FemaleChildren6To17,EmpRatio20To64FemaleChildren6To17,UnempRate20To64FemaleChildren6To17,TotalBPL,LFPRateBPL,EmpRatioBPL,UnempRateBPL,TotalAPL,LFPRateAPL,EmpRatioAPL,UnempRateAPL,TotalDisabled,LFPRateDisabled,EmpRatioDisabled,UnempRateDisabled,TotalEdu25To64,LFPRateEdu25To64,EmpRatioEdu25To64,UnempRateEdu25To64,TotalEdu25To64LessHS,LFPRateEdu25To64LessHS,EmpRatioEdu25To64LessHS,UnempRateEdu25To64LessHS,TotalEdu25To64HS,LFPRateEdu25To64HS,EmpRatioEdu25To64HS,UnempRateEdu25To64HS,TotalEdu25To64SomeCollege,LFPRateEdu25To64SomeCollege,EmpRatioEdu25To64SomeCollege,UnempRateEdu25To64SomeCollege,TotalEdu25To64Bachelors,LFPRateEdu25To64Bachelors,EmpRatioEdu25To64Bachelors,UnempRateEdu25To64Bachelors
339,340,1400000US13095010402,13095010402,10402,Dougherty County,2010,1217.0,940.0,514.0,277.0,3.8,4.4,0.0,1.8,5.3,1.8,1.4,17.0,20.0,15.0,0.0,37.2,8.3,7.2,6.0,17.0,12.7,12.4,9.5,13.4,23.6,27.1,26.7,6.5,12.0,13.4,22.4,7.2,7.1,9.1,16.7,0.0,3.2,4.1,7.6,0.0,4.1,5.3,9.7,0.0,49861.0,58477.0,77115.0,17325.0,70675.0,82942.0,NaN,27409.0,3350.0,1544.0,1806.0,7.8,12.3,3.9,13.0,11.5,14.3,8.3,10.6,6.3,7.3,6.3,8.1,7.9,9.8,6.3,5.5,4.1,6.7,9.1,9.1,9.0,6.1,5.3,6.8,7.9,5.8,9.6,6.9,4.0,9.5,7.1,8.4,6.0,3.6,4.1,3.2,2.4,1.7,3.0,1.4,2.0,0.9,1.9,0.6,3.0,2.3,3.4,1.4,0.6,0.8,0.3,0.8,0.0,1.5,3330.0,626.0,2640.0,15.0,0.0,0.0,0.0,49.0,0.0,49.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2327.0,NaN,NaN,8.6,197.0,NaN,NaN,6.7,265.0,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,470.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0,NaN,NaN,50.0,124.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,0.0,20.0,NaN,NaN,0.0,502.0,NaN,NaN,2.8,1895.0,NaN,NaN,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1630.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,341,1400000US13095010401,13095010401,10401,Dougherty County,2010,2404.0,1919.0,1648.0,485.0,1.1,0.7,0.0,2.7,1.6,0.0,0.0,8.0,4.2,1.4,0.0,15.3,4.6,2.0,1.2,15.1,15.6,17.2,14.7,9.3,15.7,16.8,17.2,11.5,17.3,20.2,19.1,5.8,23.3,23.0,26.8,24.1,5.3,6.7,7.8,0.0,11.3,12.1,13.2,8.2,88365.0,90991.0,95972.0,47212.0,113926.0,120407.0,NaN,88282.0,6382.0,3102.0,3280.0,8.7,11.8,5.9,6.6,10.2,3.2,6.5,5.3,7.7,6.4,6.6,6.3,4.0,3.7,4.3,4.6,5.6,3.6,4.4,4.6,4.1,7.6,5.3,9.9,8.6,7.6,9.6,5.0,4.6,5.4,8.4,6.6,10.1,8.6,8.6,8.7,6.2,6.3,6.1,5.8,5.6,5.9,3.6,3.0,4.2,3.1,3.9,2.3,0.3,0.4,0.3,1.4,0.4,2.3,6342.0,4380.0,1762.0,0.0,134.0,0.0,0.0,66.0,0.0,66.0,40.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4858.0,NaN,NaN,3.0,281.0,NaN,NaN,0.0,255.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,854.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.0,NaN,NaN,11.0,310.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,0.0,20.0,NaN,NaN,NaN,3310.0,NaN,NaN,2.6,3667.0,NaN,NaN,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3412.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,342,1400000US13095010302,13095010302,10302,Dougherty County,2010,1742.0,1073.0,377.0,669.0,17.7,14.2,2.1,26.5,10.3,13.1,0.0,13.8,32.0,23.3,9.5,34.8,13.9,15.8,19.9,21.4,8.3,13.5,26.5,0.0,12.7,11.9,18.6,3.6,1.4,2.3,6.6,0.0,1.7,2.7,7.7,0.0,1.5,2.4,6.9,0.0,0.5,0.7,2.1,0.0,21527.0,24668.0,48411.0,16353.0,31210.0,36882.0,NaN,18684.0,5663.0,3073.0,2590.0,5.5,5.8,5.1,5.0,3.2,7.1,9.1,10.0,8.0,9.8,10.5,8.9,12.8,14.2,11.2,6.3,6.7,5.9,5.6,5.8,5.3,9.7,9.9,9.5,9.4,7.0,12.2,9.8,10.8,8.6,6.0,6.8,5.0,3.3,3.0,3.7,2.5,3.1,1.9,2.7,1.4,4.3,1.5,1.3,1.7,0.3,0.5,0.2,0.6,0.0,1.4,0.1,0.0,0.2,5636.0,520.0,5029.0,0.0,0.0,0.0,0.0,87.0,0.0,87.0,27.0,9.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,4474.0,NaN,NaN,11.1,468.0,NaN,NaN,43.6,727.0,NaN,NaN,10.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,893.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.0,NaN,NaN,60.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,NaN,NaN,0.0,27.0,NaN,NaN,NaN,463.0,NaN,NaN,16.5,3708.0,NaN,NaN,9.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2981.0,NaN,NaN,8.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,343,1400000US13095001000,13095001000,1000,Dougherty County,2010,715.0,419.0,184.0,296.0,10.5,1.4,3.3,23.3,8.7,9.3,0.0,7.8,20.8,14.6,8.2,29.7,29.2,36.8,29.3,18.6,15.0,21.0,20.7,6.4,5.5,7.2,16.3,3.0,10.3,9.8,22.3,11.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27997.0,29320.0,39074.0,22500.0,32939.0,36311.0,NaN,27864.0,1836.0,709.0,1127.0,5.1,5.1,5.1,4.9,3.9,5.5,6.8,3.7,8.7,12.6,19.0,8.6,14.8,15.0,14.6,8.5,7.3,9.2,2.5,0.0,4.1,5.2,1.4,7.6,5.3,13.8,0.0,9.1,5.6,11.3,4.6,4.7,4.5,5.2,4.4,5.8,2.3,3.7,1.4,2.3,6.1,0.0,2.6,0.0,4.2,2.1,2.4,2.0,3.0,3.9,2.4,3.1,0.0,5.1,1836.0,575.0,1211.0,0.0,30.0,0.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1491.0,NaN,NaN,15.7,194.0,NaN,NaN,16.3,271.0,NaN,NaN,31.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,251.0,NaN,NaN,10.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,151.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,543.0,NaN,NaN,31.8,1056.0,NaN,NaN,15.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,785.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,344,1400000US13095000100,13095000100,100,Dougherty County,2010,2221.0,1287.0,475.0,934.0,17.2,21.0,0.0,18.5,15.1,7.6,10.3,19.1,29.6,29.8,18.7,29.3,9.1,5.1,6.5,16.8,15.0,20.9,30.3,4.7,6.1,5.5,6.7,7.8,4.3,7.4,20.0,0.0,2.4,0.9,2.3,3.7,1.1,1.9,5.1,0.0,0.0,0.0,0.0,0.0,20240.0,21458.0,39730.0,18892.0,28941.0,31479.0,NaN,24240.0,5976.0,2357.0,3619.0,13.3,17.6,10.6,9.1,10.6,8.1,10.1,14.8,7.0,6.5,4.6,7.7,13.8,7.3,18.0,7.1,6.4,7.5,5.9,6.9,5.3,4.1,3.7,4.3,5.2,6.2,4.5,4.3,2.7,5.3,6.9,7.6,6.4,2.8,2.5,3.0,4.1,4.3,3.9,2.5,2.2,2.6,1.8,1.3,2.2,0.5,0.6,0.4,1.8,0.6,2.6,0.4,0.0,0.7,5594.0,592.0,4901.0,48.0,0.0,0.0,0.0,53.0,0.0,53.0,382.0,228.0,30.0,0.0,0.0,0.0,124.0,0.0,0.0,0.0,3819.0,NaN,NaN,13.2,170.0,NaN,NaN,14.7,824.0,NaN,NaN,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,666.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0,NaN,NaN,48.5,162.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,NaN,NaN,100.0,322.0,NaN,NaN,0.0,540.0,NaN,NaN,0.0,3231.0,NaN,NaN,12.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2407.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
lis = [345, "", np.nan, -1, ""]
lis.extend([np.nan]*270)
not_found_entry = pd.DataFrame([lis], columns=list(df_tract))
df_tract = df_tract.append(not_found_entry, ignore_index=True)

In [95]:
df_tract.tail()

,TractID,GEO.id,GEO.id2,Tract,County,Year,HTotal,FTotal,MTotal,NfTotal,HIncomeLessThan10k,FIncomeLessThan10k,MIncomeLessThan10k,NfIncomeLessThan10k,HIncome10kTo14999,FIncome10kTo14999,MIncome10kTo14999,NfIncome10kTo14999,HIncome15kTo24999,FIncome15kTo24999,MIncome15kTo24999,NfIncome15kTo24999,HIncome25kTo34999,FIncome25kTo34999,MIncome25kTo34999,NfIncome25kTo34999,HIncome35kTo49999,FIncome35kTo49999,MIncome35kTo49999,NfIncome35kTo49999,HIncome50kTo74999,FIncome50kTo74999,MIncome50kTo74999,NfIncome50kTo74999,HIncome75kTo99999,FIncome75kTo99999,MIncome75kTo99999,NfIncome75kTo99999,HIncome100kTo149999,FIncome100kTo149999,MIncome100kTo149999,NfIncome100kTo149999,HIncome150kTo199999,FIncome150kTo199999,MIncome150kTo199999,NfIncome150kTo199999,HIncome200kOrMore,FIncome200kOrMore,MIncome200kOrMore,NfIncome200kOrMore,HIncomeMedian,FIncomeMedian,MIncomeMedian,NfIncomeMedian,HIncomeMean,FIncomeMean,MIncomeMean,NfIncomeMean,TotalPopulation,MaleTotal,FemaleTotal,TotalAgeUnder5,MaleAgeUnder5,FemaleAgeUnder5,TotalAge5To9,MaleAge5To9,FemaleAge5To9,TotalAge10To14,MaleAge10To14,FemaleAge10To14,TotalAge15To19,MaleAge15To19,FemaleAge15To19,TotalAge20To24,MaleAge20To24,FemaleAge20To24,TotalAge25To29,MaleAge25To29,FemaleAge25To29,TotalAge30To34,MaleAge30To34,FemaleAge30To34,TotalAge35To39,MaleAge35To39,FemaleAge35To39,TotalAge40To44,MaleAge40To44,FemaleAge40To44,TotalAge45To49,MaleAge45To49,FemaleAge45To49,TotalAge50To54,MaleAge50To54,FemaleAge50To54,TotalAge55To59,MaleAge55To59,FemaleAge55To59,TotalAge60To64,MaleAge60To64,FemaleAge60To64,TotalAge65To69,MaleAge65To69,FemaleAge65To69,TotalAge70To74,MaleAge70To74,FemaleAge70To74,TotalAge75To79,MaleAge75To79,FemaleAge75To79,TotalAge80To84,MaleAge80To84,FemaleAge80To84,TotalAge85AndOver,MaleAge85AndOver,FemaleAge85AndOver,NonHispanic,NonHispanicWhite,NonHispanicBlack,NonHispanicNative,NonHispanicAsian,NonHispanicPacificIslander,NonHispanicOtherRace,NonHispanic2Plus,NonHispanic2PlusIncOther,NonHispanic2PlusExcOther,Hispanic,HispanicWhite,HispanicBlack,HispanicNative,HispanicAsian,HispanicPacificIslander,HispanicOtherRace,Hispanic2Plus,Hispanic2PlusIncOther,Hispanic2PlusExcOther,Total16AndOver,LFPRate16AndOver,EmpRatio16AndOver,UnempRate16AndOver,TotalAge16To19,LFPRateAge16To19,EmpRatioAge16To19,UnempRateAge16To19,TotalAge20To24,LFPRateAge20To24,EmpRatioAge20To24,UnempRateAge20To24,TotalAge25To29,LFPRateAge25To29,EmpRatioAge25To29,UnempRateAge25To29,TotalAge30To34,LFPRateAge30To34,EmpRatioAge30To34,UnempRateAge30To34,TotalAge35To44,LFPRateAge35To44,EmpRatioAge35To44,UnempRateAge35To44,TotalAge45To54,LFPRateAge45To54,EmpRatioAge45To54,UnempRateAge45To54,TotalAge55To59,LFPRateAge55To59,EmpRatioAge55To59,UnempRateAge55To59,TotalAge60To64,LFPRateAge60To64,EmpRatioAge60To64,UnempRateAge60To64,TotalAge65To74,LFPRateAge65To74,EmpRatioAge65To74,UnempRateAge65To74,TotalAge75AndOver,LFPRateAge75AndOver,EmpRatioAge75AndOver,UnempRateAge75AndOver,TotalWhite,LFPRateWhite,EmpRatioWhite,UnempRateWhite,TotalBlack,LFPRateBlack,EmpRatioBlack,UnempRateBlack,TotalNative,LFPRateNative,EmpRatioNative,UnempRateNative,TotalAsian,LFPRateAsian,EmpRatioAsian,UnempRateAsian,TotalPacificIslander,LFPRatePacificIslander,EmpRatioPacificIslander,UnempRatePacificIslander,TotalOtherRace,LFPRateOtherRace,EmpRatioOtherRace,UnempRateOtherRace,Total2Plus,LFPRate2Plus,EmpRatio2Plus,UnempRate2Plus,TotalHispanic,LFPRateHispanic,EmpRatioHispanic,UnempRateHispanic,TotalWhiteNonHispanic,LFPRateWhiteNonHispanic,EmpRatioWhiteNonHispanic,UnempRateWhiteNonHispanic,Total20To64,LFPRate20To64,EmpRatio20To64,UnempRate20To64,Total20To64Male,LFPRate20To64Male,EmpRatio20To64Male,UnempRate20To64Male,Total20To64Female,LFPRate20To64Female,EmpRatio20To64Female,UnempRate20To64Female,Total20To64FemaleChildrenUnder18,LFPRate20To64FemaleChildrenUnder18,EmpRatio20To64FemaleChildrenUnder18,UnempRate20To64FemaleChildrenUnder18,Total20To64FemaleChildrenUnder6,LFPRate20To64FemaleChildrenUnder6,EmpRatio20To64FemaleChildrenUnder6,UnempRate20To64FemaleChildrenUnder6,Total20To64FemaleChildrenUnder6And6To17,LFPRate20To64FemaleChildrenUnder6And6To17,EmpRatio20To64FemaleChildrenUnder6And6To17,UnempRate20To64FemaleChildrenUnder6And6To17,Total20To64FemaleChildren6To17,LFPRate20To64FemaleChildren6To17,EmpRatio20To64FemaleChildren6To17,UnempRate20To64FemaleChildren6To17,TotalBPL,LFPRateBPL,EmpRatioBPL,UnempRateBPL,TotalAPL,LFPRateAPL,EmpRatioAPL,UnempRateAPL,TotalDisabled,LFPRateDisabled,EmpRatioDisabled,UnempRateDisabled,TotalEdu25To64,LFPRateEdu25To64,EmpRatioEdu25To64,UnempRateEdu25To64,TotalEdu25To64LessHS,LFPRateEdu25To64LessHS,EmpRatioEdu25To64LessHS,UnempRateEdu25To64LessHS,TotalEdu25To64HS,LFPRateEdu25To64HS,EmpRatioEdu25To64HS,UnempRateEdu25To64HS,TotalEdu25To64SomeCollege,LFPRateEdu25To64SomeCollege,EmpRatioEdu25To64SomeCollege,UnempRateEdu25To64SomeCollege,TotalEdu25To64Bachelors,LFPRateEdu25To64Bachelors,EmpRatioEdu25To64Bachelors,UnempRateEdu25To64Bachelors
340,341,1400000US13095010401,1.309501e+10,10401,Dougherty County,2010.0,2404.0,1919.0,1648.0,485.0,1.1,0.7,0.0,2.7,1.6,0.0,0.0,8.0,4.2,1.4,0.0,15.3,4.6,2.0,1.2,15.1,15.6,17.2,14.7,9.3,15.7,16.8,17.2,11.5,17.3,20.2,19.1,5.8,23.3,23.0,26.8,24.1,5.3,6.7,7.8,0.0,11.3,12.1,13.2,8.2,88365.0,90991.0,95972.0,47212.0,113926.0,120407.0,NaN,88282.0,6382.0,3102.0,3280.0,8.7,11.8,5.9,6.6,10.2,3.2,6.5,5.3,7.7,6.4,6.6,6.3,4.0,3.7,4.3,4.6,5.6,3.6,4.4,4.6,4.1,7.6,5.3,9.9,8.6,7.6,9.6,5.0,4.6,5.4,8.4,6.6,10.1,8.6,8.6,8.7,6.2,6.3,6.1,5.8,5.6,5.9,3.6,3.0,4.2,3.1,3.9,2.3,0.3,0.4,0.3,1.4,0.4,2.3,6342.0,4380.0,1762.0,0.0,134.0,0.0,0.0,66.0,0.0,66.0,40.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4858.0,NaN,NaN,3.0,281.0,NaN,NaN,0.0,255.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,854.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.0,NaN,NaN,11.0,310.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,0.0,20.0,NaN,NaN,NaN,3310.0,NaN,NaN,2.6,3667.0,NaN,NaN,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3412.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,342,1400000US13095010302,1.309501e+10,10302,Dougherty County,2010.0,1742.0,1073.0,377.0,669.0,17.7,14.2,2.1,26.5,10.3,13.1,0.0,13.8,32.0,23.3,9.5,34.8,13.9,15.8,19.9,21.4,8.3,13.5,26.5,0.0,12.7,11.9,18.6,3.6,1.4,2.3,6.6,0.0,1.7,2.7,7.7,0.0,1.5,2.4,6.9,0.0,0.5,0.7,2.1,0.0,21527.0,24668.0,48411.0,16353.0,31210.0,36882.0,NaN,18684.0,5663.0,3073.0,2590.0,5.5,5.8,5.1,5.0,3.2,7.1,9.1,10.0,8.0,9.8,10.5,8.9,12.8,14.2,11.2,6.3,6.7,5.9,5.6,5.8,5.3,9.7,9.9,9.5,9.4,7.0,12.2,9.8,10.8,8.6,6.0,6.8,5.0,3.3,3.0,3.7,2.5,3.1,1.9,2.7,1.4,4.3,1.5,1.3,1.7,0.3,0.5,0.2,0.6,0.0,1.4,0.1,0.0,0.2,5636.0,520.0,5029.0,0.0,0.0,0.0,0.0,87.0,0.0,87.0,27.0,9.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,4474.0,NaN,NaN,11.1,468.0,NaN,NaN,43.6,727.0,NaN,NaN,10.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,893.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.0,NaN,NaN,60.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,NaN,NaN,0.0,27.0,NaN,NaN,NaN,463.0,NaN,NaN,16.5,3708.0,NaN,NaN,9.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2981.0,NaN,NaN,8.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,343,1400000US13095001000,1.309500e+10,1000,Dougherty County,2010.0,715.0,419.0,184.0,296.0,10.5,1.4,3.3,23.3,8.7,9.3,0.0,7.8,20.8,14.6,8.2,29.7,29.2,36.8,29.3,18.6,15.0,21.0,20.7,6.4,5.5,7.2,16.3,3.0,10.3,9.8,22.3,11.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27997.0,29320.0,39074.0,22500.0,32939.0,36311.0,NaN,27864.0,1836.0,709.0,1127.0,5.1,5.1,5.1,4.9,3.9,5.5,6.8,3.7,8.7,12.6,19.0,8.6,14.8,15.0,14.6,8.5,7.3,9.2,2.5,0.0,4.1,5.2,1.4,7.6,5.3,13.8,0.0,9.1,5.6,11.3,4.6,4.7,4.5,5.2,4.4,5.8,2.3,3.7,1.4,2.3,6.1,0.0,2.6,0.0,4.2,2.1,2.4,2.0,3.0,3.9,2.4,3.1,0.0,5.1,1836.0,575.0,1211.0,0.0,30.0,0.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1491.0,NaN,NaN,15.7,194.0,NaN,NaN,16.3,271.0,NaN,NaN,31.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,251.0,NaN,NaN,10.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,151.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,543.0,NaN,NaN,31.8,1056.0,NaN,NaN,15.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,785.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,344,1400000US13095000100,1.309500e+10,100,Dougherty County,2010.0,2221.0,1287.0,475.0,934.0,17.2,21.0,0.0,18.5,15.1,7.6,10.3,19.1,29.6,29.8,18.7,29.3,9.1,5.1,6.5,16.8,15.0,20.9,30.3,4.7,6.1,5.5,6.7,7.8,4.3,7.4,20.0,0.0,2.4,0.9,2.3,3.7,1.1,1.9,5.1,0.0,0.0,0.0,0.0,0.0,20240.0,21458.0,39730.0,18892.0,28941.0,31479.0,NaN,24240.0,5976.0,2357.0,3619.0,13.3,17.6,10.6,9.1,10.6,8.1,10.1,14.8,7.0,6.5,4.6,7.7,13.8,7.3,18.0,7.1,6.4,7.5,5.9,6.9,5.3,4.1,3.7,4.3,5.2,6.2,4.5,4.3,2.7,5.3,6.9,7.6,6.4,2.8,2.5,3.0,4.1,4.3,3.9,2.5,2.2,2.6,1.8,1.3,2.2,0.5,0.6,0.4,1.8,0.6,2.6,0.4,0.0,0.7,5594.0,592.0,4901.0,48.0,0.0,0.0,0.0,53.0,0.0,53.0,382.0,228.0,30.0,0.0,0.0,0.0,124.0,0.0,0.0,0.0,3819.0,NaN,NaN,13.2,170.0,NaN,NaN,14.7,824.0,NaN,NaN,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,666.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0,NaN,NaN,48.5,162.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,NaN,NaN,100.0,322.0,NaN,NaN,0.0,540.0,NaN,NaN,0.0,3231.0,NaN,NaN,12.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2407.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,345,,NaN,-1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
bg_tract.to_csv(path+'TestDB/Ship/BGJunctTract_v02.csv', index=False)

In [98]:
df_tract['Year'] = df_tract['Year'].astype('Int64')

In [99]:
df_tract.to_csv(path+'TestDB/Ship/Tract_v04.csv', index=False)