In [1]:
import pandas as pd

Tract 400, 2
501, 2
10, 2

In [25]:
PATH = '/Users/william/Dropbox (Amherst College)/CDS-2019-AlbanyHub/'

In [26]:
df = pd.read_csv(PATH + 'ToDatabase/TotalUtilities.csv')

In [27]:
water = df[df['Service Type'] == "RWTR"]

In [28]:
water[water['Consumption'] > 10000]

,ChargeID,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
6679932,6679932,41755,3701 WOODBURY RD,111137.0,RWTR,300.0,140,10034.0,28.0,TGAL,41.38,2015-07-24,2015,7,24,12173
7504911,7504911,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,47241.0,34.0,TGAL,2062.23,2015-12-11,2015,12,11,30002
8408459,8408459,75823,2503 DAYLOR CT,38577.0,RWTR,300.0,130,21049.0,28.0,TGAL,62.14,2016-04-22,2016,4,22,4764
8593756,8593756,75823.0,2503 DAYLOR CT,38577.0,RWTR,300.0,130,21102.0,34.0,TGAL,108.85,2016-05-24,2016,5,24,4764
14539033,14539033,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,11544.0,31.0,TGAL,2215.94,2019-01-10,2019,1,10,30002

In [29]:
water['Unit of Measure'].value_counts()

TGAL    2630643
Name: Unit of Measure, dtype: int64

In [30]:
water['Charge Amount'].describe()

count    2.630643e+06
mean     2.006524e+01
std      1.003457e+02
min     -1.865640e+03
25%      1.106000e+01
50%      1.345000e+01
75%      2.050000e+01
max      8.648098e+04
Name: Charge Amount, dtype: float64

In [31]:
pd.options.display.max_rows = 1000

In [32]:
water[water['Premise Address'].str.contains("333 S MOCK RD")]

,ChargeID,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
10675,10675,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,491.0,33.0,TGAL,1318.59,2012-01-10,2012,1,10,30002
11205,11205,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,428.0,33.0,TGAL,1217.52,2012-01-10,2012,1,10,30002
174623,174623,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,452.0,28.0,TGAL,1237.08,2012-02-08,2012,2,8,30002
175148,175148,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,488.0,28.0,TGAL,1342.92,2012-02-08,2012,2,8,30002
341829,341829,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,550.0,30.0,TGAL,1441.90,2012-03-08,2012,3,8,30002
342341,342341,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,528.0,29.0,TGAL,1426.52,2012-03-08,2012,3,8,30002
507996,507996,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,654.0,32.0,TGAL,1629.10,2012-04-09,2012,4,9,30002
508523,508523,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,479.0,30.0,TGAL,1324.11,2012-04-09,2012,4,9,30002
674549,674549,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,708.0,30.0,TGAL,1710.64,2012-06-08,2012,6,8,30002
675090,675090,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,483.0,30.0,TGAL,1332.47,2012-06-08,2012,6,8,30002
841798,841798,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,578.0,32.0,TGAL,1573.70,2012-07-10,2012,7,10,30002
842341,842341,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,507.0,30.0,TGAL,1382.63,2012-07-10,2012,7,10,30002
1008927,1008927,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,689.0,30.0,TGAL,1764.59,2012-08-08,2012,8,8,30002
1009567,1009567,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,502.0,32.0,TGAL,1439.48,2012-08-08,2012,8,8,30002
1178722,1178722,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,725.0,29.0,TGAL,1821.83,2012-09-10,2012,9,10,30002
1179366,1179366,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,509.0,28.0,TGAL,1454.81,2012-09-10,2012,9,10,30002
1343399,1343399,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,620.0,32.0,TGAL,1654.88,2012-10-08,2012,10,8,30002
1343401,1343401,13843,333 S MOCK RD,53434.0,RWTR,300.0,139,172.0,9.0,TGAL,261.44,2012-10-26,2012,10,26,30002
1343908,1343908,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,542.0,30.0,TGAL,1527.08,2012-10-08,2012,10,8,30002
1343910,1343910,14127,333 S MOCK RD,53434.0,RWTR,300.0,139,209.0,13.0,TGAL,418.00,2012-10-26,2012,10,26,30002
1510845,1510845,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,449.0,21.0,TGAL,1028.89,2012-11-08,2012,11,8,30002
1511343,1511343,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,428.0,20.0,TGAL,956.32,2012-11-08,2012,11,8,30002
1674586,1674586,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,672.0,31.0,TGAL,1737.56,2012-12-07,2012,12,7,30002
1675166,1675166,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,464.0,31.0,TGAL,1356.26,2012-12-07,2012,12,7,30002
1839303,1839303,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,764.0,35.0,TGAL,1883.84,2013-01-09,2013,1,9,30002
1839910,1839910,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,487.0,34.0,TGAL,1406.63,2013-01-09,2013,1,9,30002
2002995,2002995,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,587.0,27.0,TGAL,1593.41,2013-02-08,2013,2,8,30002
2003582,2003582,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,453.0,28.0,TGAL,1332.17,2013-02-08,2013,2,8,30002
2168375,2168375,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,712.0,31.0,TGAL,1801.16,2013-03-08,2013,3,8,30002
2169031,2169031,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,450.0,29.0,TGAL,1325.60,2013-03-08,2013,3,8,30002
2333491,2333491,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,548.0,29.0,TGAL,1508.00,2013-04-08,2013,4,8,30002
2333940,2333940,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,645.0,31.0,TGAL,1752.65,2013-04-08,2013,4,8,30002
2499041,2499041,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,527.0,32.0,TGAL,1462.01,2013-06-10,2013,6,10,30002
2499547,2499547,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,517.0,30.0,TGAL,1472.33,2013-06-10,2013,6,10,30002
2662353,2662353,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,499.0,29.0,TGAL,1450.93,2013-07-09,2013,7,9,30002
2662856,2662856,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,488.0,31.0,TGAL,1459.26,2013-07-09,2013,7,9,30002
2826757,2826757,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,548.0,30.0,TGAL,1562.16,2013-08-08,2013,8,8,30002
2827358,2827358,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,517.0,23.0,TGAL,1292.34,2013-08-08,2013,8,8,30002
2992886,2992886,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,613.0,33.0,TGAL,1702.89,2013-09-10,2013,9,10,30002
2993392,2993392,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,499.0,37.0,TGAL,1484.23,2013-09-10,2013,9,10,30002
3157600,3157600,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,623.0,29.0,TGAL,1719.39,2013-10-08,2013,10,8,30002
3158105,3158105,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,568.0,32.0,TGAL,1640.86,2013-10-08,2013,10,8,30002
3323819,3323819,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,499.0,29.0,TGAL,1450.93,2013-11-07,2013,11,7,30002
3324336,3324336,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,484.0,29.0,TGAL,1450.18,2013-11-07,2013,11,7,30002
3486624,3486624,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,665.0,34.0,TGAL,1788.69,2013-12-09,2013,12,9,30002
3487147,3487147,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,484.0,33.0,TGAL,1450.18,2013-12-09,2013,12,9,30002
3647221,3647221,13843,333 S MOCK RD,198203.0,RWTR,300.0,NaN,NaN,NaN,TGAL,1754.04,2014-01-09,2014,1,9,30002
3647223,3647223,13843,333 S MOCK RD,198203.0,RWTR,300.0,139,686.0,16.0,TGAL,675.41,2014-01-16,2014,1,16,30002
3647840,3647840,14127,333 S MOCK RD,198203.0,RWTR,300.0,NaN,NaN,NaN,TGAL,1443.37,2014-01-09,2014,1,9,30002
3647842,3647842,14127,333 S MOCK RD,198203.0,RWTR,300.0,139,512.0,18.0,TGAL,599.45,2014-01-16,2014,1,16,30002
3929755,3929755,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,967.0,45.0,TGAL,2738.49,2014-02-10,2014,2,10,30002
3929769,3929769,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,711.0,42.0,TGAL,2335.95,2014-02-10,2014,2,10,30002
3969381,3969381,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1900.0,29.0,TGAL,3826.44,2014-03-10,2014,3,10,30002
3969943,3969943,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,515.0,31.0,TGAL,1520.55,2014-03-10,2014,3,10,30002
4132310,4132310,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,803.0,29.0,TGAL,2016.39,2014-04-08,2014,4,8,30002
4132796,4132796,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,438.0,29.0,TGAL,1345.76,2014-04-08,2014,4,8,30002
4320273,4320273,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,491.0,32.0,TGAL,1432.77,2014-06-09,2014,6,9,30002
4320830,4320830,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,518.0,32.0,TGAL,1527.36,2014-06-09,2014,6,9,30002
4506460,4506460,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,491.0,29.0,TGAL,1483.23,2014-07-09,2014,7,9,30002
4507031,4507031,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,456.0,29.0,TGAL,1435.45,2014-07-09,2014,7,9,30002
4694905,4694905,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,562.0,30.0,TGAL,1650.08,2014-08-11,2014,8,11,30002
4695504,4695504,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,523.0,30.0,TGAL,1592.90,2014-08-11,2014,8,11,30002
4884377,4884377,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,689.0,33.0,TGAL,1891.98,2014-09-09,2014,9,9,30002
4884916,4884916,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,647.0,33.0,TGAL,1884.30,2014-09-09,2014,9,9,30002
5073549,5073549,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,587.0,29.0,TGAL,1708.83,2014-10-08,2014,10,8,30002
5074075,5074075,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,644.0,29.0,TGAL,1877.25,2014-10-08,2014,10,8,30002
5264150,5264150,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,542.0,29.0,TGAL,1603.08,2014-11-07,2014,11,7,30002
5264795,5264795,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,626.0,30.0,TGAL,1834.95,2014-11-07,2014,11,7,30002
5450611,5450611,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,474.0,34.0,TGAL,1443.28,2014-12-08,2014,12,8,30002
5451059,5451059,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,481.0,33.0,TGAL,1494.20,2014-12-08,2014,12,8,30002
5636270,5636270,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,581.0,33.0,TGAL,1694.73,2015-01-09,2015,1,9,30002
5636793,5636793,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,550.0,34.0,TGAL,1656.35,2015-01-09,2015,1,9,30002
5820107,5820107,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,496.0,28.0,TGAL,1494.98,2015-02-09,2015,2,9,30002
5820640,5820640,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,387.0,27.0,TGAL,1273.30,2015-02-09,2015,2,9,30002
6005847,6005847,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,533.0,28.0,TGAL,1581.93,2015-03-09,2015,3,9,30002
6006344,6006344,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,417.0,29.0,TGAL,1343.80,2015-03-09,2015,3,9,30002
6193347,6193347,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,492.0,30.0,TGAL,1485.58,2015-04-08,2015,4,8,30002
6193833,6193833,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,453.0,30.0,TGAL,1428.40,2015-04-08,2015,4,8,30002
6379693,6379693,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,504.0,33.0,TGAL,1513.78,2015-06-08,2015,6,8,30002
6380146,6380146,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,435.0,32.0,TGAL,1386.10,2015-06-08,2015,6,8,30002
6565155,6565155,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,447.0,29.0,TGAL,1402.87,2015-07-09,2015,7,9,30002
6565660,6565660,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,354.0,30.0,TGAL,1215.61,2015-07-09,2015,7,9,30002
6751417,6751417,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,461.0,29.0,TGAL,1436.33,2015-08-10,2015,8,10,30002
6751932,6751932,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,351.0,29.0,TGAL,1208.44,2015-08-10,2015,8,10,30002
6944164,6944164,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,620.0,33.0,TGAL,1804.46,2015-09-09,2015,9,9,30002
6944690,6944690,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,453.0,32.0,TGAL,1452.22,2015-09-09,2015,9,9,30002
7131540,7131540,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,482.0,29.0,TGAL,1486.52,2015-10-08,2015,10,8,30002
7132066,7132066,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,380.0,30.0,TGAL,1277.75,2015-10-08,2015,10,8,30002
7319919,7319919,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,796.0,30.0,TGAL,2108.94,2015-11-06,2015,11,6,30002
7320387,7320387,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,398.0,30.0,TGAL,1320.77,2015-11-06,2015,11,6,30002
7504909,7504909,13843,333 S MOCK RD,206411.0,RWTR,300.0,NaN,NaN,NaN,TGAL,81128.42,2015-12-08,2015,12,8,30002
7504911,7504911,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,47241.0,34.0,TGAL,2062.23,2015-12-11,2015,12,11,30002
7505530,7505530,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,424.0,34.0,TGAL,1382.91,2015-12-08,2015,12,8,30002
7689616,7689616,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,139,832.0,32.0,TGAL,2171.22,2016-01-08,2016,1,8,30002
7690284,7690284,14127.0,333 S MOCK RD,206411.0,RWTR,300.0,139,932.0,33.0,TGAL,2420.81,2016-01-08,2016,1,8,30002
7873216,7873216,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,682.0,28.0,TGAL,1911.72,2016-02-08,2016,2,8,30002
7873681,7873681,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,-43.0,27.0,TGAL,1050.70,2016-02-08,2016,2,8,30002
8060548,8060548,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,780.0,30.0,TGAL,2081.26,2016-03-08,2016,3,8,30002
8061048,8061048,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,366.0,30.0,TGAL,1244.29,2016-03-08,2016,3,8,30002
8247211,8247211,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,708.0,29.0,TGAL,1956.70,2016-04-08,2016,4,8,30002
8247685,8247685,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,1564.0,29.0,TGAL,3514.17,2016-04-08,2016,4,8,30002
8432441,8432441,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,711.0,32.0,TGAL,1961.89,2016-05-09,2016,5,9,30002
8432960,8432960,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,2231.0,32.0,TGAL,4668.08,2016-05-09,2016,5,9,30002
8617577,8617577,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,729.0,30.0,TGAL,1993.03,2016-06-08,2016,6,8,30002
8618089,8618089,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,502.0,29.0,TGAL,1569.33,2016-06-08,2016,6,8,30002
8802675,8802675,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,663.0,29.0,TGAL,1878.85,2016-07-11,2016,7,11,30002
8803155,8803155,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,533.0,30.0,TGAL,1643.42,2016-07-11,2016,7,11,30002
8985437,8985437,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,866.0,33.0,TGAL,2342.38,2016-08-08,2016,8,8,30002
8985926,8985926,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,492.0,32.0,TGAL,1622.52,2016-08-08,2016,8,8,30002
9166002,9166002,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,741.0,28.0,TGAL,2114.88,2016-09-09,2016,9,9,30002
9166485,9166485,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,481.0,29.0,TGAL,1594.91,2016-09-09,2016,9,9,30002
9349105,9349105,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1044.0,33.0,TGAL,2666.34,2016-10-10,2016,10,10,30002
9349615,9349615,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,633.0,30.0,TGAL,1976.43,2016-10-10,2016,10,10,30002
9530000,9530000,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,577.0,30.0,TGAL,1799.15,2016-11-08,2016,11,8,30002
9530462,9530462,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,494.0,32.0,TGAL,1627.54,2016-11-08,2016,11,8,30002
9710891,9710891,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,866.0,30.0,TGAL,2342.38,2016-12-08,2016,12,8,30002
9711391,9711391,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,468.0,31.0,TGAL,1562.28,2016-12-08,2016,12,8,30002
9890845,9890845,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,139,1018.0,34.0,TGAL,2619.02,2017-01-10,2017,1,10,30002
9891225,9891225,14127.0,333 S MOCK RD,206411.0,RWTR,300.0,139,585.0,34.0,TGAL,1855.95,2017-01-10,2017,1,10,30002
10059203,10059203,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,771.0,27.0,TGAL,2169.48,2017-02-08,2017,2,8,30002
10059622,10059622,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,537.0,27.0,TGAL,1735.47,2017-02-08,2017,2,8,30002
10234783,10234783,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,921.0,30.0,TGAL,2442.48,2017-03-09,2017,3,9,30002
10235291,10235291,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,561.0,29.0,TGAL,1795.71,2017-03-09,2017,3,9,30002
10419018,10419018,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,921.0,29.0,TGAL,2442.48,2017-04-10,2017,4,10,30002
10419541,10419541,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,428.0,30.0,TGAL,1461.88,2017-04-10,2017,4,10,30002
10600093,10600093,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,966.0,31.0,TGAL,2524.38,2017-05-09,2017,5,9,30002
10600582,10600582,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,563.0,31.0,TGAL,1800.73,2017-05-09,2017,5,9,30002
10782943,10782943,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1038.0,30.0,TGAL,2655.42,2017-06-09,2017,6,9,30002
10783446,10783446,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,517.0,30.0,TGAL,1685.27,2017-06-09,2017,6,9,30002
10965502,10965502,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,873.0,30.0,TGAL,2355.12,2017-07-10,2017,7,10,30002
10965985,10965985,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,672.0,30.0,TGAL,2069.49,2017-07-10,2017,7,10,30002
11145457,11145457,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,901.0,32.0,TGAL,2406.08,2017-08-09,2017,8,9,30002
11145971,11145971,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,618.0,32.0,TGAL,1938.78,2017-08-09,2017,8,9,30002
11330985,11330985,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,948.0,29.0,TGAL,2491.62,2017-09-12,2017,9,12,30002
11331528,11331528,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,565.0,29.0,TGAL,1805.75,2017-09-12,2017,9,12,30002
11513463,11513463,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1085.0,33.0,TGAL,2740.96,2017-10-10,2017,10,10,30002
11513967,11513967,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,568.0,34.0,TGAL,1813.28,2017-10-10,2017,10,10,30002
11695218,11695218,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,950.0,29.0,TGAL,2495.26,2017-11-08,2017,11,8,30002
11695730,11695730,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,471.0,28.0,TGAL,1569.81,2017-11-08,2017,11,8,30002
11876979,11876979,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,984.0,31.0,TGAL,2557.14,2017-12-08,2017,12,8,30002
11877479,11877479,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,596.0,31.0,TGAL,1883.56,2017-12-08,2017,12,8,30002
12057707,12057707,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,NaN,NaN,NaN,TGAL,86480.98,2018-01-09,2018,1,9,30002
12057709,12057709,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,139,1096.0,34.0,TGAL,2760.98,2018-01-10,2018,1,10,30002
12058241,12058241,14127.0,333 S MOCK RD,206411.0,RWTR,300.0,139,591.0,34.0,TGAL,1871.01,2018-01-09,2018,1,9,30002
12242237,12242237,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,795.0,27.0,TGAL,2213.16,2018-02-09,2018,2,9,30002
12242751,12242751,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,452.0,27.0,TGAL,1522.12,2018-02-08,2018,2,8,30002
12423825,12423825,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1242.0,30.0,TGAL,3090.14,2018-03-12,2018,3,12,30002
12424348,12424348,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,472.0,30.0,TGAL,1604.47,2018-03-09,2018,3,9,30002
12606445,12606445,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1015.0,28.0,TGAL,2667.92,2018-04-10,2018,4,10,30002
12606941,12606941,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,492.0,28.0,TGAL,1655.67,2018-04-09,2018,4,9,30002
12787949,12787949,13843,333 S MOCK RD,206411.0,RWTR,300.0,139,1036.0,31.0,TGAL,2941.34,2018-05-09,2018,5,9,30002
12788525,12788525,14127,333 S MOCK RD,206411.0,RWTR,300.0,139,635.0,31.0,TGAL,2234.33,2018-05-09,2018,5,9,30002
12969389,12969389,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,831.0,26.0,TGAL,2325.68,2018-06-11,2018,6,11,30002
12969887,12969887,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,622.0,26.0,TGAL,1988.47,2018-06-11,2018,6,11,30002
13151549,13151549,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,921.0,30.0,TGAL,2493.08,2018-07-10,2018,7,10,30002
13152044,13152044,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,617.0,30.0,TGAL,1975.67,2018-07-10,2018,7,10,30002
13334366,13334366,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,1167.0,33.0,TGAL,2950.64,2018-08-09,2018,8,9,30002
13334894,13334894,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,1048.0,33.0,TGAL,2810.93,2018-08-09,2018,8,9,30002
13518185,13518185,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,1055.0,28.0,TGAL,2742.32,2018-09-11,2018,9,11,30002
13518703,13518703,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,835.0,28.0,TGAL,2414.75,2018-09-11,2018,9,11,30002
13719072,13719072,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,1123.0,34.0,TGAL,2868.80,2018-10-15,2018,10,15,30002
13719074,13719074,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,857.0,29.0,TGAL,2374.04,2018-11-08,2018,10,8,30002
13719076,13719076,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,983.0,34.0,TGAL,2608.40,2018-12-07,2018,10,7,30002
13720330,13720330,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,974.0,34.0,TGAL,2673.29,2018-10-15,2018,10,15,30002
13720332,13720332,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,677.0,29.0,TGAL,2120.87,2018-11-08,2018,10,8,30002
13720334,13720334,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,585.0,34.0,TGAL,1893.75,2018-12-07,2018,10,7,30002
14221414,14221414,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,857.0,29.0,TGAL,2374.04,2018-11-08,2018,11,8,30002
14221762,14221762,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,677.0,29.0,TGAL,2120.87,2018-11-08,2018,11,8,30002
14539032,14539032,13843,333 S MOCK RD,235015.0,RWTR,300.0,NaN,NaN,NaN,TGAL,20815.94,2019-01-09,2019,1,9,30002
14539033,14539033,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,11544.0,31.0,TGAL,2215.94,2019-01-10,2019,1,10,30002
14539046,14539046,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,557.0,31.0,TGAL,1822.07,2019-01-09,2019,1,9,30002
14578948,14578948,13843,333 S MOCK RD,235015.0,RWTR,300.0,139,700.0,28.0,TGAL,2082.02,2019-02-08,2019,2,8,30002
14579497,14579497,14127,333 S MOCK RD,235015.0,RWTR,300.0,139,617.0,28.0,TGAL,1975.67,2019-02-08,2019,2,8,30002

In [33]:
water[water['Charge Amount'] > 10000]

,ChargeID,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
1115212,1115212,42336,4000 GILLIONVILLE RD,42174.0,RWTR,300.0,130,9998.0,12.0,TGAL,14008.39,2012-08-08,2012,8,8,12517
7398802,7398802,33413,2609 FLYNN CT,208751.0,RWTR,300.0,NaN,NaN,NaN,TGAL,16806.81,2015-11-19,2015,11,19,16862
7504909,7504909,13843,333 S MOCK RD,206411.0,RWTR,300.0,NaN,NaN,NaN,TGAL,81128.42,2015-12-08,2015,12,8,30002
8248669,8248669,14282,1511 WHITING DR,118220.0,RWTR,300.0,130,9844.0,14.0,TGAL,17032.73,2016-04-22,2016,4,22,30122
8593754,8593754,75823.0,2503 DAYLOR CT,38577.0,RWTR,300.0,NaN,NaN,NaN,TGAL,36414.63,2016-05-23,2016,5,23,4764
9053810,9053810,31433,1200 KINGSTOWN CT,66010.0,RWTR,300.0,130,9584.0,15.0,TGAL,17445.99,2016-08-17,2016,8,17,20494
11772120,11772120,33353,2220 FRIAR TUCK LN,226251.0,RWTR,300.0,NaN,NaN,NaN,TGAL,14756.37,2017-11-21,2017,11,21,16841
12057707,12057707,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,NaN,NaN,NaN,TGAL,86480.98,2018-01-09,2018,1,9,30002
14063829,14063829,43709,636 W SOCIETY AVE,22703.0,RWTR,300.0,130,9995.0,8.0,TGAL,18591.08,2018-12-27,2018,10,27,8344
14078327,14078327,44980,905 N DAVIS ST,28608.0,RWTR,300.0,NaN,NaN,NaN,TGAL,18599.77,2018-11-28,2018,10,28,9116
14339915,14339915,44980,905 N DAVIS ST,28608.0,RWTR,300.0,NaN,NaN,NaN,TGAL,18599.77,2018-11-28,2018,11,28,9116
14539032,14539032,13843,333 S MOCK RD,235015.0,RWTR,300.0,NaN,NaN,NaN,TGAL,20815.94,2019-01-09,2019,1,9,30002

In [34]:
water[water['Charge Amount'] > 86000]

,ChargeID,Premise,Premise Address,Customer,Service Type,Service Number,Service Rate,Consumption,Days of Service,Unit of Measure,Charge Amount,Charge Date,Year,Month,Day,PrimaryID
12057707,12057707,13843.0,333 S MOCK RD,206411.0,RWTR,300.0,NaN,NaN,NaN,TGAL,86480.98,2018-01-09,2018,1,9,30002

In [35]:
df_400_2 = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_400_2.csv")
df_400_2_housing = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_400_2_housing.csv")
df_501_2 = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_501_2.csv")
df_501_2_housing = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_501_2_housing.csv")
df_1000_2 = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_1000_2.csv")
df_1000_2_housing = pd.read_csv(PATH + "Raw-Data/water_investigate/rwtr_high_values_1000_2_housing.csv")

In [43]:
print(df_400_2['Consumption'].sum() / df_400_2.shape[0])
print(df_400_2_housing['Consumption'].sum() / df_400_2_housing.shape[0])

7.965987305946779